# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cbc47571eebc6854486e57d9552bceeb5d50e310622cd4206e3be66738c0b29a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Public API for conversion."""

import liter_llm._internal_bindings as _rust

from ._internal_bindings import CustomProviderConfig, DefaultClient


def create_client(
    api_key: str,
    base_url: str | None = None,
    timeout_secs: int | None = None,
    max_retries: int | None = None,
    model_hint: str | None = None,
) -> DefaultClient:
    """Create a new LLM client with simple scalar configuration."""
    return _rust.create_client(api_key, base_url, timeout_secs, max_retries, model_hint)


def create_client_from_json(json: str) -> DefaultClient:
    """Create a new LLM client from a JSON string."""
    return _rust.create_client_from_json(json)


def register_custom_provider(config: CustomProviderConfig) -> None:
    """Register a custom provider in the global runtime registry."""
    return _rust.register_custom_provider(config)


def unregister_custom_provider(name: str) -> bool:
    """Remove a previously registered custom provider by name."""
    return _rust.unregister_custom_provider(name)
