// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f2b982477f17273d62854b3a5f85fa0b090d16b4ccef74491894e102802b6e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    globalSetup: './globalSetup.ts',
  },
});
