// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cdb265c49b83491bfca9765e44f467f35e7839dcaab8d4b0f930ebdeb894bcc0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    globalSetup: "./globalSetup.ts",
  },
});
