# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: batches
defmodule E2e.BatchesTest do
  use ExUnit.Case, async: true

  describe "edge_batch_already_cancelled" do
    test "Attempt to cancel an already-cancelled batch" do
      assert {:error, _} = LiterLlm.cancel_batch_async(nil)
    end
  end

  describe "edge_batch_empty_list" do
    test "List batches when no batches exist" do
      {:ok, result} = LiterLlm.list_batches_async(nil)
      assert length(result.data) == 0
    end
  end

  describe "error_batch_auth_401" do
    test "401 Unauthorized when creating a batch with invalid API key" do
      assert {:error, _} = LiterLlm.create_batch_async(nil)
    end
  end

  describe "error_batch_invalid_file" do
    test "400 Bad Request when creating a batch with invalid input file" do
      assert {:error, _} = LiterLlm.create_batch_async(nil)
    end
  end

  describe "error_batch_not_found" do
    test "404 Not Found when retrieving a nonexistent batch" do
      assert {:error, _} = LiterLlm.retrieve_batch_async(nil)
    end
  end

  describe "smoke_batch_completed" do
    test "Retrieve a completed batch job with output file" do
      {:ok, result} = LiterLlm.retrieve_batch_async(nil)
      assert result.id != ""
      assert String.trim(result.status) == "completed"
    end
  end

  describe "smoke_cancel_batch" do
    test "Cancel a running batch job" do
      {:ok, result} = LiterLlm.cancel_batch_async(nil)
      assert result.id != ""
      assert String.trim(result.status) == "cancelling"
    end
  end

  describe "smoke_create_batch" do
    test "Create a new batch processing job" do
      {:ok, result} = LiterLlm.create_batch_async(nil)
      assert result.id != ""
      assert String.trim(result.status) == "validating"
    end
  end

  describe "smoke_list_batches" do
    test "List all batch jobs" do
      {:ok, result} = LiterLlm.list_batches_async(nil)
      assert length(result.data) == 2
    end
  end

  describe "smoke_retrieve_batch" do
    test "Retrieve the status of a batch job" do
      {:ok, result} = LiterLlm.retrieve_batch_async(nil)
      assert result.id != ""
      assert String.trim(result.status) == "in_progress"
    end
  end
end
