# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d17ec785bf212ac5e26799f681300548ea53a2106ac8db6c729715f57f8aa47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: error-handling
defmodule E2e.ErrorHandlingTest do
  use ExUnit.Case, async: false

  describe "anthropic_error_auth" do
    test "401 Authentication error returned by the Anthropic API when the API key is invalid" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "auth_401" do
    test "401 Unauthorized error when API key is invalid or missing" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "azure_error_auth" do
    test "Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "bad_request_400" do
    test "400 Bad Request error when a parameter value is invalid" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "bedrock_error_auth" do
    test "AWS Bedrock returns 403 Forbidden (not 401) when credentials are missing, expired, or the IAM role lacks bedrock:InvokeModel permission — verifies the error is mapped to Authentication" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "content_policy_violation" do
    test "400 error when a request is rejected due to content policy" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "context_window_exceeded" do
    test "400 error when the prompt exceeds the model's maximum context length" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "empty_response_body" do
    test "200 OK response with an empty JSON object body, missing required fields" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "forbidden_403" do
    test "403 Forbidden error when the API key does not have access to the requested resource" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "gateway_timeout_504" do
    test "504 Gateway Timeout error when the upstream service times out" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "github_copilot_error_auth" do
    test "401 Authentication error returned by the GitHub Copilot API when the token is invalid or expired" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "not_found_404" do
    test "404 Not Found error when requesting a model that does not exist" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "rate_limit_429" do
    test "429 Too Many Requests error when the rate limit is exceeded" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "server_error_500" do
    test "500 Internal Server Error from the upstream API" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "service_unavailable_502" do
    test "502 Bad Gateway error when the upstream service is unavailable" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "timeout_error" do
    test "408 Request Timeout error when the API request takes too long to complete" do
      _result = LiterLlm.chat_async(nil)
    end
  end

  describe "vertex_error_auth" do
    test "Google Vertex AI returns 401 Unauthorized when the OAuth2 token is missing, expired, or the service account lacks aiplatform.endpoints.predict permission — verifies the error is mapped to Authentication" do
      _result = LiterLlm.chat_async(nil)
    end
  end
end
