# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:267511345373d694a4eb00284d4cda5497b98d42785cea970aaebabdba567ebd
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: list-models
defmodule E2e.ListModelsTest do
  use ExUnit.Case, async: false

  describe "empty_model_list" do
    test "empty_model_list" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/empty_model_list")

      {:ok, result} = LiterLlm.defaultclient_list_models_async(client)
      assert length(result.data) >= 0
      assert length(result.data) == 0
    end
  end

  describe "list_models_error_401" do
    test "list_models_error_401" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_error_401")

      assert {:error, __reason} = LiterLlm.defaultclient_list_models_async(client)
      # skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
    end
  end

  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

  describe "list_models_error_500" do
    test "list_models_error_500" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_error_500")

      assert {:error, __reason} = LiterLlm.defaultclient_list_models_async(client)
      # skipped: declared error variant 'ServerError' not yet preserved as a distinct identity by this backend's generator
    end
  end

  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend

  describe "list_models_filtered" do
    test "list_models_filtered" do
      {:ok, client} =
        LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_filtered")

      {:ok, result} = LiterLlm.defaultclient_list_models_async(client)
      assert length(result.data) >= 5
      assert Enum.at(result.data, 0).object == "model"
    end
  end
end
