# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb3119dfec6a50e286ea91fcb473b823f08cb4e4276e374fb2b7628fbe4131ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: moderate
defmodule E2e.ModerateTest do
  use ExUnit.Case, async: false

  describe "edge_moderate_all_categories" do
    test "Moderation response with multiple categories flagged" do
      result = LiterLlm.moderate_async("\"Extremely harmful content targeting multiple categories\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == true
    end
  end

  describe "edge_moderate_empty_input" do
    test "Moderation with empty string input" do
      result = LiterLlm.moderate_async("\"\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == false
    end
  end

  describe "error_moderate_auth_401" do
    test "401 Unauthorized for moderation with invalid API key" do
      _result = LiterLlm.moderate_async("\"Hello\"")
    end
  end

  describe "error_moderate_bad_request" do
    test "400 Bad Request for moderation with invalid model" do
      _result = LiterLlm.moderate_async("\"Hello\"")
    end
  end

  describe "smoke_moderate_batch" do
    test "Moderate multiple inputs in a single request" do
      result = LiterLlm.moderate_async("[\"Hello world\",\"Nice weather today\"]")
      assert length(result.results) == 2
      assert result.results["0"].flagged == false
    end
  end

  describe "smoke_moderate_flagged" do
    test "Moderation detects flagged content" do
      result = LiterLlm.moderate_async("\"I want to hurt someone very badly\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == true
    end
  end

  describe "smoke_moderate_single" do
    test "Moderate a single non-flagged input" do
      result = LiterLlm.moderate_async("\"The weather is nice today.\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == false
    end
  end
end
