# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c366bdda2a3e402384ee5cc30c60e1ffb726aa2f3df85400e6bacc9938045a84
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: moderate
defmodule E2e.ModerateTest do
  use ExUnit.Case, async: false

  describe "edge_moderate_all_categories" do
    test "edge_moderate_all_categories" do
      result = LiterLlm.moderate_async("\"Extremely harmful content targeting multiple categories\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == true
    end
  end

  describe "edge_moderate_empty_input" do
    test "edge_moderate_empty_input" do
      result = LiterLlm.moderate_async("\"\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == false
    end
  end

  describe "error_moderate_auth_401" do
    test "error_moderate_auth_401" do
      _result = LiterLlm.moderate_async("\"Hello\"")
    end
  end

  describe "error_moderate_bad_request" do
    test "error_moderate_bad_request" do
      _result = LiterLlm.moderate_async("\"Hello\"")
    end
  end

  describe "smoke_moderate_batch" do
    test "smoke_moderate_batch" do
      result = LiterLlm.moderate_async("[\"Hello world\",\"Nice weather today\"]")
      assert length(result.results) == 2
      assert result.results["0"].flagged == false
    end
  end

  describe "smoke_moderate_flagged" do
    test "smoke_moderate_flagged" do
      result = LiterLlm.moderate_async("\"I want to hurt someone very badly\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == true
    end
  end

  describe "smoke_moderate_single" do
    test "smoke_moderate_single" do
      result = LiterLlm.moderate_async("\"The weather is nice today.\"")
      assert length(result.results) == 1
      assert result.results["0"].flagged == false
    end
  end
end
