# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8967f7c5bf4258a6d9689daf11694c1f6ba8b5326de8e278ef7cb3ad6a55507
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: ocr
defmodule E2e.OcrTest do
  use ExUnit.Case, async: false

  describe "ocr_error_400" do
    test "400 Bad Request error when OCR input has an invalid image format" do
      _result = LiterLlm.ocr_async(nil)
    end
  end

  describe "ocr_error_401" do
    test "401 Unauthorized error on OCR request due to invalid API credentials" do
      _result = LiterLlm.ocr_async(nil)
    end
  end

  describe "ocr_multi_page" do
    test "OCR request returning multiple pages of document content" do
      result = LiterLlm.ocr_async(nil)
      assert length(result.pages) == 2
      assert result.pages["0"].index == 0
      assert result.pages["1"].index == 1
    end
  end

  describe "ocr_url_document" do
    test "OCR request with a document URL input" do
      result = LiterLlm.ocr_async(nil)
    end
  end
end
