# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e21f432717362463b56e95ed71871cb13a1add69a9925b64ac4f286c8ed3e96f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: tool-calling
defmodule E2e.ToolCallingTest do
  use ExUnit.Case, async: true

  describe "anthropic_tool_calling" do
    test "Chat request to Anthropic provider with a tool definition; assistant responds with a tool call" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.choices) == 1
      assert result.choices["0"].message.tool_calls != ""
      assert String.trim(result.choices["0"].message.tool_calls["0"].function.name) == "get_weather"
      assert String.trim(result.choices["0"].finish_reason) == "tool_calls"
    end
  end

  describe "single_tool_call" do
    test "Chat request with a tool definition; assistant responds with a tool call" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.choices) == 1
      assert result.choices["0"].message.tool_calls != ""
      assert String.trim(result.choices["0"].message.tool_calls["0"].function.name) == "get_weather"
      assert String.trim(result.choices["0"].finish_reason) == "tool_calls"
    end
  end
end
