# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca4a32985805b95b986b8ab6e4003347d285ddaf6ba0648576cb7782d89d18f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: transcribe
defmodule E2e.TranscribeTest do
  use ExUnit.Case, async: false

  describe "edge_transcribe_empty_audio" do
    test "edge_transcribe_empty_audio" do
      result = LiterLlm.transcribe_async(nil)
      assert String.contains?(to_string(result.text), "")
    end
  end

  describe "edge_transcribe_with_timestamps" do
    test "edge_transcribe_with_timestamps" do
      result = LiterLlm.transcribe_async(nil)
      assert result.text != ""
      assert length(result.segments) == 3
      assert result.segments["0"].id == 0
    end
  end

  describe "error_transcribe_auth_401" do
    test "error_transcribe_auth_401" do
      _result = LiterLlm.transcribe_async(nil)
    end
  end

  describe "error_transcribe_bad_format" do
    test "error_transcribe_bad_format" do
      _result = LiterLlm.transcribe_async(nil)
    end
  end

  describe "smoke_transcribe_basic" do
    test "smoke_transcribe_basic" do
      result = LiterLlm.transcribe_async(nil)
      assert String.contains?(to_string(result.text), "Hello, this is a test transcription.")
    end
  end

  describe "smoke_transcribe_with_language" do
    test "smoke_transcribe_with_language" do
      result = LiterLlm.transcribe_async(nil)
      assert String.contains?(to_string(result.text), "Hallo, dies ist ein Testtranskription.")
    end
  end
end
