// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c40070bdf4d3940a7b1a04015347f2aed1638b0a6f48f384a2b0efc59f6f8ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: batches.</summary>
public class BatchesTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_EdgeBatchAlreadyCancelled()
    {
        // Attempt to cancel an already-cancelled batch
        await Assert.ThrowsAsync<LiterLlmException>(() => LiterLlmLib.CancelBatch("batch-cancelled001"));
    }

    [Fact]
    public async Task Test_EdgeBatchEmptyList()
    {
        // List batches when no batches exist
        var result = await LiterLlmLib.ListBatches("{}");
        Assert.Equal(0, result.Data.Count);
    }

    [Fact]
    public async Task Test_ErrorBatchAuth401()
    {
        // 401 Unauthorized when creating a batch with invalid API key
        await Assert.ThrowsAsync<LiterLlmException>(() => LiterLlmLib.CreateBatch(null));
    }

    [Fact]
    public async Task Test_ErrorBatchInvalidFile()
    {
        // 400 Bad Request when creating a batch with invalid input file
        await Assert.ThrowsAsync<LiterLlmException>(() => LiterLlmLib.CreateBatch(null));
    }

    [Fact]
    public async Task Test_ErrorBatchNotFound()
    {
        // 404 Not Found when retrieving a nonexistent batch
        await Assert.ThrowsAsync<LiterLlmException>(() => LiterLlmLib.RetrieveBatch("batch-nonexistent"));
    }

    [Fact]
    public async Task Test_SmokeBatchCompleted()
    {
        // Retrieve a completed batch job with output file
        var result = await LiterLlmLib.RetrieveBatch("batch-ghi789");
        Assert.False(string.IsNullOrEmpty(result.Id?.ToString()));
        Assert.Equal("completed", result.Status.Trim());
    }

    [Fact]
    public async Task Test_SmokeCancelBatch()
    {
        // Cancel a running batch job
        var result = await LiterLlmLib.CancelBatch("batch-def456");
        Assert.False(string.IsNullOrEmpty(result.Id?.ToString()));
        Assert.Equal("cancelling", result.Status.Trim());
    }

    [Fact]
    public async Task Test_SmokeCreateBatch()
    {
        // Create a new batch processing job
        var result = await LiterLlmLib.CreateBatch(null);
        Assert.False(string.IsNullOrEmpty(result.Id?.ToString()));
        Assert.Equal("validating", result.Status.Trim());
    }

    [Fact]
    public async Task Test_SmokeListBatches()
    {
        // List all batch jobs
        var result = await LiterLlmLib.ListBatches("{}");
        Assert.Equal(2, result.Data.Count);
    }

    [Fact]
    public async Task Test_SmokeRetrieveBatch()
    {
        // Retrieve the status of a batch job
        var result = await LiterLlmLib.RetrieveBatch("batch-abc123");
        Assert.False(string.IsNullOrEmpty(result.Id?.ToString()));
        Assert.Equal("in_progress", result.Status.Trim());
    }
}
