// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:92683ceabdc154eda160b584314ead660f50cd2fb0a4d04d6ba7592cb2dd33df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: cache.</summary>
public class CacheTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_CacheHit()
    {
        // Tests that identical chat requests return cached response
        var result = await LiterLlmLib.Chat(null);
        Assert.True(result.CacheHit);
    }

    [Fact]
    public async Task Test_CacheMissTtl()
    {
        // Tests that cache expires after TTL
        var result = await LiterLlmLib.Chat(null);
        Assert.True(result.CacheHit);
    }

    [Fact]
    public async Task Test_CacheOpendalMemory()
    {
        // Cache hit with OpenDAL memory backend returns cached response on repeat request
        var result = await LiterLlmLib.Chat(null);
        Assert.True(result.CacheHit);
    }

    [Fact]
    public async Task Test_CacheStreamBypass()
    {
        // Tests that streaming requests bypass cache entirely
        var result = await LiterLlmLib.ChatStream(null);
        Assert.True(result.CacheBypassed);
    }
}
