// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:deb6bddd7d8b8846744aeba0fd8d6f9b3a17efa8bb3e3b27e2ca5fd4bdbd63d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: embed.</summary>
public class EmbedTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_BatchEmbed()
    {
        // Embedding request with multiple input strings returns one embedding object per input
        var result = await LiterLlmLib.Embed(new List<string>() { "Hello", "World" });
        Assert.Equal(2, result.Data.Count);
        Assert.Equal(5, result.Data["0"].Embedding.Count);
    }

    [Fact]
    public async Task Test_EdgeEmbedBatchInput()
    {
        // Embedding request with multiple inputs returns multiple embedding objects
        var result = await LiterLlmLib.Embed(new List<string>() { "Hello world", "Goodbye world" });
        Assert.Equal(2, result.Data.Count);
        Assert.True(result.Data["0"].Index == 0);
        Assert.True(result.Data["1"].Index == 1);
    }

    [Fact]
    public async Task Test_EdgeEmbedEmptyInput()
    {
        // Embedding request with empty string input returns empty data array
        var result = await LiterLlmLib.Embed("");
        Assert.Equal(0, result.Data.Count);
    }

    [Fact]
    public async Task Test_EmbedEncodingFormat()
    {
        // Embedding request with explicit encoding_format of float returns float array embeddings
        var result = await LiterLlmLib.Embed("Test input");
        Assert.Equal(1, result.Data.Count);
        Assert.Equal(5, result.Data["0"].Embedding.Count);
    }

    [Fact]
    public async Task Test_EmbedError401()
    {
        // 401 Unauthorized error on embedding request when API key is invalid
        await Assert.ThrowsAsync<LiterLlmException>(() => LiterLlmLib.Embed("Hello world"));
    }

    [Fact]
    public async Task Test_EmbedWithDimensions()
    {
        // Embedding request with explicit dimensions parameter returns embeddings of the requested size
        var result = await LiterLlmLib.Embed("Hello world");
        Assert.Equal(1, result.Data.Count);
        Assert.Equal(8, result.Data["0"].Embedding.Count);
    }

    [Fact]
    public async Task Test_LocalEmbedOllama()
    {
        // Embedding request via Ollama local provider with all-minilm model
        var result = await LiterLlmLib.Embed("The quick brown fox jumps over the lazy dog");
        Assert.Equal(1, result.Data.Count);
        Assert.Equal(32, result.Data["0"].Embedding.Count);
    }
}
