// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a60ff9a1cadbd6f63ac38065d05cf6a4d040c1311cef45b2506d817c406b7af9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: error-handling.</summary>
public class ErrorHandlingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_AnthropicErrorAuth()
    {
        // 401 Authentication error returned by the Anthropic API when the API key is invalid
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/anthropic_error_auth";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_Auth401()
    {
        // 401 Unauthorized error when API key is invalid or missing
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/auth_401";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_AzureErrorAuth()
    {
        // Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/azure_error_auth";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_BadRequest400()
    {
        // 400 Bad Request error when a parameter value is invalid
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/bad_request_400";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_BedrockErrorAuth()
    {
        // AWS Bedrock returns 403 Forbidden (not 401) when credentials are missing, expired, or the IAM role lacks bedrock:InvokeModel permission — verifies the error is mapped to Authentication
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/bedrock_error_auth";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_ContentPolicyViolation()
    {
        // 400 error when a request is rejected due to content policy
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/content_policy_violation";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_ContextWindowExceeded()
    {
        // 400 error when the prompt exceeds the model's maximum context length
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/context_window_exceeded";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_EmptyResponseBody()
    {
        // 200 OK response with an empty JSON object body, missing required fields
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/empty_response_body";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_Forbidden403()
    {
        // 403 Forbidden error when the API key does not have access to the requested resource
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/forbidden_403";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_GatewayTimeout504()
    {
        // 504 Gateway Timeout error when the upstream service times out
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/gateway_timeout_504";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_GithubCopilotErrorAuth()
    {
        // 401 Authentication error returned by the GitHub Copilot API when the token is invalid or expired
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/github_copilot_error_auth";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_NotFound404()
    {
        // 404 Not Found error when requesting a model that does not exist
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/not_found_404";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_RateLimit429()
    {
        // 429 Too Many Requests error when the rate limit is exceeded
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/rate_limit_429";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_ServerError500()
    {
        // 500 Internal Server Error from the upstream API
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/server_error_500";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_ServiceUnavailable502()
    {
        // 502 Bad Gateway error when the upstream service is unavailable
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/service_unavailable_502";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_TimeoutError()
    {
        // 408 Request Timeout error when the API request takes too long to complete
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/timeout_error";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }

    [Fact]
    public async Task Test_VertexErrorAuth()
    {
        // Google Vertex AI returns 401 Unauthorized when the OAuth2 token is missing, expired, or the service account lacks aiplatform.endpoints.predict permission — verifies the error is mapped to Authentication
        var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/vertex_error_auth";
        var client = LiterLlmLib.CreateClient("test-key", baseUrl);
        await Assert.ThrowsAsync<LiterLlmException>(() => client.Chat(null));
    }
}
