// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be536584f7c27bed88ba7815590f160f235118b1a169381f366e231bce816d0f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: tool-calling.</summary>
public class ToolCallingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_AnthropicToolCalling()
    {
        // Chat request to Anthropic provider with a tool definition; assistant responds with a tool call
        var result = await LiterLlmLib.Chat(null);
        Assert.Equal(1, result.Choices.Count);
        Assert.False(string.IsNullOrEmpty(result.Choices["0"].Message.ToolCalls?.ToString()));
        Assert.Equal("get_weather", result.Choices["0"].Message.ToolCalls["0"].Function.Name.Trim());
        Assert.Equal("tool_calls", result.Choices["0"].FinishReason.Trim());
    }

    [Fact]
    public async Task Test_SingleToolCall()
    {
        // Chat request with a tool definition; assistant responds with a tool call
        var result = await LiterLlmLib.Chat(null);
        Assert.Equal(1, result.Choices.Count);
        Assert.False(string.IsNullOrEmpty(result.Choices["0"].Message.ToolCalls?.ToString()));
        Assert.Equal("get_weather", result.Choices["0"].Message.ToolCalls["0"].Function.Name.Trim());
        Assert.Equal("tool_calls", result.Choices["0"].FinishReason.Trim());
    }
}
