# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc8e3dda26080cf112687d25124d8c54c5633af3ce069f1d0b6fcff81579e4b1
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'liter_llm'
require 'json'

RSpec.describe 'batches' do

  it 'edge_batch_already_cancelled: Attempt to cancel an already-cancelled batch' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_batch_already_cancelled')
    expect {
      client.cancel_batch_async('batch-cancelled001')
    }.to raise_error(RuntimeError) # skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'edge_batch_empty_list: List batches when no batches exist' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_batch_empty_list')
    result = client.list_batches_async(nil)
    expect(result.data.length).to eq(0)

  end


  it 'error_batch_auth_401: 401 Unauthorized when creating a batch with invalid API key' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/error_batch_auth_401')
    expect {
      client.create_batch_async(LiterLlm::CreateBatchRequest.new(completion_window: '24h', endpoint: '/v1/chat/completions', input_file_id: 'file-abc123'))
    }.to raise_error(RuntimeError) # skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'error_batch_invalid_file: 400 Bad Request when creating a batch with invalid input file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/error_batch_invalid_file')
    expect {
      client.create_batch_async(LiterLlm::CreateBatchRequest.new(completion_window: '24h', endpoint: '/v1/chat/completions', input_file_id: 'file-wrong-purpose'))
    }.to raise_error(RuntimeError) # skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'error_batch_not_found: 404 Not Found when retrieving a nonexistent batch' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/error_batch_not_found')
    expect {
      client.retrieve_batch_async('batch-nonexistent')
    }.to raise_error(RuntimeError) # skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
  end
  # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend


  it 'smoke_batch_completed: Retrieve a completed batch job with output file' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_batch_completed')
    result = client.retrieve_batch_async('batch-ghi789')
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)
    expect(result.status.to_s).to eq('completed')

  end


  it 'smoke_cancel_batch: Cancel a running batch job' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_cancel_batch')
    result = client.cancel_batch_async('batch-def456')
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)
    expect(result.status.to_s).to eq('cancelling')

  end


  it 'smoke_create_batch: Create a new batch processing job' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_create_batch')
    result = client.create_batch_async(LiterLlm::CreateBatchRequest.new(completion_window: '24h', endpoint: '/v1/chat/completions', input_file_id: 'file-abc123'))
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)
    expect(result.status.to_s).to eq('validating')

  end


  it 'smoke_list_batches: List all batch jobs' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_list_batches')
    result = client.list_batches_async(nil)
    expect(result.data.length).to eq(2)

  end


  it 'smoke_retrieve_batch: Retrieve the status of a batch job' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/smoke_retrieve_batch')
    result = client.retrieve_batch_async('batch-abc123')
    expect(result.id.respond_to?(:empty?) ? !result.id.empty? : !result.id.nil?).to be(true)
    expect(result.status.to_s).to eq('in_progress')

  end

end
