// Generated by alef. Do not edit by hand.
// alef:hash:72db8f901c9ae6e5549dec5b9f30edd34a207ac3de48d7afae4b5994b2faca6d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Text, texts, or multimodal content to embed. */
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = EmbeddingInputDeserializer::class)
@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = EmbeddingInputSerializer::class)
sealed class EmbeddingInput {
    /** Single text string. */
    data class Single(val value: String) : EmbeddingInput()
    /** Multiple text strings (batch embedding). */
    data class Multiple(val value: List<String>) : EmbeddingInput()
    /** Text and image parts for a single multimodal embedding. */
    data class Multimodal(val value: List<EmbeddingContentPart>) : EmbeddingInput()
}

private class EmbeddingInputDeserializer : com.fasterxml.jackson.databind.deser.std.StdDeserializer<EmbeddingInput>(EmbeddingInput::class.java) {
    @Suppress("LongMethod")
    override fun deserialize(
        parser: com.fasterxml.jackson.core.JsonParser,
        ctx: com.fasterxml.jackson.databind.DeserializationContext,
    ): EmbeddingInput {
        val node = parser.codec.readTree<com.fasterxml.jackson.databind.JsonNode>(parser)
        if (node.isTextual) return EmbeddingInput.Single(node.asText())
        if (node.isArray) return run {
                val javaType = ctx.typeFactory.constructCollectionType(List::class.java, String::class.java)
                @Suppress("UNCHECKED_CAST")
                EmbeddingInput.Multiple(ctx.readTreeAsValue<List<String>>(node, javaType) as List<String>)
            }
        if (node.isArray) return run {
                val javaType = ctx.typeFactory.constructCollectionType(List::class.java, EmbeddingContentPart::class.java)
                @Suppress("UNCHECKED_CAST")
                EmbeddingInput.Multimodal(ctx.readTreeAsValue<List<EmbeddingContentPart>>(node, javaType) as List<EmbeddingContentPart>)
            }
        throw com.fasterxml.jackson.databind.exc.InvalidFormatException(
            parser, "Cannot deserialize EmbeddingInput: no matching variant for JSON shape", null, EmbeddingInput::class.java,
        )
    }
}

private class EmbeddingInputSerializer : com.fasterxml.jackson.databind.ser.std.StdSerializer<EmbeddingInput>(EmbeddingInput::class.java) {
    @Suppress("LongMethod")
    override fun serialize(
        value: EmbeddingInput,
        gen: com.fasterxml.jackson.core.JsonGenerator,
        provider: com.fasterxml.jackson.databind.SerializerProvider,
    ) {
        @Suppress("UNCHECKED_CAST")
        val mapper = (gen.codec as? com.fasterxml.jackson.databind.ObjectMapper) ?: com.fasterxml.jackson.databind.ObjectMapper().findAndRegisterModules()
        when (value) {
            is EmbeddingInput.Single -> mapper.writeValue(gen, value.value)
            is EmbeddingInput.Multiple -> mapper.writeValue(gen, value.value)
            is EmbeddingInput.Multimodal -> {
                gen.writeStartArray()
                val elemSerializer = provider.findValueSerializer(EmbeddingContentPart::class.java)
                for (elem in value.value) {
                    elemSerializer.serialize(elem, gen, provider)
                }
                gen.writeEndArray()
            }
        }
    }
}
