// Generated by alef. Do not edit by hand.
// alef:hash:632eb5c15eefa5b48169eb8517b8ff9ea0804c5525eb3ba9decec2c048237c75
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** An OCR response. */
data class OcrResponse(
    /** Extracted pages in order. */
    val pages: List<OcrPage> = emptyList(),
    /** Model/provider used for OCR. */
    val model: String,
    /** Token usage, if reported by the provider. */
    val usage: Usage? = null,
)
