// Generated by alef. Do not edit by hand.
// alef:hash:0d42fa440413e2955d93d00a5558375bf0ed0a6369c435858c6c24404603c2d1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** A search request. */
data class SearchRequest(
    /** The model/provider to use (e.g. `"brave/web-search"`, `"tavily/search"`). */
    val model: String = "",
    /** The search query string. */
    val query: String = "",
    /** Maximum number of results to return. */
    val maxResults: Int? = null,
    /** Domain filter — restrict results to specific domains. */
    val searchDomainFilter: List<String>? = null,
    /** Country code for localized results (ISO 3166-1 alpha-2, e.g., `"US"`, `"FR"`). */
    val country: String? = null,
)
