// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b30c4ddb98b3cf74627226312438c074b2e76d56092ca1a6f76ce7fc02d40749
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: rerank
package e2e_test

import (
	"testing"

	pkg "liter_llm"
)

func Test_EdgeRerankEmptyQuery(t *testing.T) {
	// Reranking with an empty query string
	err := pkg.Rerank(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EdgeRerankSingleDoc(t *testing.T) {
	// Reranking with only a single document
	err := pkg.Rerank(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ErrorRerankAuth401(t *testing.T) {
	// 401 Unauthorized for reranking with invalid API key
	err := pkg.Rerank(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorRerankBadRequest(t *testing.T) {
	// 400 Bad Request for reranking with invalid model
	err := pkg.Rerank(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_SmokeRerankBasic(t *testing.T) {
	// Basic reranking of documents against a query
	err := pkg.Rerank(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SmokeRerankReturnDocs(t *testing.T) {
	// Reranking with return_documents flag to include document text
	err := pkg.Rerank(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SmokeRerankWithTopN(t *testing.T) {
	// Reranking with top_n parameter to limit results
	err := pkg.Rerank(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
