// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1ee4697b19f0fa6b0b6ff3742d280b514ed942e951fb8077758589b618f7d61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: parity

mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_api_surface_parity() {
    // Canonical API surface definition for cross-binding parity verification
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{}"#.to_string(),
        stream_chunks: vec![],
        headers: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let _ = client.chat(&request).await;
}
