// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[path = "mock_server.rs"]
mod mock_server;

use liter_llm::{ClientConfigBuilder, DefaultClient, LlmClient};

/// Reranking with an empty query string
#[tokio::test]
async fn edge_rerank_empty_query() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 200,
            body: r#"{"id":"rerank-empty001","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.5},{"index":1,"relevance_score":0.48}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// Reranking with only a single document
#[tokio::test]
async fn edge_rerank_single_doc() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 200,
            body: r#"{"id":"rerank-single001","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.98}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// 401 Unauthorized for reranking with invalid API key
#[tokio::test]
async fn error_rerank_auth_401() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// 400 Bad Request for reranking with invalid model
#[tokio::test]
async fn error_rerank_bad_request() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":"model_not_found","message":"The model 'nonexistent-rerank' does not exist.","param":"model","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// Basic reranking of documents against a query
#[tokio::test]
async fn smoke_rerank_basic() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 200,
            body: r#"{"id":"rerank-abc123","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.95},{"index":2,"relevance_score":0.82},{"index":1,"relevance_score":0.05}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// Reranking with return_documents flag to include document text
#[tokio::test]
async fn smoke_rerank_return_docs() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 200,
            body: r#"{"id":"rerank-ghi789","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"document":{"text":"Rust is a systems programming language."},"index":0,"relevance_score":0.96},{"document":{"text":"Iron rusts when exposed to water."},"index":1,"relevance_score":0.12}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}

/// Reranking with top_n parameter to limit results
#[tokio::test]
async fn smoke_rerank_with_top_n() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/rerank",
            method: "POST",
            status: 200,
            body: r#"{"id":"rerank-def456","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.97},{"index":2,"relevance_score":0.91}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "rerank"

    server.shutdown();
}
