// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[path = "mock_server.rs"]
mod mock_server;

use liter_llm::{ClientConfigBuilder, DefaultClient, LlmClient};

/// Attempt to cancel an already-cancelled batch
#[tokio::test]
async fn edge_batch_already_cancelled() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches/batch-placeholder",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":null,"message":"Batch batch-cancelled001 is already in terminal state 'cancelled' and cannot be cancelled.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "cancel_batch"

    server.shutdown();
}

/// List batches when no batches exist
#[tokio::test]
async fn edge_batch_empty_list() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/batches",
        method: "GET",
        status: 200,
        body: r#"{"data":[],"has_more":false,"object":"list"}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "list_batches"

    server.shutdown();
}

/// 401 Unauthorized when creating a batch with invalid API key
#[tokio::test]
async fn error_batch_auth_401() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "create_batch"

    server.shutdown();
}

/// 400 Bad Request when creating a batch with invalid input file
#[tokio::test]
async fn error_batch_invalid_file() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":null,"message":"The file 'file-wrong-purpose' has purpose 'fine-tune', but batch requires 'batch'.","param":"input_file_id","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "create_batch"

    server.shutdown();
}

/// 404 Not Found when retrieving a nonexistent batch
#[tokio::test]
async fn error_batch_not_found() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches/batch-placeholder",
            method: "GET",
            status: 404,
            body: r#"{"error":{"code":null,"message":"No such Batch object: batch-nonexistent","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "retrieve_batch"

    server.shutdown();
}

/// Retrieve a completed batch job with output file
#[tokio::test]
async fn smoke_batch_completed() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches/batch-placeholder",
            method: "GET",
            status: 200,
            body: r#"{"completed_at":1711003600,"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-ghi789","in_progress_at":1711000100,"input_file_id":"file-input001","object":"batch","output_file_id":"file-output001","request_counts":{"completed":98,"failed":2,"total":100},"status":"completed"}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "retrieve_batch"

    server.shutdown();
}

/// Cancel a running batch job
#[tokio::test]
async fn smoke_cancel_batch() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches/batch-placeholder",
            method: "POST",
            status: 200,
            body: r#"{"cancelling_at":1711000400,"created_at":1711000200,"endpoint":"/v1/chat/completions","id":"batch-def456","object":"batch","request_counts":{"completed":30,"failed":0,"total":100},"status":"cancelling"}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "cancel_batch"

    server.shutdown();
}

/// Create a new batch processing job
#[tokio::test]
async fn smoke_create_batch() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches",
            method: "POST",
            status: 200,
            body: r#"{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","input_file_id":"file-abc123","object":"batch","request_counts":{"completed":0,"failed":0,"total":0},"status":"validating"}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "create_batch"

    server.shutdown();
}

/// List all batch jobs
#[tokio::test]
async fn smoke_list_batches() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches",
            method: "GET",
            status: 200,
            body: r#"{"data":[{"created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","object":"batch","status":"completed"},{"created_at":1711000200,"endpoint":"/v1/embeddings","id":"batch-def456","object":"batch","status":"in_progress"}],"has_more":false,"object":"list"}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "list_batches"

    server.shutdown();
}

/// Retrieve the status of a batch job
#[tokio::test]
async fn smoke_retrieve_batch() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/batches/batch-placeholder",
            method: "GET",
            status: 200,
            body: r#"{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","in_progress_at":1711000100,"input_file_id":"file-abc123","object":"batch","request_counts":{"completed":45,"failed":2,"total":100},"status":"in_progress"}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "retrieve_batch"

    server.shutdown();
}
