// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[path = "mock_server.rs"]
mod mock_server;

use liter_llm::{ClientConfigBuilder, DefaultClient, LlmClient};

/// Image generation returning base64-encoded data instead of URL
#[tokio::test]
async fn edge_image_b64_response() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 200,
            body: r#"{"created":1711000000,"data":[{"b64_json":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==","revised_prompt":"A perfect blue circle on a white background"}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// Image generation with an empty prompt returns 400
#[tokio::test]
async fn edge_image_empty_prompt() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":null,"message":"You must provide a prompt.","param":"prompt","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// 401 Unauthorized when generating images with invalid API key
#[tokio::test]
async fn error_image_auth_401() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// 400 Bad Request when image generation parameters are invalid
#[tokio::test]
async fn error_image_bad_request() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":null,"message":"Invalid value for 'size': '9999x9999'. Supported values are: '1024x1024', '1792x1024', '1024x1792'.","param":"size","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// 429 Rate limit exceeded for image generation
#[tokio::test]
async fn error_image_rate_limit() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 429,
            body: r#"{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for images per minute. Limit: 5, Used: 5, Requested: 1.","param":null,"type":"rate_limit_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// Basic image generation with a text prompt
#[tokio::test]
async fn smoke_image_basic() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 200,
            body: r#"{"created":1711000000,"data":[{"revised_prompt":"A fluffy white cat sitting peacefully on a sunlit windowsill","url":"https://example.com/images/img-abc123.png"}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// Image generation requesting multiple images
#[tokio::test]
async fn smoke_image_multiple() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 200,
            body: r#"{"created":1711000000,"data":[{"url":"https://example.com/images/img-001.png"},{"url":"https://example.com/images/img-002.png"},{"url":"https://example.com/images/img-003.png"}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}

/// Image generation with explicit size parameter
#[tokio::test]
async fn smoke_image_with_size() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/images/generations",
            method: "POST",
            status: 200,
            body: r#"{"created":1711000000,"data":[{"revised_prompt":"A breathtaking sunset over snow-capped mountains","url":"https://example.com/images/img-def456.png"}]}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // TODO: unknown method "image_generate"

    server.shutdown();
}
