<?php

declare(strict_types=1);

// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

namespace LiterLlmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class BatchesTest extends TestCase
{
    /** Attempt to cancel an already-cancelled batch */
    public function testEdgeBatchAlreadyCancelled(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches/batch-placeholder',
                method: 'POST',
                status: 400,
                body: '{"error":{"code":null,"message":"Batch batch-cancelled001 is already in terminal state \'cancelled\' and cannot be cancelled.","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches/batch-placeholder', 'POST', '{"batch_id":"batch-cancelled001"}');
        $server->stop();

        $this->assertEquals(400, $result['status']);
    }

    /** List batches when no batches exist */
    public function testEdgeBatchEmptyList(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches',
                method: 'GET',
                status: 200,
                body: '{"data":[],"has_more":false,"object":"list"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** 401 Unauthorized when creating a batch with invalid API key */
    public function testErrorBatchAuth401(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches',
                method: 'POST',
                status: 401,
                body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches', 'POST', '{"completion_window":"24h","endpoint":"/v1/chat/completions","input_file_id":"file-abc123"}');
        $server->stop();

        $this->assertEquals(401, $result['status']);
    }

    /** 400 Bad Request when creating a batch with invalid input file */
    public function testErrorBatchInvalidFile(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches',
                method: 'POST',
                status: 400,
                body: '{"error":{"code":null,"message":"The file \'file-wrong-purpose\' has purpose \'fine-tune\', but batch requires \'batch\'.","param":"input_file_id","type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches', 'POST', '{"completion_window":"24h","endpoint":"/v1/chat/completions","input_file_id":"file-wrong-purpose"}');
        $server->stop();

        $this->assertEquals(400, $result['status']);
    }

    /** 404 Not Found when retrieving a nonexistent batch */
    public function testErrorBatchNotFound(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches/batch-placeholder',
                method: 'GET',
                status: 404,
                body: '{"error":{"code":null,"message":"No such Batch object: batch-nonexistent","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches/batch-placeholder', 'GET');
        $server->stop();

        $this->assertEquals(404, $result['status']);
    }

    /** Retrieve a completed batch job with output file */
    public function testSmokeBatchCompleted(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches/batch-placeholder',
                method: 'GET',
                status: 200,
                body: '{"completed_at":1711003600,"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-ghi789","in_progress_at":1711000100,"input_file_id":"file-input001","object":"batch","output_file_id":"file-output001","request_counts":{"completed":98,"failed":2,"total":100},"status":"completed"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches/batch-placeholder', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** Cancel a running batch job */
    public function testSmokeCancelBatch(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches/batch-placeholder',
                method: 'POST',
                status: 200,
                body: '{"cancelling_at":1711000400,"created_at":1711000200,"endpoint":"/v1/chat/completions","id":"batch-def456","object":"batch","request_counts":{"completed":30,"failed":0,"total":100},"status":"cancelling"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches/batch-placeholder', 'POST', '{"batch_id":"batch-def456"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** Create a new batch processing job */
    public function testSmokeCreateBatch(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches',
                method: 'POST',
                status: 200,
                body: '{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","input_file_id":"file-abc123","object":"batch","request_counts":{"completed":0,"failed":0,"total":0},"status":"validating"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches', 'POST', '{"completion_window":"24h","endpoint":"/v1/chat/completions","input_file_id":"file-abc123"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** List all batch jobs */
    public function testSmokeListBatches(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches',
                method: 'GET',
                status: 200,
                body: '{"data":[{"created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","object":"batch","status":"completed"},{"created_at":1711000200,"endpoint":"/v1/embeddings","id":"batch-def456","object":"batch","status":"in_progress"}],"has_more":false,"object":"list"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** Retrieve the status of a batch job */
    public function testSmokeRetrieveBatch(): void
    {
        $routes = [
            new MockRoute(
                path: '/batches/batch-placeholder',
                method: 'GET',
                status: 200,
                body: '{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","in_progress_at":1711000100,"input_file_id":"file-abc123","object":"batch","request_counts":{"completed":45,"failed":2,"total":100},"status":"in_progress"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/batches/batch-placeholder', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }
}
