<?php

declare(strict_types=1);

// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

namespace LiterLlmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class CacheTest extends TestCase
{
    /** Tests that identical chat requests return cached response */
    public function testCacheHit(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-cache-hit-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $mockUrl = $server->url;

        $cacheConfig = new \LiterLlm\CacheConfig(maxEntries: 10, ttlSeconds: 60);
        $client = new \LiterLlm\LlmClient('test-key', $mockUrl, cacheConfig: $cacheConfig);

        $resp1 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $resp2 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $this->assertEquals($resp1, $resp2, 'Expected cache hit on second call');
        $server->stop();
    }

    /** Tests that cache expires after TTL */
    public function testCacheMissTtl(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-cache-miss-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $mockUrl = $server->url;

        $cacheConfig = new \LiterLlm\CacheConfig(maxEntries: 10, ttlSeconds: 60);
        $client = new \LiterLlm\LlmClient('test-key', $mockUrl, cacheConfig: $cacheConfig);

        $resp1 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $resp2 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $this->assertNotNull($resp1);
        $this->assertNotNull($resp2);
        $server->stop();
    }

    /** Cache hit with OpenDAL memory backend returns cached response on repeat request */
    public function testCacheOpendalMemory(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-opendal-mem-001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":2,"prompt_tokens":5,"total_tokens":7}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $mockUrl = $server->url;

        $cacheConfig = new \LiterLlm\CacheConfig(maxEntries: 10, ttlSeconds: 60);
        $client = new \LiterLlm\LlmClient('test-key', $mockUrl, cacheConfig: $cacheConfig);

        $resp1 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $resp2 = $client->chat('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $this->assertEquals($resp1, $resp2, 'Expected cache hit on second call');
        $server->stop();
    }

    /** Tests that streaming requests bypass cache entirely */
    public function testCacheStreamBypass(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-stream-bypass-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $mockUrl = $server->url;

        $cacheConfig = new \LiterLlm\CacheConfig(maxEntries: 10, ttlSeconds: 60);
        $client = new \LiterLlm\LlmClient('test-key', $mockUrl, cacheConfig: $cacheConfig);

        $chunks = $client->chatStream('{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $this->assertNotEmpty($chunks, 'Expected stream chunks');
        $server->stop();
    }
}
