<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;

/** E2e tests for category: parity. */
final class ParityTest extends TestCase
{
    /** Canonical API surface definition for cross-binding parity verification */
    public function test_api_surface_parity(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key');
        $this->expectNotToPerformAssertions();
        $result = $client->chat_async(null);
    }
}
