// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd5c5c57403a03713acb559d8f98e84499f55f7a8a304ba76b40a87f7a8340f1
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: tool-calling.
final class ToolCallingTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testAnthropicToolCalling() async throws {
        // Chat request to Anthropic provider with a tool definition; assistant responds with a tool call
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"max_tokens\":256,\"messages\":[{\"content\":\"What is the weather in London?\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and country, e.g. London, UK\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/anthropic_tool_calling")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19 = result.choices()
        // skipped: field 'choices[0].message.tool_calls' has no countable Swift leaf (swift-bridge JSON-bridges it to RustString)
        // skipped: field 'choices.message.tool_calls' has no countable Swift leaf (swift-bridge JSON-bridges it to RustString)
        let _vec_choices_equals_1c1cc717 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

    func testSingleToolCall() async throws {
        // Chat request with a tool definition; assistant responds with a tool call
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"What is the weather in San Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and state, e.g. San Francisco, CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/single_tool_call")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_not_empty_c4dcde19 = result.choices()
        // skipped: field 'choices[0].message.tool_calls' has no countable Swift leaf (swift-bridge JSON-bridges it to RustString)
        // skipped: field 'choices.message.tool_calls' has no countable Swift leaf (swift-bridge JSON-bridges it to RustString)
        let _vec_choices_equals_1c1cc717 = result.choices()
        XCTAssertEqual((_vec_choices_equals_1c1cc717[0].finishReason()?.toString() ?? ""), "tool_calls")
    }

}
