// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d201996d55d843cff1d287a7b98274d7780fa2e9f8fe34e616eff0c33534b879
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/liter_llm.h");
}
