// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e89a365e8f9a114ea71c751561ee1a12f454aacda2ba0d1d57a6717c80be25aa
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/liter_llm.h");
}
