# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fb5dc2aa5697be7a8789369581afc95e63c62a331a9c171fc715a7cd4bb814e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Liter_llm
  VERSION = "1.4.0.pre.rc.16"
end
