# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa6f295cf0c8f8e5ae077a9e05307eaef4ac9169f0f5c65e68ed55dac180ab94
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Liter_llm
  VERSION = '1.4.0.pre.rc.9'
end
