// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literllm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: batches. */
class BatchesTest {

  /** Attempt to cancel an already-cancelled batch */
  @Test
  void edgeBatchAlreadyCancelled() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches/batch-placeholder",
                    "POST",
                    400,
                    "{\"error\":{\"code\":null,\"message\":\"Batch batch-cancelled001 is already in"
                        + " terminal state 'cancelled' and cannot be"
                        + " cancelled.\",\"param\":null,\"type\":\"invalid_request_error\"}}")))) {

      // TODO: unknown method "cancel_batch"
    }
  }

  /** List batches when no batches exist */
  @Test
  void edgeBatchEmptyList() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches",
                    "GET",
                    200,
                    "{\"data\":[],\"has_more\":false,\"object\":\"list\"}")))) {

      // TODO: unknown method "list_batches"
    }
  }

  /** 401 Unauthorized when creating a batch with invalid API key */
  @Test
  void errorBatchAuth401() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches",
                    "POST",
                    401,
                    "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key"
                        + " provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}")))) {

      // TODO: unknown method "create_batch"
    }
  }

  /** 400 Bad Request when creating a batch with invalid input file */
  @Test
  void errorBatchInvalidFile() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches",
                    "POST",
                    400,
                    "{\"error\":{\"code\":null,\"message\":\"The file 'file-wrong-purpose' has"
                        + " purpose 'fine-tune', but batch requires"
                        + " 'batch'.\",\"param\":\"input_file_id\",\"type\":\"invalid_request_error\"}}")))) {

      // TODO: unknown method "create_batch"
    }
  }

  /** 404 Not Found when retrieving a nonexistent batch */
  @Test
  void errorBatchNotFound() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches/batch-placeholder",
                    "GET",
                    404,
                    "{\"error\":{\"code\":null,\"message\":\"No such Batch object:"
                        + " batch-nonexistent\",\"param\":null,\"type\":\"invalid_request_error\"}}")))) {

      // TODO: unknown method "retrieve_batch"
    }
  }

  /** Retrieve a completed batch job with output file */
  @Test
  void smokeBatchCompleted() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches/batch-placeholder",
                    "GET",
                    200,
                    "{\"completed_at\":1711003600,\"completion_window\":\"24h\",\"created_at\":1711000000,\"endpoint\":\"/v1/chat/completions\",\"id\":\"batch-ghi789\",\"in_progress_at\":1711000100,\"input_file_id\":\"file-input001\",\"object\":\"batch\",\"output_file_id\":\"file-output001\",\"request_counts\":{\"completed\":98,\"failed\":2,\"total\":100},\"status\":\"completed\"}")))) {

      // TODO: unknown method "retrieve_batch"
    }
  }

  /** Cancel a running batch job */
  @Test
  void smokeCancelBatch() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches/batch-placeholder",
                    "POST",
                    200,
                    "{\"cancelling_at\":1711000400,\"created_at\":1711000200,\"endpoint\":\"/v1/chat/completions\",\"id\":\"batch-def456\",\"object\":\"batch\",\"request_counts\":{\"completed\":30,\"failed\":0,\"total\":100},\"status\":\"cancelling\"}")))) {

      // TODO: unknown method "cancel_batch"
    }
  }

  /** Create a new batch processing job */
  @Test
  void smokeCreateBatch() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches",
                    "POST",
                    200,
                    "{\"completion_window\":\"24h\",\"created_at\":1711000000,\"endpoint\":\"/v1/chat/completions\",\"id\":\"batch-abc123\",\"input_file_id\":\"file-abc123\",\"object\":\"batch\",\"request_counts\":{\"completed\":0,\"failed\":0,\"total\":0},\"status\":\"validating\"}")))) {

      // TODO: unknown method "create_batch"
    }
  }

  /** List all batch jobs */
  @Test
  void smokeListBatches() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches",
                    "GET",
                    200,
                    "{\"data\":[{\"created_at\":1711000000,\"endpoint\":\"/v1/chat/completions\",\"id\":\"batch-abc123\",\"object\":\"batch\",\"status\":\"completed\"},{\"created_at\":1711000200,\"endpoint\":\"/v1/embeddings\",\"id\":\"batch-def456\",\"object\":\"batch\",\"status\":\"in_progress\"}],\"has_more\":false,\"object\":\"list\"}")))) {

      // TODO: unknown method "list_batches"
    }
  }

  /** Retrieve the status of a batch job */
  @Test
  void smokeRetrieveBatch() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/batches/batch-placeholder",
                    "GET",
                    200,
                    "{\"completion_window\":\"24h\",\"created_at\":1711000000,\"endpoint\":\"/v1/chat/completions\",\"id\":\"batch-abc123\",\"in_progress_at\":1711000100,\"input_file_id\":\"file-abc123\",\"object\":\"batch\",\"request_counts\":{\"completed\":45,\"failed\":2,\"total\":100},\"status\":\"in_progress\"}")))) {

      // TODO: unknown method "retrieve_batch"
    }
  }
}
