// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ecbf560905ab89be658f60afd80e6b38475aade2457b929cc1b0c074022f383d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** E2e tests for category: configuration. */
class ConfigurationTest {
    @Test
    void testCustomBaseUrl() throws Exception {
        // Client configured with a custom base URL routes all requests to that endpoint
        var result = LiterLlm.chat(null);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertEquals("Hi there!", result.choices().get("0").message().content().trim());
        assertEquals("stop", result.choices().get("0").finishReason().trim());
        assertEquals("local-model", result.model().trim());
    }

    @Test
    void testExtraHeaders() throws Exception {
        // Client configured with extra custom headers successfully completes a chat request
        var result = LiterLlm.chat(null);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertEquals("stop", result.choices().get("0").finishReason().trim());
    }

    @Test
    void testLocalProviderLlamacpp() throws Exception {
        // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
        var result = LiterLlm.chat(null);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertEquals("Hi there! I'm running locally.", result.choices().get("0").message().content().trim());
        assertEquals("stop", result.choices().get("0").finishReason().trim());
        assertEquals("my-model", result.model().trim());
    }

    @Test
    void testLocalProviderOllama() throws Exception {
        // Ollama local provider routes requests via ollama/ model prefix with no auth
        var result = LiterLlm.chat(null);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertEquals("Hello! How can I help you today?", result.choices().get("0").message().content().trim());
        assertEquals("stop", result.choices().get("0").finishReason().trim());
        assertEquals("qwen2:0.5b", result.model().trim());
    }

    @Test
    void testLocalProviderVllm() throws Exception {
        // vLLM local provider routes requests via vllm/ model prefix with no auth
        var result = LiterLlm.chat(null);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertEquals("Hello! How may I assist you?", result.choices().get("0").message().content().trim());
        assertEquals("stop", result.choices().get("0").finishReason().trim());
        assertEquals("meta-llama/Llama-3.2-1B", result.model().trim());
    }

}
