# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: types

test_that("all_message_types: Request with all message role types (system, user, assistant, tool) to verify round-trip serialization", {
  result <- chat()
  expect_equal(length(result$choices), 1)
  expect_equal(trimws(result$choices[["0"]]$finish_reason), "stop")
})

test_that("multimodal_content: User message with mixed text and image_url content parts to verify multimodal serialization", {
  result <- chat()
  expect_equal(length(result$choices), 1)
  expect_equal(trimws(result$choices[["0"]]$finish_reason), "stop")
})
