// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import LiterLlm

/// E2e tests for category: cache.
final class CacheTests: XCTestCase {
    func testCacheHit() async throws {
        // Tests that identical chat requests return cached response
        let result = try await chat(nil)
        XCTAssertTrue(result.cache_hit)
    }

    func testCacheMissTtl() async throws {
        // Tests that cache expires after TTL
        let result = try await chat(nil)
        XCTAssertTrue(result.cache_hit)
    }

    func testCacheOpendalMemory() async throws {
        // Cache hit with OpenDAL memory backend returns cached response on repeat request
        let result = try await chat(nil)
        XCTAssertTrue(result.cache_hit)
    }

    func testCacheStreamBypass() async throws {
        // Tests that streaming requests bypass cache entirely
        let result = try await chatStream(nil)
        XCTAssertTrue(result.cache_bypassed)
    }

}
