// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:83a886dfc0e3d814dfd1e6ffdf0a0471527c71715e8c6843de70e13f62f888a7
#nullable enable

using System;

namespace LiterLlm;

public class AuthenticationException : LiterLlmErrorException
{
    public AuthenticationException(string message) : base(message) { }

    public AuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}
