// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:97a44d0b318d29c6d109fb247cb5b3343f35f3b1324c21ecb8d7123b4f038339
#nullable enable

using System;

namespace LiterLlm;

public class BadRequestException : LiterLlmErrorException
{
    public BadRequestException(string message) : base(message) { }

    public BadRequestException(string message, Exception innerException) : base(message, innerException) { }
}
