// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:22224df981dd9f26a4f020fa605017e1c44647ba9eca9929e431d9d27de837c2
#nullable enable

using System;

namespace LiterLlm;

public class BadRequestException : LiterLlmErrorException
{
    public BadRequestException(string message) : base(message) { }

    public BadRequestException(string message, Exception innerException) : base(message, innerException) { }
}
