// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class BatchListQuery
{
    [JsonPropertyName("limit")]
    public uint? Limit { get; set; } = null;

    [JsonPropertyName("after")]
    public string? After { get; set; } = null;

}
