// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Configuration for the response cache.
/// </summary>
public sealed class CacheConfig
{
    /// <summary>
    /// Maximum number of cached entries.
    /// </summary>
    [JsonPropertyName("maxEntries")]
    public required nuint MaxEntries { get; set; }

    /// <summary>
    /// Time-to-live for each cached entry.
    /// </summary>
    [JsonPropertyName("ttl")]
    public required ulong Ttl { get; set; }

    /// <summary>
    /// Storage backend to use.
    /// </summary>
    [JsonPropertyName("backend")]
    public required string Backend { get; set; }

}
