// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:07275cc911650f10a91667dc81c9830f7b1edee7b2e8676a5033f1e8aece0d44
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ChatCompletionTool
{
    [JsonPropertyName("tool_type")]
    public ToolType ToolType { get; set; } = default!;

    [JsonPropertyName("function")]
    public FunctionDefinition Function { get; set; } = default!;

}
