// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2d137e79f83c667e36e42106c34df2d3913931b7076f5ab2eb937487813b02d5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class Choice
{
    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

    [JsonPropertyName("message")]
    public AssistantMessage Message { get; set; } = default!;

    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; set; } = null;

}
