// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a5220147589f69ffc10659a5bfdd22f55638fdf5ae6bd2eae2c28961de299a9d
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
