// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ad903365962f3fcbd409a6653062e552d8204b6d709d0442ee919a70172c8a69
#nullable enable

using System;

namespace LiterLlm;

public class ContextWindowExceededException : LiterLlmErrorException
{
    public ContextWindowExceededException(string message) : base(message) { }

    public ContextWindowExceededException(string message, Exception innerException) : base(message, innerException) { }
}
