// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c05d46f803485d40d92aaa5fcd181d82809010a62842b362177bedf412571e8e
#nullable enable

using System;

namespace LiterLlm;

public class ContextWindowExceededException : LiterLlmErrorException
{
    public ContextWindowExceededException(string message) : base(message) { }

    public ContextWindowExceededException(string message, Exception innerException) : base(message, innerException) { }
}
