// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to transcribe audio into text.
/// </summary>
public sealed class CreateTranscriptionRequest
{
    [JsonPropertyName("model")]
    public required string Model { get; set; }

    /// <summary>
    /// Base64-encoded audio file data.
    /// </summary>
    [JsonPropertyName("file")]
    public required string File { get; set; }

    [JsonPropertyName("language")]
    public string? Language { get; set; } = null;

    [JsonPropertyName("prompt")]
    public string? Prompt { get; set; } = null;

    [JsonPropertyName("responseFormat")]
    public string? ResponseFormat { get; set; } = null;

    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; } = null;

}
