// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e6483ca21c19ed16d5f88d9f70ae412437a680f6a493fb22de79c721ebfc059
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Configuration for registering a custom LLM provider at runtime.
/// </summary>
public sealed class CustomProviderConfig
{
    /// <summary>
    /// Unique name for this provider (e.g., "my-provider").
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    /// <summary>
    /// Base URL for the provider's API (e.g., "https://api.my-provider.com/v1").
    /// </summary>
    [JsonPropertyName("base_url")]
    public string BaseUrl { get; set; } = "";

    /// <summary>
    /// Authentication header format.
    /// </summary>
    [JsonPropertyName("auth_header")]
    public JsonElement AuthHeader { get; set; } = default!;

    /// <summary>
    /// Model name prefixes that route to this provider (e.g., ["my-"]).
    /// </summary>
    [JsonPropertyName("model_prefixes")]
    public List<string> ModelPrefixes { get; set; } = [];

}
