// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54b350948ffdfabace2d58455e5f1424b80751f7bd4cf2cbfd663ad3f2bd84ad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// Default client implementation backed by `reqwest`.
///
/// The provider is resolved at construction time from `model_hint` (or
/// defaults to OpenAI). However, individual requests can override the
/// provider when their model string contains a prefix that clearly
/// identifies a different provider (e.g. `"anthropic/claude-3"` will
/// route to Anthropic even if the client was built without a hint).
///
/// When the model prefix does not match any known provider, the
/// construction-time provider is used as the fallback.
///
/// The provider is stored behind an [`Arc`] so it can be shared cheaply into
/// async closures and streaming tasks that must be `'static`.
/// </summary>
public sealed class DefaultClient : IDisposable
{
    internal IntPtr Handle { get; }

    internal DefaultClient(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
