// This file is auto-generated by skif. DO NOT EDIT.

namespace LiterLlm;

/// <summary>
/// The format in which the embedding vectors are returned.
/// </summary>
public enum EmbeddingFormat
{
    /// <summary>
    /// 32-bit floating-point numbers (default).
    /// </summary>
    Float,
    /// <summary>
    /// Base64-encoded string representation of the floats.
    /// </summary>
    Base64,
}
