// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0e4f8d6e35432fcc7f7ef702ed84e18d172a2198fe38f4315e0ba2e8cefa526
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum EmbeddingInput
{
    [JsonPropertyName("single")]
    Single,
    [JsonPropertyName("multiple")]
    Multiple,
}
