// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class FileCacheConfig
{
    [JsonPropertyName("maxEntries")]
    public nuint? MaxEntries { get; set; } = null;

    [JsonPropertyName("ttlSeconds")]
    public ulong? TtlSeconds { get; set; } = null;

    [JsonPropertyName("backend")]
    public string? Backend { get; set; } = null;

    [JsonPropertyName("backendConfig")]
    public Dictionary<string, string>? BackendConfig { get; set; } = null;

}
