// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c28cbfbb0cf6fd67f46ac5f73bf873e7e9e0c5e3054ad9049fa9f8bae8923c2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class FileListQuery
{
    [JsonPropertyName("purpose")]
    public string? Purpose { get; set; } = null;

    [JsonPropertyName("limit")]
    public uint? Limit { get; set; } = null;

    [JsonPropertyName("after")]
    public string? After { get; set; } = null;

}
