// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b7f92445ff5885e00bd4bc90bcb4a1da4bed79bfe5bbf7bd9bf2f5b2614a4ac8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Deprecated legacy function-role message body.
/// </summary>
public sealed class FunctionMessage
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

}
