// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b989e1422a5aae5c2d6988eac0115668ef3825084ac5d8ab73bdf52788894c39
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response containing generated images.
/// </summary>
public sealed class ImagesResponse
{
    [JsonPropertyName("created")]
    public ulong Created { get; set; } = 0;

    [JsonPropertyName("data")]
    public List<Image> Data { get; set; } = [];

}
