// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c7f79337dc33ea6c1198c999c98d689092f3fb7235d3404138eacb5ef3ca7ee1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum ImageDetail
{
    [JsonPropertyName("low")]
    Low,
    [JsonPropertyName("high")]
    High,
    [JsonPropertyName("auto")]
    Auto,
}
