// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ed97b492357fc5757f31aea54f57e041ea460d3756ae379ea003d9c88970a331
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum ImageDetail
{
    [JsonPropertyName("low")]
    Low,
    [JsonPropertyName("high")]
    High,
    [JsonPropertyName("auto")]
    Auto,
}
