// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An internal logic error (e.g. unexpected Tower response variant).
///
/// This should never surface in normal operation — if it does, it
/// indicates a bug in the library.
/// </summary>
public class InternalErrorException : LiterLlmErrorException
{
    public InternalErrorException(string message) : base(message) { }

    public InternalErrorException(string message, Exception innerException) : base(message, innerException) { }
}
