// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class JsonSchemaFormat
{
    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    [JsonPropertyName("schema")]
    public required string Schema { get; set; }

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; } = null;

}
