// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b79e66c1bf756cb1ce87eab3c4524a88048a509be2fca6d4f9cba0d535da374
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class JsonSchemaFormat
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    [JsonPropertyName("schema")]
    public object? Schema { get; set; } = null;

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; } = null;

}
