// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// All errors that can occur when using `liter-llm`.
/// </summary>
public class LiterLlmErrorException : Exception
{
    public LiterLlmErrorException(string message) : base(message) { }

    public LiterLlmErrorException(string message, Exception innerException) : base(message, innerException) { }
}
