// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8219f7343589f184f67c493f9cf8b132dcce674e75e000457cb5e826357b30e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to classify content for policy violations.
/// </summary>
public sealed class ModerationRequest
{
    [JsonPropertyName("input")]
    public JsonElement Input { get; set; } = default!;

    [JsonPropertyName("model")]
    public string? Model { get; set; } = null;

}
