// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:47717e1b146206e4166d5582f79f1f03e5deaff6a7808bf71be485957efdb2bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to classify content for policy violations.
/// </summary>
public sealed class ModerationRequest
{
    [JsonPropertyName("input")]
    public JsonElement Input { get; set; } = default!;

    [JsonPropertyName("model")]
    public string? Model { get; set; } = null;

}
