// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to classify content for policy violations.
/// </summary>
public sealed class ModerationRequest
{
    [JsonPropertyName("input")]
    public JsonElement Input { get; set; } = default!;

    [JsonPropertyName("model")]
    public string? Model { get; set; } = null;

}
