// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0e951f43fc12b518d2b215e358dc4c6ed69993910e3ab13342602b37e09e37b5
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
