// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b266831d347d4729d7f7328fe7693926662f5307793e4d9abaea89f477b4e7c4
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
