// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// An OCR response.
/// </summary>
public sealed class OcrResponse
{
    /// <summary>
    /// Extracted pages.
    /// </summary>
    [JsonPropertyName("pages")]
    public required List<OcrPage> Pages { get; set; }

    /// <summary>
    /// The model used.
    /// </summary>
    [JsonPropertyName("model")]
    public required string Model { get; set; }

    /// <summary>
    /// Token usage, if reported by the provider.
    /// </summary>
    [JsonPropertyName("usage")]
    public Usage? Usage { get; set; } = null;

}
