// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23525e88de072f4ff8d577d648c0b5f34f477c1229540765680ec754f215149c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Page dimensions in pixels.
/// </summary>
public sealed class PageDimensions
{
    /// <summary>
    /// Width in pixels.
    /// </summary>
    [JsonPropertyName("width")]
    public uint Width { get; set; } = 0;

    /// <summary>
    /// Height in pixels.
    /// </summary>
    [JsonPropertyName("height")]
    public uint Height { get; set; } = 0;

}
