// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Page dimensions in pixels.
/// </summary>
public sealed class PageDimensions
{
    /// <summary>
    /// Width in pixels.
    /// </summary>
    [JsonPropertyName("width")]
    public uint Width { get; set; } = 0;

    /// <summary>
    /// Height in pixels.
    /// </summary>
    [JsonPropertyName("height")]
    public uint Height { get; set; } = 0;

}
