// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fd12981f9b8cc6a396671b527a5586b59c5404233a31100ceabdc2b8ae8f9b3e
#nullable enable

using System;

namespace LiterLlm;

public class RateLimitedException : LiterLlmErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
