// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to rerank documents by relevance to a query.
/// </summary>
public sealed class RerankRequest
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    [JsonPropertyName("query")]
    public string Query { get; set; } = "";

    [JsonPropertyName("documents")]
    public List<RerankDocument> Documents { get; set; } = [];

    [JsonPropertyName("top_n")]
    public uint? TopN { get; set; } = null;

    [JsonPropertyName("return_documents")]
    public bool? ReturnDocuments { get; set; } = null;

}
