// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40b837605f1ddf427239cf9feb8ffb19a57c93673812c5d82372a93a15593a15
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// The text content of a reranked document, returned when `return_documents` is true.
/// </summary>
public sealed class RerankResultDocument
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
