// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

/// <summary>
/// A document to be reranked — either a plain string or an object with a text field.
/// </summary>
public enum RerankDocument
{
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("object")]
    Object,
}
