// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37f3b851d2c62140c51e5f40b6784794ccaa478f889819f97a26de4153bba63d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// The text content of a reranked document, returned when `return_documents` is true.
/// </summary>
public sealed class RerankResultDocument
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
