// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b946e8d3483c2a989cc2f0180c59c3624d7a08de0aa15e252ca79873fe7ff0c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// The text content of a reranked document, returned when `return_documents` is true.
/// </summary>
public sealed class RerankResultDocument
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
