// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:258c27685a71142b3e866b1741340d7100eb85162a5e4c65f51eb3b92f741717
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ResponseTool
{
    [JsonPropertyName("tool_type")]
    public string ToolType { get; set; } = "";

    [JsonPropertyName("config")]
    public object? Config { get; set; } = null;

}
