// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0c7e2fedb35dd3404be9f6fe37b3a3dc3759b3bebfbd41ef67b0c3509543259
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// A search response.
/// </summary>
public sealed class SearchResponse
{
    /// <summary>
    /// The search results.
    /// </summary>
    [JsonPropertyName("results")]
    public List<SearchResult> Results { get; set; } = [];

    /// <summary>
    /// The model used.
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

}
