// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8c8a83bdeb91b98077aa41b01c2359c58e70b48836122bdda48599b9ad3b3a48
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (502, 503, or 504).
/// </summary>
public class ServiceUnavailableException : LiterLlmErrorException
{
    public ServiceUnavailableException(string message) : base(message) { }

    public ServiceUnavailableException(string message, Exception innerException) : base(message, innerException) { }
}
