// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5813a7c0a7e4c459f0d858fb0b81caa90313828df98eb0270f8b5876077b23df
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace LiterLlm;

// The native handle is the scalar `AlefHandle` (`uint64_t`) registry index, not a pointer.
// `SafeHandle`'s only storage slot is a pointer-width `IntPtr`, so the `ulong` is packed into
// that slot as a raw bit pattern (never dereferenced) to keep `SafeHandle`'s guaranteed
// finalization and `DangerousAddRef`/`DangerousRelease` ref-counting, which the borrow/lease/
// transfer machinery below builds on. This is lossless on every currently supported .NET
// target (IntPtr is 8 bytes on all 64-bit platforms .NET 5+ ships on); on a true 32-bit
// process a handle value above `uint.MaxValue` would truncate, but that requires over four
// billion concurrently live handles of this type, and 32-bit .NET targets are legacy-only.
internal sealed class SingleflightResultSafeHandle : SafeHandle
{
    internal SingleflightResultSafeHandle(ulong handle) : base(IntPtr.Zero, true)
    {
        SetHandle(Pack(handle));
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    internal static IntPtr Pack(ulong value) => unchecked((IntPtr)(long)value);

    internal static ulong Unpack(IntPtr value) => unchecked((ulong)(long)value);

    protected override bool ReleaseHandle()
    {
        NativeMethods.SingleflightResultFree(Unpack(handle));
        return true;
    }
}
/// <summary>/// The value broadcast from a singleflight leader to all followers./// /// The error value is shared so every follower receives the same upstream/// failure without cloning the underlying error./// </summary>
public sealed class SingleflightResult : IDisposable
{
    private SingleflightResultSafeHandle _safeHandle;
    private readonly object _handleLock = new();
    private int _activeBorrows;
    private bool _handleUnavailable;
    private bool _transferPending;

    internal sealed class HandleLease : IDisposable
    {
        private SingleflightResult? _owner;

        internal HandleLease(SingleflightResult owner, ulong handle)
        {
            _owner = owner;
            Handle = handle;
        }

        internal ulong Handle { get; }

        public void Dispose()
        {
            var owner = global::System.Threading.Interlocked.Exchange(ref _owner, null);
            owner?.ReleaseBorrow();
        }
    }

    private sealed class HandleTransfer : IDisposable
    {
        private SingleflightResult? _owner;
        private SingleflightResultSafeHandle? _transferredHandle;

        internal HandleTransfer(SingleflightResult owner, ulong handle)
        {
            _owner = owner;
            _transferredHandle = new SingleflightResultSafeHandle(handle);
        }

        internal ulong Handle => _transferredHandle is { } transferredHandle
            ? SingleflightResultSafeHandle.Unpack(transferredHandle.DangerousGetHandle())
            : throw new InvalidOperationException("Handle transfer is no longer active");

        internal void Commit()
        {
            var transferredHandle = _transferredHandle
                ?? throw new InvalidOperationException("Handle transfer is no longer active");
            transferredHandle.SetHandleAsInvalid();
            _transferredHandle = null;
            var owner = _owner;
            _owner = null;
            owner?.CommitTransfer();
        }

        public void Dispose()
        {
            var transferredHandle = global::System.Threading.Interlocked.Exchange(ref _transferredHandle, null);
            var owner = global::System.Threading.Interlocked.Exchange(ref _owner, null);
            if (transferredHandle is null) return;
            if (owner is null)
            {
                transferredHandle.Dispose();
                return;
            }
            var handle = SingleflightResultSafeHandle.Unpack(transferredHandle.DangerousGetHandle());
            transferredHandle.SetHandleAsInvalid();
            owner.RollbackTransfer(handle);
        }
    }

    internal SingleflightResult(ulong handle)
    {
        _safeHandle = new SingleflightResultSafeHandle(handle);
    }

    internal ulong Handle => GetHandle();

    private ulong GetHandle()
    {
        lock (_handleLock)
        {
            ThrowIfHandleUnavailable();
            return SingleflightResultSafeHandle.Unpack(_safeHandle.DangerousGetHandle());
        }
    }

    internal HandleLease BorrowHandle()
    {
        lock (_handleLock)
        {
            ThrowIfHandleUnavailable();
            var lease = new HandleLease(this, SingleflightResultSafeHandle.Unpack(_safeHandle.DangerousGetHandle()));
            var addRefSucceeded = false;
            _safeHandle.DangerousAddRef(ref addRefSucceeded);
            if (!addRefSucceeded) throw new ObjectDisposedException(nameof(SingleflightResult));
            _activeBorrows++;
            return lease;
        }
    }

    private void ReleaseBorrow()
    {
        lock (_handleLock)
        {
            _safeHandle.DangerousRelease();
            _activeBorrows--;
            if (_activeBorrows == 0) global::System.Threading.Monitor.PulseAll(_handleLock);
        }
    }

    private HandleTransfer TakeHandle()
    {
        lock (_handleLock)
        {
            ThrowIfHandleUnavailable();
            WaitForBorrowedCalls();
            var transfer = new HandleTransfer(this, SingleflightResultSafeHandle.Unpack(_safeHandle.DangerousGetHandle()));
            _handleUnavailable = true;
            _safeHandle.SetHandleAsInvalid();
            _transferPending = true;
            return transfer;
        }
    }

    private void RollbackTransfer(ulong handle)
    {
        lock (_handleLock)
        {
            _transferPending = false;
            _safeHandle = new SingleflightResultSafeHandle(handle);
            _handleUnavailable = false;
            global::System.Threading.Monitor.PulseAll(_handleLock);
        }
    }

    private void CommitTransfer()
    {
        lock (_handleLock)
        {
            _transferPending = false;
            global::System.Threading.Monitor.PulseAll(_handleLock);
        }
    }

    private void WaitForBorrowedCalls()
    {
        var interrupted = false;
        while (_activeBorrows != 0)
        {
            try
            {
                global::System.Threading.Monitor.Wait(_handleLock);
            }
            catch (global::System.Threading.ThreadInterruptedException)
            {
                interrupted = true;
            }
        }
        if (interrupted) global::System.Threading.Thread.CurrentThread.Interrupt();
    }

    private void WaitForPendingTransfer()
    {
        var interrupted = false;
        while (_transferPending)
        {
            try
            {
                global::System.Threading.Monitor.Wait(_handleLock);
            }
            catch (global::System.Threading.ThreadInterruptedException)
            {
                interrupted = true;
            }
        }
        if (interrupted) global::System.Threading.Thread.CurrentThread.Interrupt();
    }

    private void ThrowIfHandleUnavailable()
    {
        if (_handleUnavailable || _safeHandle.IsClosed || _safeHandle.IsInvalid)
        {
            throw new ObjectDisposedException(nameof(SingleflightResult));
        }
    }

    public void Dispose()
    {
        lock (_handleLock)
        {
            if (_transferPending)
            {
                WaitForPendingTransfer();
                if (_handleUnavailable) return;
            }
            if (_handleUnavailable) return;
            _handleUnavailable = true;
            WaitForBorrowedCalls();
            _safeHandle.Dispose();
        }
    }

}
