// This file is auto-generated by skif. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class SpecificFunction
{
    [JsonPropertyName("name")]
    public required string Name { get; set; }

}
