// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:205a7b75fa240e491b4e1490c3b77dda2a2b2e84c801d64e814d6bc4cd666b12
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class SpecificFunction
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

}
