// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f9775fe89ceec4ee0720df25e047c1a6ec50439a32a6f2733acb0361c18c3480
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class StreamChoice
{
    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

    [JsonPropertyName("delta")]
    public StreamDelta Delta { get; set; } = default!;

    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; set; } = null;

}
