// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9dee583ab8e6e0f65df1f89fa627db586ba659317208ed8d1c008438b1f104fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class StreamChoice
{
    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

    [JsonPropertyName("delta")]
    public StreamDelta Delta { get; set; } = default!;

    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; set; } = null;

}
