// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41d21abf52707d69ebb87c8552d3e5bacc5d389363b0c8aac9532710e95a3d16
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class StreamChoice
{
    [JsonPropertyName("index")]
    public uint Index { get; set; } = 0;

    [JsonPropertyName("delta")]
    public StreamDelta Delta { get; set; } = default!;

    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; set; } = null;

}
