// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b0c3fec4a462dc1f0b115559972d7928b49bd3b70174c28dac26a4bd5615e1c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class StreamDelta
{
    [JsonPropertyName("role")]
    public string? Role { get; set; } = null;

    [JsonPropertyName("content")]
    public string? Content { get; set; } = null;

    [JsonPropertyName("tool_calls")]
    public List<StreamToolCall>? ToolCalls { get; set; } = null;

    /// <summary>
    /// Deprecated legacy function_call delta; retained for API compatibility.
    /// </summary>
    [JsonPropertyName("function_call")]
    public StreamFunctionCall? FunctionCall { get; set; } = null;

    [JsonPropertyName("refusal")]
    public string? Refusal { get; set; } = null;

}
