// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2bc452c073728eb7b6a2ed9a7dd81f4c794a83109b071e7b69464cbc49e7c428
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class StreamFunctionCall
{
    [JsonPropertyName("name")]
    public string? Name { get; set; } = null;

    [JsonPropertyName("arguments")]
    public string? Arguments { get; set; } = null;

}
