// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2eff5a5898306573a865a2af15a6b78f3648564d55deae09b1385093783065d5
#nullable enable

using System;

namespace LiterLlm;

public class TimeoutException : LiterLlmErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
