// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3e997fe4dda32dae6bd87eb1d3c310840657a651554ac16974cc166dbf8aeb30
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ToolCall
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("call_type")]
    public ToolType CallType { get; set; } = default!;

    [JsonPropertyName("function")]
    public FunctionCall Function { get; set; } = default!;

}
