// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:92e7622797f9be001638249953d2d23f039ded20cdd262cec58deda9a3550c3b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum ToolChoice
{
    [JsonPropertyName("mode")]
    Mode,
    [JsonPropertyName("specific")]
    Specific,
}
