// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1096e9b464e7126fdfda1bf5858510a95b6448401f64e130b05193546d27e3e1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace LiterLlm;

public enum ToolChoice
{
    [JsonPropertyName("mode")]
    Mode,
    [JsonPropertyName("specific")]
    Specific,
}
