// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a2b2f507fb71321b519f3faab15b06b71fc7348fec67b0788faa6c431fc46ad9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ToolCall
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("call_type")]
    public ToolType CallType { get; set; } = default!;

    [JsonPropertyName("function")]
    public FunctionCall Function { get; set; } = default!;

}
