// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2b32d73ab143fd486148f534694c236cbdd7aef19a060bc60755cc2b358f204
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response from a transcription request.
/// </summary>
public sealed class TranscriptionResponse
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    [JsonPropertyName("language")]
    public string? Language { get; set; } = null;

    [JsonPropertyName("duration")]
    public double? Duration { get; set; } = null;

    [JsonPropertyName("segments")]
    public List<TranscriptionSegment>? Segments { get; set; } = null;

}
