// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a68c49b607eab373e8ef14fd3a308a7675b512b82473fff8d4e181222a759e37
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class Usage
{
    /// <summary>
    /// Prompt tokens used. Defaults to 0 when absent (some providers omit this).
    /// </summary>
    [JsonPropertyName("prompt_tokens")]
    public ulong PromptTokens { get; set; } = 0;

    /// <summary>
    /// Completion tokens used. Defaults to 0 when absent (e.g. embedding responses).
    /// </summary>
    [JsonPropertyName("completion_tokens")]
    public ulong CompletionTokens { get; set; } = 0;

    /// <summary>
    /// Total tokens used. Defaults to 0 when absent (some providers omit this).
    /// </summary>
    [JsonPropertyName("total_tokens")]
    public ulong TotalTokens { get; set; } = 0;

    /// <summary>
    /// Breakdown of tokens used in the prompt, including cached tokens served
    /// at the provider's discounted cache-read rate. Absent when the provider
    /// does not return prompt-token details.
    /// </summary>
    [JsonPropertyName("prompt_tokens_details")]
    public PromptTokensDetails? PromptTokensDetails { get; set; } = null;

}
