// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const liter_llm = @import("liter_llm");

// E2e tests for category: streaming

test "anthropic_stream" {
    // Streaming chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) yielding multiple SSE chunks
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 3);
    try testing.expectEqual("One Two Three", result.stream_content);
    try testing.expect(result.stream_complete);
}

test "azure_stream" {
    // Streaming chat completion via Azure OpenAI — verifies the azure/ prefix routes correctly and SSE chunks are delivered in the standard OpenAI chat.completion.chunk shape
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 3);
    try testing.expectEqual("1 2 3", result.stream_content);
    try testing.expect(result.stream_complete);
}

test "basic_stream" {
    // Streaming chat completion that produces content across multiple SSE chunks
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 3);
    try testing.expectEqual("1 2 3", result.stream_content);
}

test "bedrock_stream" {
    // Streaming chat completion via the AWS Bedrock provider using the bedrock/ prefix — verifies SSE chunks are yielded and assembled correctly from the Converse streaming API
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 2);
    try testing.expectEqual("One Two Three", result.stream_content);
    try testing.expect(result.stream_complete);
}

test "edge_stream_function_call" {
    // Streaming chat completion with tool/function call chunks
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 2);
}

test "empty_stream" {
    // Streaming chat completion that produces no content chunks before the DONE signal
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 0);
    try testing.expectEqual("", result.stream_content);
}

test "local_stream_ollama" {
    // Streaming chat completion via Ollama local provider with SSE chunks
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 3);
    try testing.expectEqual("1 2 3", result.stream_content);
    try testing.expect(result.stream_complete);
}

test "stream_content_policy_error" {
    // 400 Bad Request error on stream due to content policy violation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(@typeInfo(@TypeOf(result)) == .ErrorUnion);

test "stream_done_signal" {
    // Verify that the [DONE] sentinel signal properly terminates the stream
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.stream_complete);
    try testing.expectEqual("Done", result.stream_content);
    try testing.expect(result.no_chunks_after_done);
}

test "stream_error_401" {
    // 401 Unauthorized error on stream initiation before any chunks are received
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(@typeInfo(@TypeOf(result)) == .ErrorUnion);

test "stream_multiple_choices" {
    // Streaming chat completion with multiple choice outputs (n > 1)
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
}

test "stream_with_tool_calls" {
    // Streaming chat completion where the assistant responds with a tool call across multiple chunks
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 4);
    try testing.expectEqual("tool_calls", result.finish_reason);
    try testing.expect(result.tool_calls.len > 0);
    try testing.expectEqual("get_weather", result.tool_calls.get("0").function.name);
}

test "stream_with_usage" {
    // Streaming chat completion that includes a usage summary in the final chunk
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 3);
    try testing.expectEqual("Hi there!", result.stream_content);
    try testing.expectEqual(18, result.usage.total_tokens);
}

test "vertex_stream" {
    // Streaming chat completion via the Google Vertex AI provider using the vertex_ai/ prefix — verifies SSE chunks from the Gemini streaming endpoint are yielded and assembled correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const result = liter_llm.chat_stream(null);
    try testing.expect(result.chunks.len >= 2);
    try testing.expectEqual("One Two Three", result.stream_content);
    try testing.expect(result.stream_complete);
}

