// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: image-generate. */
class ImageGenerateTest {
    @Test
    fun testEdgeImageB64Response() {
        // Image generation returning base64-encoded data instead of URL
        val result = LiterLlm.imageGenerate(null)
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertFalse(result.data.get("0").b64_json.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testEdgeImageEmptyPrompt() {
        // Image generation with an empty prompt returns 400
        assertFailsWith<Exception> { LiterLlm.imageGenerate(null) }
    }

    @Test
    fun testEdgeImageMultipleN() {
        // Image generation requesting multiple images with n=3
        val result = LiterLlm.imageGenerate(null)
        assertEquals(3, result.data.size, "expected exactly 3 elements")
        assertFalse(result.data.get("0").url.isEmpty(), "expected non-empty value")
        assertFalse(result.data.get("1").url.isEmpty(), "expected non-empty value")
        assertFalse(result.data.get("2").url.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testErrorImageAuth401() {
        // 401 Unauthorized when generating images with invalid API key
        assertFailsWith<Exception> { LiterLlm.imageGenerate(null) }
    }

    @Test
    fun testErrorImageBadRequest() {
        // 400 Bad Request when image generation parameters are invalid
        assertFailsWith<Exception> { LiterLlm.imageGenerate(null) }
    }

    @Test
    fun testErrorImageRateLimit() {
        // 429 Rate limit exceeded for image generation
        assertFailsWith<Exception> { LiterLlm.imageGenerate(null) }
    }

    @Test
    fun testSmokeImageBasic() {
        // Basic image generation with a text prompt
        val result = LiterLlm.imageGenerate(null)
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertFalse(result.data.get("0").url.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testSmokeImageMultiple() {
        // Image generation requesting multiple images
        val result = LiterLlm.imageGenerate(null)
        assertEquals(3, result.data.size, "expected exactly 3 elements")
        assertFalse(result.data.get("0").url.isEmpty(), "expected non-empty value")
    }

    @Test
    fun testSmokeImageWithSize() {
        // Image generation with explicit size parameter
        val result = LiterLlm.imageGenerate(null)
        assertEquals(1, result.data.size, "expected exactly 1 elements")
        assertFalse(result.data.get("0").url.isEmpty(), "expected non-empty value")
    }

}
