// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: rerank. */
class RerankTest {
    @Test
    fun testEdgeRerankEmptyQuery() {
        // Reranking with an empty query string
        val result = LiterLlm.rerank(null)
        assertEquals(2, result.results.size, "expected exactly 2 elements")
    }

    @Test
    fun testEdgeRerankSingleDoc() {
        // Reranking with only a single document
        val result = LiterLlm.rerank(null)
        assertEquals(1, result.results.size, "expected exactly 1 elements")
        assertTrue(result.results.get("0").relevance_score > 0.9d, "expected > {kotlin_val}")
    }

    @Test
    fun testErrorRerankAuth401() {
        // 401 Unauthorized for reranking with invalid API key
        assertFailsWith<Exception> { LiterLlm.rerank(null) }
    }

    @Test
    fun testErrorRerankBadRequest() {
        // 400 Bad Request for reranking with invalid model
        assertFailsWith<Exception> { LiterLlm.rerank(null) }
    }

    @Test
    fun testSmokeRerankBasic() {
        // Basic reranking of documents against a query
        val result = LiterLlm.rerank(null)
        assertEquals(3, result.results.size, "expected exactly 3 elements")
        assertTrue(result.results.get("0").relevance_score > 0.9d, "expected > {kotlin_val}")
    }

    @Test
    fun testSmokeRerankReturnDocs() {
        // Reranking with return_documents flag to include document text
        val result = LiterLlm.rerank(null)
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        assertFalse(result.results.get("0").document.isEmpty(), "expected non-empty value")
        assertTrue(result.results.get("0").relevance_score > 0.9d, "expected > {kotlin_val}")
    }

    @Test
    fun testSmokeRerankWithTopN() {
        // Reranking with top_n parameter to limit results
        val result = LiterLlm.rerank(null)
        assertEquals(2, result.results.size, "expected exactly 2 elements")
        assertTrue(result.results.get("0").relevance_score > 0.9d, "expected > {kotlin_val}")
    }

}
