# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: budget."""
import pytest
from liter_llm import chat


@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_budget_enforced() -> None:
    """Tests that a request is rejected when budget is exceeded."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await chat(request=request)
    assert "BudgetExceeded" in str(exc_info.value)  # noqa: S101

@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_budget_per_model() -> None:
    """Tests per-model budget limit."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await chat(request=request)
    assert "BudgetExceeded" in str(exc_info.value)  # noqa: S101

@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_budget_tracked() -> None:
    """Tests that cost is tracked after a successful response."""
    request = None
    result = await chat(request=request)
    assert result.cost_tracked is True  # noqa: S101

