# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:086d5e733f4b715a3b34336c451dbf128f4bf09e9ea7cea1e6de24ed83c26097
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: parity."""

import pytest  # noqa: F401
from liter_llm import chat


@pytest.mark.asyncio
async def test_api_surface_parity() -> None:
    """Canonical API surface definition for cross-binding parity verification."""
    request = None
    _ = await chat(request=request)
