# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: streaming."""
import pytest
from liter_llm import chat_stream


@pytest.mark.asyncio
async def test_anthropic_stream() -> None:
    """Streaming chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) yielding multiple SSE chunks."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 3  # noqa: S101
    assert result.stream_content.strip() == "One Two Three"  # noqa: S101
    assert result.stream_complete is True  # noqa: S101

@pytest.mark.asyncio
async def test_azure_stream() -> None:
    """Streaming chat completion via Azure OpenAI — verifies the azure/ prefix routes correctly and SSE chunks are delivered in the standard OpenAI chat.completion.chunk shape."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 3  # noqa: S101
    assert result.stream_content.strip() == "1 2 3"  # noqa: S101
    assert result.stream_complete is True  # noqa: S101

@pytest.mark.asyncio
async def test_basic_stream() -> None:
    """Streaming chat completion that produces content across multiple SSE chunks."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 3  # noqa: S101
    assert result.stream_content.strip() == "1 2 3"  # noqa: S101

@pytest.mark.asyncio
async def test_bedrock_stream() -> None:
    """Streaming chat completion via the AWS Bedrock provider using the bedrock/ prefix — verifies SSE chunks are yielded and assembled correctly from the Converse streaming API."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 2  # noqa: S101
    assert result.stream_content.strip() == "One Two Three"  # noqa: S101
    assert result.stream_complete is True  # noqa: S101

@pytest.mark.asyncio
async def test_edge_stream_function_call() -> None:
    """Streaming chat completion with tool/function call chunks."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 2  # noqa: S101

@pytest.mark.asyncio
async def test_empty_stream() -> None:
    """Streaming chat completion that produces no content chunks before the DONE signal."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 0  # noqa: S101
    assert result.stream_content.strip() == ""  # noqa: S101

@pytest.mark.asyncio
async def test_local_stream_ollama() -> None:
    """Streaming chat completion via Ollama local provider with SSE chunks."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 3  # noqa: S101
    assert result.stream_content.strip() == "1 2 3"  # noqa: S101
    assert result.stream_complete is True  # noqa: S101

@pytest.mark.asyncio
async def test_stream_content_policy_error() -> None:
    """400 Bad Request error on stream due to content policy violation."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await chat_stream(request=request)
    assert "ContentPolicy" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_stream_done_signal() -> None:
    """Verify that the [DONE] sentinel signal properly terminates the stream."""
    request = None
    result = await chat_stream(request=request)
    assert result.stream_complete is True  # noqa: S101
    assert result.stream_content.strip() == "Done"  # noqa: S101
    assert result.no_chunks_after_done is True  # noqa: S101

@pytest.mark.asyncio
async def test_stream_error_401() -> None:
    """401 Unauthorized error on stream initiation before any chunks are received."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await chat_stream(request=request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_stream_multiple_choices() -> None:
    """Streaming chat completion with multiple choice outputs (n > 1)."""
    request = None
    _ = await chat_stream(request=request)

@pytest.mark.asyncio
async def test_stream_with_tool_calls() -> None:
    """Streaming chat completion where the assistant responds with a tool call across multiple chunks."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 4  # noqa: S101
    assert result.finish_reason.strip() == "tool_calls"  # noqa: S101
    assert result.tool_calls  # noqa: S101
    assert result.tool_calls.get("0").function.name.strip() == "get_weather"  # noqa: S101

@pytest.mark.asyncio
async def test_stream_with_usage() -> None:
    """Streaming chat completion that includes a usage summary in the final chunk."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 3  # noqa: S101
    assert result.stream_content.strip() == "Hi there!"  # noqa: S101
    assert result.usage.total_tokens == 18  # noqa: S101

@pytest.mark.asyncio
async def test_vertex_stream() -> None:
    """Streaming chat completion via the Google Vertex AI provider using the vertex_ai/ prefix — verifies SSE chunks from the Gemini streaming endpoint are yielded and assembled correctly."""
    request = None
    result = await chat_stream(request=request)
    assert len(result.chunks) >= 2  # noqa: S101
    assert result.stream_content.strip() == "One Two Three"  # noqa: S101
    assert result.stream_complete is True  # noqa: S101

