# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import pytest

from .mock_server import MockRoute, MockServerInfo
from liter_lm import LlmClient  # noqa: E402


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 200, "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-abc123\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":10,\"total_tokens\":15}}"),
]], indirect=True)
async def test_basic_chat(mock_server: MockServerInfo) -> None:
    """Basic chat completion with a single user message"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}")
    response = await client.chat(**request)

    assert len(response.choices) == 1, f"Expected 1 choice(s), got {len(response.choices)}"
    assert response.choices[0].message.content == "Hello!", "message content mismatch"
    assert response.choices[0].finish_reason == "stop", "finish_reason mismatch"
    assert response.usage is not None, "Expected usage object"
    assert response.usage.total_tokens == 15, "total_tokens mismatch"
    assert response.model == "gpt-4", "model mismatch"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/embeddings", "POST", 200, "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}"),
]], indirect=True)
async def test_basic_embed(mock_server: MockServerInfo) -> None:
    """Basic embedding request for a single input string"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}")
    response = await client.embed(**request)

    assert len(response.data) == 1, f"Expected 1 embedding(s), got {len(response.data)}"
    assert len(response.data[0].embedding) == 5, f"Expected 5 dimensions, got {len(response.data[0].embedding)}"
    assert len(response.data) >= 1, f"Expected at least 1 embedding(s), got {len(response.data)}"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/models", "GET", 200, "{\"data\":[{\"created\":1687882411,\"id\":\"gpt-4\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1677610602,\"id\":\"gpt-3.5-turbo\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1705948997,\"id\":\"text-embedding-3-small\",\"object\":\"model\",\"owned_by\":\"openai\"}],\"object\":\"list\"}"),
]], indirect=True)
async def test_basic_list_models(mock_server: MockServerInfo) -> None:
    """List available models from the API"""
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    response = await client.list_models()

    assert len(response.data) == 3, f"Expected 3 model(s), got {len(response.data)}"
    assert len(response.data) >= 1, f"Expected at least 1 model(s), got {len(response.data)}"
