# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd4bd43ad1afb33e61e2d9a4fe672e91dbaa722db783a4a57afc77103d2f0cfa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: custom_provider."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_provider_auth() -> None:
    """Tests custom provider with custom auth header."""
    request = {
        "messages": [{"content": "Hello", "role": "user"}],
        "model": "my-auth-model-v1",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/provider_auth",
    )
    _ = await client.chat(request=request)


@pytest.mark.asyncio
async def test_register_provider() -> None:
    """Tests that a custom provider can be registered and routes requests."""
    request = {
        "messages": [{"content": "Hello", "role": "user"}],
        "model": "my-model-v1",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/register_provider",
    )
    _ = await client.chat(request=request)
