# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72fa626ed0d1eeed19fba3e2c3961232c56978b5faa6b2b88aee435dd60fb47f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: smoke."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_anthropic_chat() -> None:
    """Basic chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) with system and user messages."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/anthropic_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "claude-3-5-sonnet-20241022"  # noqa: S101
    assert result.usage.total_tokens == 23  # noqa: S101


@pytest.mark.asyncio
async def test_azure_chat() -> None:
    """Chat completion via Azure OpenAI with the azure/ prefix for provider routing — verifies the prefix is stripped before dispatching and the response is normalised to the standard OpenAI chat completion shape."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/azure_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "gpt-4"  # noqa: S101
    assert result.usage.total_tokens == 13  # noqa: S101


@pytest.mark.asyncio
async def test_azure_embed() -> None:
    """Embedding request via Azure OpenAI using the azure/ provider prefix — response follows the standard OpenAI embeddings shape that Azure returns unchanged."""
    request = "Hello world"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/azure_embed",
    )
    result = await client.embed(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert len(result.data.get("0").embedding) == 1536  # noqa: S101


@pytest.mark.asyncio
async def test_basic_chat() -> None:
    """Basic chat completion with a single user message."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/basic_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.usage.total_tokens == 15  # noqa: S101
    assert result.model.strip() == "gpt-4"  # noqa: S101


@pytest.mark.asyncio
async def test_basic_embed() -> None:
    """Basic embedding request for a single input string."""
    request = "Hello world"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/basic_embed",
    )
    result = await client.embed(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert len(result.data.get("0").embedding) == 5  # noqa: S101


@pytest.mark.asyncio
async def test_basic_list_models() -> None:
    """List available models from the API."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/basic_list_models",
    )
    result = await client.list_models()
    assert len(result.data) >= 1  # noqa: S101


@pytest.mark.asyncio
async def test_bedrock_chat() -> None:
    """Basic chat completion via the AWS Bedrock provider using the bedrock/ prefix for routing — verifies the prefix is stripped before dispatching and the Converse API response is normalised to the standard OpenAI chat completion shape."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/bedrock_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "anthropic.claude-3-sonnet-20240229-v1:0"  # noqa: S101
    assert result.usage.total_tokens == 15  # noqa: S101


@pytest.mark.asyncio
async def test_github_copilot_chat() -> None:
    """Basic chat completion via the GitHub Copilot provider (gpt-4o) with a single user message."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/github_copilot_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "gpt-4o"  # noqa: S101
    assert result.usage.total_tokens == 14  # noqa: S101


@pytest.mark.asyncio
async def test_local_chat_ollama() -> None:
    """Chat completion against local Ollama with qwen2:0.5b model."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/local_chat_ollama",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101


@pytest.mark.asyncio
async def test_local_list_models_ollama() -> None:
    """List models from local Ollama instance."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/local_list_models_ollama",
    )
    result = await client.list_models()
    assert len(result.data) >= 1  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_cache_memory() -> None:
    """Test in-memory caching by sending identical requests twice."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_cache_memory",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_chat_anthropic() -> None:
    """Basic chat completion against real Anthropic API."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_chat_anthropic",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101
    assert result.usage  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_chat_gemini() -> None:
    """Basic chat completion against real Google Gemini API."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_chat_gemini",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101
    assert result.usage  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_chat_openai() -> None:
    """Basic chat completion against real OpenAI API."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_chat_openai",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101
    assert result.usage  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_embed_openai() -> None:
    """Embeddings request against real OpenAI API."""
    request = ["Hello world"]
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_embed_openai",
    )
    result = await client.embed(request=request)
    assert result.data  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_list_models_openai() -> None:
    """List models against real OpenAI API."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_list_models_openai",
    )
    result = await client.list_models()
    assert len(result.data) >= 1  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_provider_routing() -> None:
    """Test provider routing by sending requests to OpenAI and Anthropic."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_provider_routing",
    )
    result = await client.chat(request=request)
    assert result.choices  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_streaming_openai() -> None:
    """Chat streaming against real OpenAI API, verifies chunks received."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_streaming_openai",
    )
    result = await client.chat_stream(request=request)
    assert len(result.chunks) >= 1  # noqa: S101


@pytest.mark.asyncio
async def test_vertex_chat() -> None:
    """Basic chat completion via the Google Vertex AI provider using the vertex_ai/ prefix for routing — verifies the prefix is stripped before dispatching and the Gemini response is normalised to the standard OpenAI chat completion shape."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/vertex_chat",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hello!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "gemini-2.0-flash"  # noqa: S101
    assert result.usage.total_tokens == 13  # noqa: S101


@pytest.mark.asyncio
async def test_vertex_embed() -> None:
    """Embedding request via Google Vertex AI using the vertex_ai/ provider prefix and the text-embedding-005 model — response follows the standard OpenAI embeddings shape."""
    request = "Hello"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/vertex_embed",
    )
    result = await client.embed(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert len(result.data.get("0").embedding) == 160  # noqa: S101
