# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9470df7acbffad78fd393d6804256d4c1ea0679996f6589e9c339e2532788099
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: custom_provider."""

import os

import pytest  # noqa: F401
from liter_llm import create_client
from liter_llm._internal_bindings import ChatCompletionRequest


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_provider_auth() -> None:
    """Tests custom provider with custom auth header."""
    request = ChatCompletionRequest.from_json(
        '{"messages":[{"content":"Hello","role":"user"}],"model":"my-auth-model-v1"}'
    )
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/provider_auth",
    )
    _ = await client.chat(request)


@pytest.mark.asyncio
async def test_register_provider() -> None:
    """Tests that a custom provider can be registered and routes requests."""
    request = ChatCompletionRequest.from_json(
        '{"messages":[{"content":"Hello","role":"user"}],"model":"my-model-v1"}'
    )
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/register_provider",
    )
    _ = await client.chat(request)
