# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d11df3c4e7f4543f667550bcf684b43ce46e833b130430271e325201a3bc0d4b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: configuration."""

import pytest  # noqa: F401
from liter_llm import chat


@pytest.mark.asyncio
async def test_custom_base_url() -> None:
    """Client configured with a custom base URL routes all requests to that endpoint."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "Hi there!"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "local-model"  # noqa: S101


@pytest.mark.asyncio
async def test_extra_headers() -> None:
    """Client configured with extra custom headers successfully completes a chat request."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_local_provider_llamacpp() -> None:
    """llamacpp local provider routes requests via llamacpp/ model prefix with no auth."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert (
        result.choices.get("0").message.content.strip()
        == "Hi there! I'm running locally."
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "my-model"  # noqa: S101


@pytest.mark.asyncio
async def test_local_provider_ollama() -> None:
    """Ollama local provider routes requests via ollama/ model prefix with no auth."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert (
        result.choices.get("0").message.content.strip()
        == "Hello! How can I help you today?"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "qwen2:0.5b"  # noqa: S101


@pytest.mark.asyncio
async def test_local_provider_vllm() -> None:
    """vLLM local provider routes requests via vllm/ model prefix with no auth."""
    request = None
    result = await chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert (
        result.choices.get("0").message.content.strip()
        == "Hello! How may I assist you?"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.model.strip() == "meta-llama/Llama-3.2-1B"  # noqa: S101
