# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:891595ac549bc056d3c97cdf20c5b7a1d7c29df546b63dd0f808993635bdc6a6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: chat."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_developer_message() -> None:
    """Chat request that includes a developer role message alongside user messages."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/developer_message",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "s[::-1]"  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_edge_chat_max_tokens() -> None:
    """Chat request with max_tokens=1 terminates with length finish_reason."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_chat_max_tokens",
    )
    result = await client.chat(request=request)
    assert result.choices.get("0").finish_reason.strip() == "length"  # noqa: S101
    assert result.choices.get("0").message.content  # noqa: S101


@pytest.mark.asyncio
async def test_edge_chat_system_only() -> None:
    """Chat request with system message and user message."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_chat_system_only",
    )
    result = await client.chat(request=request)
    assert result.choices.get("0").message.content  # noqa: S101


@pytest.mark.asyncio
async def test_edge_chat_temperature_zero() -> None:
    """Chat request with temperature=0 for deterministic responses."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_chat_temperature_zero",
    )
    result = await client.chat(request=request)
    assert result.choices.get("0").message.content  # noqa: S101


@pytest.mark.asyncio
async def test_finish_reason_content_filter() -> None:
    """Chat response stopped by content filter with finish_reason of content_filter and null content."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/finish_reason_content_filter",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "content_filter"  # noqa: S101


@pytest.mark.asyncio
async def test_finish_reason_length() -> None:
    """Chat response truncated due to max_tokens limit with finish_reason of length."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/finish_reason_length",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "length"  # noqa: S101


@pytest.mark.asyncio
async def test_multi_turn_conversation() -> None:
    """Multi-turn conversation with system, user, assistant, and follow-up user messages."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/multi_turn_conversation",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content.strip() == "4 + 4 equals 8."  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_parallel_tool_calls() -> None:
    """Chat request that results in parallel tool calls in the response."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/parallel_tool_calls",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.tool_calls  # noqa: S101
    assert len(result.choices.get("0").message.tool_calls) == 2  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "tool_calls"  # noqa: S101


@pytest.mark.asyncio
async def test_response_format_json_object() -> None:
    """Chat request with response_format json_object that returns valid JSON content."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/response_format_json_object",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_response_format_json_schema() -> None:
    """Chat request with response_format json_schema that validates the output structure."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/response_format_json_schema",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.content  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_seed_parameter() -> None:
    """Chat request with seed parameter for deterministic output; response includes system_fingerprint."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/seed_parameter",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101
    assert result.system_fingerprint  # noqa: S101


@pytest.mark.asyncio
async def test_stop_sequences() -> None:
    """Chat request with custom stop sequences that terminates generation at a stop token."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/stop_sequences",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "stop"  # noqa: S101


@pytest.mark.asyncio
async def test_tool_choice_required() -> None:
    """Chat request with tool_choice set to required forces the model to call a tool."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/tool_choice_required",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.tool_calls  # noqa: S101
    assert (
        result.choices.get("0").message.tool_calls.get("0").function.name.strip()
        == "get_weather"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "tool_calls"  # noqa: S101


@pytest.mark.asyncio
async def test_tool_choice_specific() -> None:
    """Chat request with tool_choice specifying a particular function to call."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/tool_choice_specific",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.tool_calls  # noqa: S101
    assert (
        result.choices.get("0").message.tool_calls.get("0").function.name.strip()
        == "get_weather"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "tool_calls"  # noqa: S101
