# Code generated by liter-llm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import pytest

from .mock_server import MockRoute, MockServerInfo
from liter_llm import (  # noqa: E402
    LlmClient,
    AuthenticationError,
    BadRequestError,
)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/audio/speech", "POST", 200, "{\"_binary\":true,\"_content_type\":\"audio/mpeg\",\"_description\":\"Mock binary audio data for long text\"}"),
]], indirect=True)
async def test_edge_speech_long_input(mock_server: MockServerInfo) -> None:
    """Speech generation with a very long input text"""
    # TODO: unknown method "speech"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/audio/speech", "POST", 401, "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}"),
]], indirect=True)
async def test_error_speech_auth_401(mock_server: MockServerInfo) -> None:
    """401 Unauthorized for speech generation with invalid API key"""
    # TODO: unknown method "speech"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/audio/speech", "POST", 400, "{\"error\":{\"code\":\"model_not_found\",\"message\":\"The model 'tts-nonexistent' does not exist.\",\"param\":\"model\",\"type\":\"invalid_request_error\"}}"),
]], indirect=True)
async def test_error_speech_bad_model(mock_server: MockServerInfo) -> None:
    """400 Bad Request for speech with unsupported model"""
    # TODO: unknown method "speech"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/audio/speech", "POST", 200, "{\"_binary\":true,\"_content_type\":\"audio/mpeg\",\"_description\":\"Mock binary audio data\"}"),
]], indirect=True)
async def test_smoke_speech_basic(mock_server: MockServerInfo) -> None:
    """Basic text-to-speech generation"""
    # TODO: unknown method "speech"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/audio/speech", "POST", 200, "{\"_binary\":true,\"_content_type\":\"audio/mpeg\",\"_description\":\"Mock MP3 audio data\"}"),
]], indirect=True)
async def test_smoke_speech_mp3_format(mock_server: MockServerInfo) -> None:
    """Text-to-speech with explicit MP3 response format"""
    # TODO: unknown method "speech"
