# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2addb3add4d8f73d9653de98d940004b84563df36d0910c2efb352bbe82852a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: search."""

import pytest  # noqa: F401
from liter_llm import search


@pytest.mark.asyncio
async def test_search_basic() -> None:
    """Basic web search request with a simple query."""
    request = None
    _ = await search(request=request)


@pytest.mark.asyncio
async def test_search_empty_results() -> None:
    """Web search with a query that returns no results."""
    request = None
    _ = await search(request=request)


@pytest.mark.asyncio
async def test_search_error_400() -> None:
    """400 Bad Request error when search query is empty."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await search(request=request)
    assert "BadRequest" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_search_error_401() -> None:
    """401 Unauthorized error on web search due to invalid API credentials."""
    request = None
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await search(request=request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_search_with_max_results() -> None:
    """Search request with max_results parameter limiting response count."""
    request = None
    result = await search(request=request)
    assert len(result.results) == 2  # noqa: S101
