# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e77dd8ab0409e13a920a1e5e00bf1999e524e4f2ce6f3c3520c3b6bd1f70428
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: batches."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_edge_batch_already_cancelled() -> None:
    """Attempt to cancel an already-cancelled batch."""
    batch_id = "batch-cancelled001"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/edge_batch_already_cancelled",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.cancel_batch(batch_id=batch_id)
    assert "BadRequest" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_edge_batch_empty_list() -> None:
    """List batches when no batches exist."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_batch_empty_list",
    )
    result = await client.list_batches()
    assert len(result.data) == 0  # noqa: S101


@pytest.mark.asyncio
async def test_error_batch_auth_401() -> None:
    """401 Unauthorized when creating a batch with invalid API key."""
    request = {
        "completion_window": "24h",
        "endpoint": "/v1/chat/completions",
        "input_file_id": "file-abc123",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_batch_auth_401",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.create_batch(request=request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_error_batch_invalid_file() -> None:
    """400 Bad Request when creating a batch with invalid input file."""
    request = {
        "completion_window": "24h",
        "endpoint": "/v1/chat/completions",
        "input_file_id": "file-wrong-purpose",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_batch_invalid_file",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.create_batch(request=request)
    assert "BadRequest" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_error_batch_not_found() -> None:
    """404 Not Found when retrieving a nonexistent batch."""
    batch_id = "batch-nonexistent"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_batch_not_found",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.retrieve_batch(batch_id=batch_id)
    assert "NotFound" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_batch_completed() -> None:
    """Retrieve a completed batch job with output file."""
    batch_id = "batch-ghi789"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_batch_completed",
    )
    result = await client.retrieve_batch(batch_id=batch_id)
    assert result.id  # noqa: S101
    assert result.status.strip() == "completed"  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_cancel_batch() -> None:
    """Cancel a running batch job."""
    batch_id = "batch-def456"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_cancel_batch",
    )
    result = await client.cancel_batch(batch_id=batch_id)
    assert result.id  # noqa: S101
    assert result.status.strip() == "cancelling"  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_create_batch() -> None:
    """Create a new batch processing job."""
    request = {
        "completion_window": "24h",
        "endpoint": "/v1/chat/completions",
        "input_file_id": "file-abc123",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_create_batch",
    )
    result = await client.create_batch(request=request)
    assert result.id  # noqa: S101
    assert result.status.strip() == "validating"  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_list_batches() -> None:
    """List all batch jobs."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_list_batches",
    )
    result = await client.list_batches()
    assert len(result.data) == 2  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_retrieve_batch() -> None:
    """Retrieve the status of a batch job."""
    batch_id = "batch-abc123"
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_retrieve_batch",
    )
    result = await client.retrieve_batch(batch_id=batch_id)
    assert result.id  # noqa: S101
    assert result.status.strip() == "in_progress"  # noqa: S101
