# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f157485dda98584a4a9fcaa3f452097905ec091c5cbbee65f4efdfb625e95c0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: tool-calling."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_anthropic_tool_calling() -> None:
    """Chat request to Anthropic provider with a tool definition; assistant responds with a tool call."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/anthropic_tool_calling",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.tool_calls  # noqa: S101
    assert (
        result.choices.get("0").message.tool_calls.get("0").function.name.strip()
        == "get_weather"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "tool_calls"  # noqa: S101


@pytest.mark.asyncio
async def test_single_tool_call() -> None:
    """Chat request with a tool definition; assistant responds with a tool call."""
    request = None
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/single_tool_call",
    )
    result = await client.chat(request=request)
    assert len(result.choices) == 1  # noqa: S101
    assert result.choices.get("0").message.tool_calls  # noqa: S101
    assert (
        result.choices.get("0").message.tool_calls.get("0").function.name.strip()
        == "get_weather"
    )  # noqa: S101
    assert result.choices.get("0").finish_reason.strip() == "tool_calls"  # noqa: S101
