# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:79e3ec419a9b820a48ee0524da399b765de18673f55f61be2ec721aa2b2b8e69
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: transcribe."""

import os

import pytest  # noqa: F401
from liter_llm import create_client


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_edge_transcribe_empty_audio() -> None:
    """Transcription of a silent or empty audio file returns empty text."""
    request = {"file": "silence.mp3", "model": "whisper-1"}
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/edge_transcribe_empty_audio",
    )
    result = await client.transcribe(request)
    assert "" in result.text  # noqa: S101


@pytest.mark.asyncio
async def test_edge_transcribe_with_timestamps() -> None:
    """Transcription with verbose JSON response format including timestamp segments."""
    request = {
        "file": "audio.mp3",
        "model": "whisper-1",
        "response_format": "verbose_json",
    }
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/edge_transcribe_with_timestamps",
    )
    result = await client.transcribe(request)
    assert result.text  # noqa: S101
    assert len(result.segments) == 3  # noqa: S101
    assert result.segments[0].id == 0  # noqa: S101


@pytest.mark.asyncio
async def test_error_transcribe_auth_401() -> None:
    """401 Unauthorized for transcription with invalid API key."""
    request = {"file": "audio.mp3", "model": "whisper-1"}
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_transcribe_auth_401",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.transcribe(request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_error_transcribe_bad_format() -> None:
    """400 Bad Request when audio format is unsupported."""
    request = {"file": "audio.xyz", "model": "whisper-1"}
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/error_transcribe_bad_format",
    )
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.transcribe(request)
    assert "BadRequest" in str(exc_info.value)  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_transcribe_basic() -> None:
    """Basic audio transcription."""
    request = {"file": "audio.mp3", "model": "whisper-1"}
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_transcribe_basic",
    )
    result = await client.transcribe(request)
    assert "Hello, this is a test transcription." in result.text  # noqa: S101


@pytest.mark.asyncio
async def test_smoke_transcribe_with_language() -> None:
    """Audio transcription with explicit language hint."""
    request = {"file": "audio_de.mp3", "language": "de", "model": "whisper-1"}
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"]
        + "/fixtures/smoke_transcribe_with_language",
    )
    result = await client.transcribe(request)
    assert "Hallo, dies ist ein Testtranskription." in result.text  # noqa: S101
