// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** E2e tests for category: custom_provider. */
class CustomProviderTest {
    @Test
    void testProviderAuth() throws Exception {
        // Tests custom provider with custom auth header
        var result = LiterLlm.chat(null);
    }

    @Test
    void testRegisterProvider() throws Exception {
        // Tests that a custom provider can be registered and routes requests
        var result = LiterLlm.chat(null);
    }

}
