// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** E2e tests for category: speech. */
class SpeechTest {
    @Test
    void testEdgeSpeechAllVoices() throws Exception {
        // Text-to-speech with specific voice selection
        var result = LiterLlm.speech("Hello world");
        assertFalse(result.audio().isEmpty(), "expected non-empty value");
    }

    @Test
    void testEdgeSpeechLongInput() throws Exception {
        // Speech generation with a very long input text
        var result = LiterLlm.speech("This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. This is a long input text. End of input.");
        assertFalse(result.audio().isEmpty(), "expected non-empty value");
    }

    @Test
    void testErrorSpeechAuth401() throws Exception {
        // 401 Unauthorized for speech generation with invalid API key
        assertThrows(Exception.class, () -> LiterLlm.speech("Hello"));
    }

    @Test
    void testErrorSpeechBadModel() throws Exception {
        // 400 Bad Request for speech with unsupported model
        assertThrows(Exception.class, () -> LiterLlm.speech("Hello"));
    }

    @Test
    void testSmokeSpeechBasic() throws Exception {
        // Basic text-to-speech generation
        var result = LiterLlm.speech("Hello, world!");
        assertFalse(result.audio().isEmpty(), "expected non-empty value");
    }

    @Test
    void testSmokeSpeechMp3Format() throws Exception {
        // Text-to-speech with explicit MP3 response format
        var result = LiterLlm.speech("The quick brown fox jumps over the lazy dog.");
        assertFalse(result.audio().isEmpty(), "expected non-empty value");
    }

}
