// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6fc119871cf5f782cc343e62b8d9917c09e762d64dcb2e93ca9de46fce1ecb9f
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: configuration.
final class ConfigurationTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testCustomBaseUrl() async throws {
        // Client configured with a custom base URL routes all requests to that endpoint
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"local-model\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/custom_base_url")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "local-model")
    }

    func testExtraHeaders() async throws {
        // Client configured with extra custom headers successfully completes a chat request
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/extra_headers")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
    }

    func testLocalProviderLlamacpp() async throws {
        // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"llamacpp/my-model\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/local_provider_llamacpp")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "my-model")
    }

    func testLocalProviderOllama() async throws {
        // Ollama local provider routes requests via ollama/ model prefix with no auth
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"ollama/qwen2:0.5b\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/local_provider_ollama")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "qwen2:0.5b")
    }

    func testLocalProviderVllm() async throws {
        // vLLM local provider routes requests via vllm/ model prefix with no auth
        let _req = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"vllm/meta-llama/Llama-3.2-1B\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/local_provider_vllm")
        let result = try await _client.chat(_req)
        XCTAssertNotNil(result)
        XCTAssertEqual(result.choices().count, 1)
        // skipped: enum field 'choices[0].message.content' is a payload-carrying union with no scalar wire accessor in this binding
        let _vec_choices_equals_f15f117a_1 = result.choices()
        XCTAssertEqual((_vec_choices_equals_f15f117a_1[0].finishReason()?.toString() ?? ""), "stop")
        XCTAssertEqual(result.model().toString(), "meta-llama/Llama-3.2-1B")
    }

}
