# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ecb2cd0e3e7abd637e31fd91a84420902c09c73c73bcfe396b1cfd2c391fcae6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.AssistantMessage do
  @moduledoc false

  defstruct content: "",
            name: "",
            tool_calls: [],
            refusal: "",
            function_call: nil
end
