# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc2242373c99a2e6405230f8c73507c7a07ab6b09237b4d4e68bf099180c72a4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.AssistantContent do
  @moduledoc """
  Content shape for assistant messages.

  `#[serde(untagged)]` means providers returning a plain scalar string for the
  `content` field still deserialise correctly into `AssistantContent::Text(_)`.
  Providers returning an array of typed parts (e.g. after an image-generation
  or audio-synthesis request) deserialise into `AssistantContent::Parts(_)`.
  """

  @typedoc "Content shape for assistant messages."
  @type t :: term()

  @typedoc "Plain text response (the common case for text-only models)."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Structured parts — text, refusals, output images, output audio."
  @type parts :: %{type: :parts, value: [map()]}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "Text"
  def wire_value(:parts), do: "Parts"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
  def wire_value(value) when is_map(value), do: Map.fetch!(value, :type)

  defimpl String.Chars, for: LiterLlm.AssistantContent do
    @doc false
    def to_string(value), do: LiterLlm.AssistantContent.wire_value(value)
  end
end
