# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fabe5851415f1e045f1327c562cb4356d128c85e1e6a7f5710057bea833d1f83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.AudioContent do
  @moduledoc false

  defstruct data: "",
            format: ""
end
