# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c4b69cccc2a3195e8d8ab29335f38acd8d8a41593313f6970aab6f52cc78b64
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.BatchRequestCounts do
  @moduledoc false

  defstruct total: 0,
            completed: 0,
            failed: 0
end
