# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce30516c3eeb8d419050cf7182d1826cbe0cec43b565cc955c34a37186dd9326
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.BatchStatus do
  @moduledoc "Status of a batch job."

  @typedoc "Status of a batch job."
  @type t :: :validating | :failed | :in_progress | :finalizing | :completed | :expired | :cancelling | :cancelled

  @validating :validating
  @failed :failed
  @in_progress :in_progress
  @finalizing :finalizing
  @completed :completed
  @expired :expired
  @cancelling :cancelling
  @cancelled :cancelled

  @doc "Validating the input file."
  @spec validating() :: t()
  def validating, do: @validating
  @doc "Job failed."
  @spec failed() :: t()
  def failed, do: @failed
  @doc "Job is running."
  @spec in_progress() :: t()
  def in_progress, do: @in_progress
  @doc "Finalizing results."
  @spec finalizing() :: t()
  def finalizing, do: @finalizing
  @doc "Job completed successfully."
  @spec completed() :: t()
  def completed, do: @completed
  @doc "Job expired before completion."
  @spec expired() :: t()
  def expired, do: @expired
  @doc "Job is being cancelled."
  @spec cancelling() :: t()
  def cancelling, do: @cancelling
  @doc "Job has been cancelled."
  @spec cancelled() :: t()
  def cancelled, do: @cancelled

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:validating), do: "validating"
  def wire_value(:failed), do: "failed"
  def wire_value(:in_progress), do: "in_progress"
  def wire_value(:finalizing), do: "finalizing"
  def wire_value(:completed), do: "completed"
  def wire_value(:expired), do: "expired"
  def wire_value(:cancelling), do: "cancelling"
  def wire_value(:cancelled), do: "cancelled"
end
