# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3238d1920b780057a39ece07e0db3ffb18b05ce46948cebd8da2b35ffefe11e6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ChatCompletionRequest do
  @moduledoc "Chat completion request (compatible with OpenAI and similar APIs)."

  @typedoc "Chat completion request (compatible with OpenAI and similar APIs)."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          messages: [LiterLlm.Message.t()],
          temperature: float() | nil,
          top_p: float() | nil,
          n: non_neg_integer() | nil,
          stream: boolean() | nil,
          stop: LiterLlm.StopSequence.t() | nil,
          max_tokens: non_neg_integer() | nil,
          presence_penalty: float() | nil,
          frequency_penalty: float() | nil,
          logit_bias: map() | nil,
          user: String.t() | nil,
          tools: [LiterLlm.ChatCompletionTool.t()] | nil,
          tool_choice: LiterLlm.ToolChoice.t() | nil,
          parallel_tool_calls: boolean() | nil,
          response_format: LiterLlm.ResponseFormat.t() | nil,
          stream_options: LiterLlm.StreamOptions.t() | nil,
          seed: integer() | nil,
          reasoning_effort: LiterLlm.ReasoningEffort.t() | nil,
          modalities: [LiterLlm.Modality.t()] | nil,
          logprobs: boolean() | nil,
          top_logprobs: non_neg_integer() | nil,
          max_completion_tokens: non_neg_integer() | nil,
          service_tier: String.t() | nil,
          store: boolean() | nil,
          metadata: map() | nil,
          prediction: String.t() | nil,
          audio: String.t() | nil,
          web_search_options: String.t() | nil,
          extra_body: String.t() | nil
        }

  defstruct model: nil,
            messages: [],
            temperature: nil,
            top_p: nil,
            n: nil,
            stream: nil,
            stop: nil,
            max_tokens: nil,
            presence_penalty: nil,
            frequency_penalty: nil,
            logit_bias: nil,
            user: nil,
            tools: nil,
            tool_choice: nil,
            parallel_tool_calls: nil,
            response_format: nil,
            stream_options: nil,
            seed: nil,
            reasoning_effort: nil,
            modalities: nil,
            logprobs: nil,
            top_logprobs: nil,
            max_completion_tokens: nil,
            service_tier: nil,
            store: nil,
            metadata: nil,
            prediction: nil,
            audio: nil,
            web_search_options: nil,
            extra_body: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
