# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f476e68b433a0d50cc4a8be91d317d3deb20d476cfc4f13a0cba44f9cd2a9f87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ChatCompletionTool do
  @moduledoc false

  defstruct tool_type: :function,
            function: nil
end
