# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8c2340a1e2c8a4f9d34b3bd98bdc230e853548625f4a45f661bd058c25a629ea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.Choice do
  @moduledoc false

  defstruct index: 0,
            message: nil,
            finish_reason: :stop
end
