# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b22c397ecc47fb710ec98b1a82931cf452d8f2aa2b4c5c6c98c6549897af3b05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.Choice do
  @moduledoc false

  defstruct index: 0,
            message: nil,
            finish_reason: :stop
end
