# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bfe58e04e66bcab813eb67acfd6b85f53fa0ec424cde2fce7a6b2147fa635f43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.CreateResponseRequest do
  @moduledoc false

  defstruct model: "",
            input: "",
            instructions: "",
            tools: [],
            temperature: 0.0,
            max_output_tokens: 0,
            metadata: ""
end
