# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a3c1fdecbfd9e7810f9fd202240f3d2c63812fa6870a03440f05251fbd7f185
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.CreateFileRequest do
  @moduledoc false

  defstruct file: "",
            purpose: :assistants,
            filename: ""
end
