# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3faee1ed03a6c9b6f0cadb0ede4a552d8370339501b8d385182da74c720571c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.CreateImageRequest do
  @moduledoc "Request to create images from a text prompt."

  defstruct prompt: "",
            model: "",
            n: 0,
            size: "",
            quality: "",
            style: "",
            response_format: "",
            user: ""
end
