# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e95ee799108b12f0686c3acd370e8158a77468446ac707e8dcbddb2e927fa484
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.DocumentContent do
  @moduledoc false

  defstruct data: "",
            media_type: ""
end
