# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b8d1c971805e7a1549010b7882f8fee28e25c07fde1b90737024cde299aee26f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingObject do
  @moduledoc false

  defstruct object: "",
            embedding: [],
            index: 0
end
