# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6c25638781cc2e821195d329f2a9514027c1c7242afc914f7b6c5fdf6617e64
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingFormat do
  @moduledoc "The format in which the embedding vectors are returned."

  @type t :: :float | :base64

  @float :float
  @base64 :base64

  @spec float() :: t()
  def float, do: @float
  @spec base64() :: t()
  def base64, do: @base64
end
