# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingFormat do
  @moduledoc "The format in which the embedding vectors are returned."

  @type t :: :float | :base64

  @float :float
  @base64 :base64

  @spec float() :: t()
  def float, do: @float
  @spec base64() :: t()
  def base64, do: @base64
end
