# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:39044fe127dc39ef86ed99868992406ea2dbaa1b61f18e14d1d11862920feb3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingRequest do
  @moduledoc false

  defstruct model: "",
            input: :single,
            encoding_format: nil,
            dimensions: nil,
            user: nil
end
