# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02d59881cc7a1d5c7a2294733d840caee9e08497298499ba6c6124ef92eb5040
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.FunctionCall do
  @moduledoc false

  defstruct name: "",
            arguments: ""
end
