# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.Image do
  @moduledoc "A single generated image, returned as either a URL or base64 data."

  defstruct url: "",
            b64_json: "",
            revised_prompt: ""
end
