# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba1a39a8cca2b797aa6814a9af3d2792bea08f53ee3362619a9cc37b2df8b93d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.LlmCacheConfig do
  @moduledoc "Response cache configuration."

  @typedoc "Response cache configuration."
  @type t :: %__MODULE__{
          max_entries: non_neg_integer() | nil,
          ttl_seconds: non_neg_integer() | nil,
          backend: String.t() | nil,
          backend_config: map() | nil
        }

  defstruct max_entries: nil,
            ttl_seconds: nil,
            backend: nil,
            backend_config: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
