# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61236f0b5d46a5fc9c4e17b862eba1d65ebf2e8eed118e2250a198c134fd42e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.Message do
  @moduledoc "A chat message in a conversation."

  @type t :: term()

  @type system :: %{type: :system, value_0: term()}
  @type user :: %{type: :user, value_0: term()}
  @type assistant :: %{type: :assistant, value_0: term()}
  @type tool :: %{type: :tool, value_0: term()}
  @type developer :: %{type: :developer, value_0: term()}
  @type function_variant :: %{type: :function, value_0: term()}
end
