# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f6bf4db40cc3f364685b555c0458fb50033e39bcf8a1473f8bc117b063f861c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ModerationCategories do
  @moduledoc "Boolean flags for each moderation category."

  defstruct sexual: false,
            hate: false,
            harassment: false,
            self_harm: false,
            sexual_minors: false,
            hate_threatening: false,
            violence_graphic: false,
            self_harm_intent: false,
            self_harm_instructions: false,
            harassment_threatening: false,
            violence: false
end
