# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5987adeba18cbe9089059f576a70d4c6b341c89f1e010d15a40c8c92498d2795
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ModelsListResponse do
  @moduledoc false

  defstruct object: "",
            data: []
end
