# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78b6a48e27150c02fcd4539561caeb3a0192fce6d2e136aeb780282bc4245724
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.ModelsListResponse do
  @moduledoc "Response listing available models."

  @typedoc "Response listing available models."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [LiterLlm.ModelObject.t()]
        }

  defstruct object: nil,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
