# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7142c30903125603a40b635579ef97c4f1f7d9dc5516afbb806648380ada71f9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.OcrRequest do
  @moduledoc "An OCR request."

  @typedoc "An OCR request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          document: LiterLlm.OcrDocument.t(),
          pages: [non_neg_integer()] | nil,
          include_image_base64: boolean() | nil
        }

  defstruct model: nil,
            document: :url,
            pages: nil,
            include_image_base64: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
