# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dd8cba51e339b252378edd1b049af1450d430f2835a1efa235954838d40f2f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.OcrImage do
  @moduledoc "An image extracted from an OCR page."

  defstruct id: "",
            image_base64: nil
end
