# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bac9e7506b799aeb25b1adb31c2729c78229a5cb833e54b1244f097efba11a28
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.PageDimensions do
  @moduledoc "Page dimensions in pixels."

  defstruct width: 0,
            height: 0
end
