# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8ee0a84d9d3d4e4dc59a8e53281aaca4d237c6a698155fb67ae545e4fbe4fea9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.RerankDocument do
  @moduledoc "A document to be reranked — either a plain string or an object with a text field."

  @type t :: term()

  @type text :: %{type: :text, value_0: term()}
  @type object :: %{type: :object, text: term()}
end
