# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76068a1c028bf6a61dd5230240f2b7d8cfc279ac1a9cfe23da1e7ec89c5c8069
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.SearchRequest do
  @moduledoc "A search request."

  defstruct model: "",
            query: "",
            max_results: 0,
            search_domain_filter: [],
            country: ""
end
