# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:18d62edc9e268316a09cecd6f73eb7b686fa667a363b5ae5760430ed53a9f189
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamChoice do
  @moduledoc false

  defstruct index: 0,
            delta: nil,
            finish_reason: :stop
end
