# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f381150bf2843b2ef8b41995a35e27e6df4feeb11b883143a95b66c5961ba2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamOptions do
  @moduledoc false

  defstruct include_usage: false
end
