# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a74c617718ebe3eb362b077bdbb3e18f276993a6ab4d33b614ecf5dcac50f14
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.StreamFunctionCall do
  @moduledoc "Partial function call details in a stream."

  @typedoc "Partial function call details in a stream."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          arguments: String.t() | nil
        }

  defstruct name: nil,
            arguments: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
