# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e97059b5d168c4e49f32675366d33eb3e1ab6175b08d58fc6becdac66f5eec63
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamDelta do
  @moduledoc false

  defstruct role: "",
            content: "",
            tool_calls: [],
            function_call: nil,
            refusal: ""
end
