# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f7080d07e992cd6410969f63e21e004b9650aba68bf6527d8735b280bc99b0e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamDelta do
  @moduledoc false

  defstruct role: "",
            content: "",
            tool_calls: [],
            function_call: nil,
            refusal: ""
end
