# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0b84fa7ece3234eacd0f8c078a40e005c218e9f99aad8f6ab2c3ac329374cb9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ToolType do
  @moduledoc "The type discriminator for tool/tool-call objects."

  @type t :: :function

  @function :function

  @spec function() :: t()
  def function, do: @function
end
