# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b541a797a91d035a9585938e87aba131c637b8f62f7291be7ebf9903d13b716b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc false

  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @spec auto() :: t()
  def auto, do: @auto
  @spec required() :: t()
  def required, do: @required
  @spec none() :: t()
  def none, do: @none
end
