# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc false

  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @spec auto() :: t()
  def auto, do: @auto
  @spec required() :: t()
  def required, do: @required
  @spec none() :: t()
  def none, do: @none
end
