# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d97b21c4d3b44c39f7ba06ec2484c92f75f713e291e11155b2e87e13a3eb50a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ToolChoice do
  @moduledoc false

  @type t :: term()

  @type mode :: %{type: :mode, value_0: term()}
  @type specific :: %{type: :specific, value_0: term()}
end
