# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:956f0ec5ab2e1b400aec0f06f7daeae5724802745d5ba73fbb2d3669df3d11b7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  @typedoc "A segment of transcribed audio with timing information."
  @type t :: %__MODULE__{
          id: non_neg_integer(),
          start: float(),
          end: float(),
          text: String.t() | nil
        }

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
