# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: ""
end
