# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de495a9836f390cc4ede3bd3736d5a579163fd362eeb1ad278f9bc275b70928c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.UserContent do
  @moduledoc false

  @type t :: term()

  @type text :: %{type: :text, value_0: term()}
  @type parts :: %{type: :parts, value_0: term()}
end
