# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce6b26277c5cd9ff16919edf4936ffbbd93d24bcd1b5dd4756b5b1edd50ca48d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.UserContent do
  @moduledoc false

  @type t :: term()

  @type text :: %{type: :text, value_0: term()}
  @type parts :: %{type: :parts, value_0: term()}
end
