// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6438728fd4f83bf50f8fd0f68582060c3652bf14bf23f4d9847a94a8439c855d
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;
using static LiterLlm.LiterLlmConverter;

namespace LiterLlm
{
    /// <summary>E2e tests for category: batches.</summary>
    public class BatchesTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_EdgeBatchAlreadyCancelled()
        {
            // Attempt to cancel an already-cancelled batch
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/edge_batch_already_cancelled";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var thrown = await Assert.ThrowsAnyAsync<LiterLlmException>(async () =>
            {
                await client.CancelBatchAsync("batch-cancelled001");
            });
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
            // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        }

        [Fact]
        public async Task Test_EdgeBatchEmptyList()
        {
            // List batches when no batches exist
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/edge_batch_empty_list";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.ListBatchesAsync(null);
            Assert.Empty(result.Data);

        }

        [Fact]
        public async Task Test_ErrorBatchAuth401()
        {
            // 401 Unauthorized when creating a batch with invalid API key
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/error_batch_auth_401";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var thrown = await Assert.ThrowsAnyAsync<LiterLlmException>(async () =>
            {
                await client.CreateBatchAsync(CreateBatchRequest.FromJson("{\"completion_window\":\"24h\",\"endpoint\":\"/v1/chat/completions\",\"input_file_id\":\"file-abc123\"}"));
            });
            // skipped: declared error variant 'Authentication' not yet preserved as a distinct identity by this backend's generator
            // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        }

        [Fact]
        public async Task Test_ErrorBatchInvalidFile()
        {
            // 400 Bad Request when creating a batch with invalid input file
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/error_batch_invalid_file";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var thrown = await Assert.ThrowsAnyAsync<LiterLlmException>(async () =>
            {
                await client.CreateBatchAsync(CreateBatchRequest.FromJson("{\"completion_window\":\"24h\",\"endpoint\":\"/v1/chat/completions\",\"input_file_id\":\"file-wrong-purpose\"}"));
            });
            // skipped: declared error variant 'BadRequest' not yet preserved as a distinct identity by this backend's generator
            // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        }

        [Fact]
        public async Task Test_ErrorBatchNotFound()
        {
            // 404 Not Found when retrieving a nonexistent batch
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/error_batch_not_found";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var thrown = await Assert.ThrowsAnyAsync<LiterLlmException>(async () =>
            {
                await client.RetrieveBatchAsync("batch-nonexistent");
            });
            // skipped: declared error variant 'NotFound' not yet preserved as a distinct identity by this backend's generator
            // skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
        }

        [Fact]
        public async Task Test_SmokeBatchCompleted()
        {
            // Retrieve a completed batch job with output file
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/smoke_batch_completed";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.RetrieveBatchAsync("batch-ghi789");
            Assert.True(((object?)result.Id) switch
            {
                null => false,
                string text => text.Length > 0,
                System.Collections.ICollection items => items.Count > 0,
                _ => true,
            }, "expected non-empty value");
            Assert.Equal("completed", result.Status == null ? null : System.Text.Json.JsonSerializer.Serialize(result.Status).Trim('"'));

        }

        [Fact]
        public async Task Test_SmokeCancelBatch()
        {
            // Cancel a running batch job
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/smoke_cancel_batch";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.CancelBatchAsync("batch-def456");
            Assert.True(((object?)result.Id) switch
            {
                null => false,
                string text => text.Length > 0,
                System.Collections.ICollection items => items.Count > 0,
                _ => true,
            }, "expected non-empty value");
            Assert.Equal("cancelling", result.Status == null ? null : System.Text.Json.JsonSerializer.Serialize(result.Status).Trim('"'));

        }

        [Fact]
        public async Task Test_SmokeCreateBatch()
        {
            // Create a new batch processing job
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/smoke_create_batch";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.CreateBatchAsync(CreateBatchRequest.FromJson("{\"completion_window\":\"24h\",\"endpoint\":\"/v1/chat/completions\",\"input_file_id\":\"file-abc123\"}"));
            Assert.True(((object?)result.Id) switch
            {
                null => false,
                string text => text.Length > 0,
                System.Collections.ICollection items => items.Count > 0,
                _ => true,
            }, "expected non-empty value");
            Assert.Equal("validating", result.Status == null ? null : System.Text.Json.JsonSerializer.Serialize(result.Status).Trim('"'));

        }

        [Fact]
        public async Task Test_SmokeListBatches()
        {
            // List all batch jobs
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/smoke_list_batches";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.ListBatchesAsync(null);
            Assert.Equal(2, result.Data.Count);

        }

        [Fact]
        public async Task Test_SmokeRetrieveBatch()
        {
            // Retrieve the status of a batch job
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/smoke_retrieve_batch";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.RetrieveBatchAsync("batch-abc123");
            Assert.True(((object?)result.Id) switch
            {
                null => false,
                string text => text.Length > 0,
                System.Collections.ICollection items => items.Count > 0,
                _ => true,
            }, "expected non-empty value");
            Assert.Equal("in_progress", result.Status == null ? null : System.Text.Json.JsonSerializer.Serialize(result.Status).Trim('"'));

        }


    }
}
