# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b8a978bf498772e4defbba7bc214e470a855255e5d22eb772bc89b8ccb16b88b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "liter_llm/version"
require_relative "liter_llm/native"

# Top-level namespace for the LiterLlm Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "liter_llm/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module LiterLlm
  # Re-export all types and functions from native extension
end

# Keep generated types under LiterLlm. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
