# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eec8c0a9430cc0a1a3568b0f9ab7f4a0a42cec90b05cc79a96b274c530c70c17
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: moderate."""

import os

import pytest
from liter_llm import create_client
from liter_llm._internal_bindings import ModerationRequest


@pytest.mark.asyncio

async def test_edge_moderate_all_categories() -> None:
    """Moderation response with multiple categories flagged."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_moderate_all_categories")
    req = ModerationRequest.from_json("{\"input\":\"Extremely harmful content targeting multiple categories\",\"model\":\"omni-moderation-latest\"}")

    result = await client.moderate(req)
    assert len(result.results) == 1
    assert result.results[0].flagged is True


@pytest.mark.asyncio

async def test_edge_moderate_empty_input() -> None:
    """Moderation with empty string input."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/edge_moderate_empty_input")
    req = ModerationRequest.from_json("{\"input\":\"\",\"model\":\"omni-moderation-latest\"}")

    result = await client.moderate(req)
    assert len(result.results) == 1
    assert result.results[0].flagged is False


@pytest.mark.asyncio

async def test_error_moderate_auth_401() -> None:
    """401 Unauthorized for moderation with invalid API key."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_moderate_auth_401")
        req = ModerationRequest.from_json("{\"input\":\"Hello\",\"model\":\"omni-moderation-latest\"}")
        await client.moderate(req)
    assert "Authentication" in str(exc_info.value) or "Authentication" in type(exc_info.value).__name__


@pytest.mark.asyncio

async def test_error_moderate_bad_request() -> None:
    """400 Bad Request for moderation with invalid model."""
    # skipped: assertion type 'equals' has no accessor for error field error.status_code in this backend
    with pytest.raises(Exception) as exc_info:  # noqa: B017
        client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/error_moderate_bad_request")
        req = ModerationRequest.from_json("{\"input\":\"Hello\",\"model\":\"nonexistent-moderation\"}")
        await client.moderate(req)
    assert "BadRequest" in str(exc_info.value) or "BadRequest" in type(exc_info.value).__name__


@pytest.mark.asyncio

async def test_smoke_moderate_batch() -> None:
    """Moderate multiple inputs in a single request."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_moderate_batch")
    req = ModerationRequest.from_json("{\"input\":[\"Hello world\",\"Nice weather today\"],\"model\":\"omni-moderation-latest\"}")

    result = await client.moderate(req)
    assert len(result.results) == 2
    assert result.results[0].flagged is False


@pytest.mark.asyncio

async def test_smoke_moderate_flagged() -> None:
    """Moderation detects flagged content."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_moderate_flagged")
    req = ModerationRequest.from_json("{\"input\":\"I want to hurt someone very badly\",\"model\":\"omni-moderation-latest\"}")

    result = await client.moderate(req)
    assert len(result.results) == 1
    assert result.results[0].flagged is True


@pytest.mark.asyncio

async def test_smoke_moderate_single() -> None:
    """Moderate a single non-flagged input."""
    client = create_client(api_key="test-key", base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/smoke_moderate_single")
    req = ModerationRequest.from_json("{\"input\":\"The weather is nice today.\",\"model\":\"omni-moderation-latest\"}")

    result = await client.moderate(req)
    assert len(result.results) == 1
    assert result.results[0].flagged is False
