// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.literllm;

import java.util.Map;
import java.util.Optional;

public record BudgetConfig(Optional<Double> globalLimit, Map<String, Double> modelLimits, Enforcement enforcement) {
}
