// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.literllm;

import java.util.Optional;

public record Choice(int index, AssistantMessage message, Optional<FinishReason> finishReason) {
}
