// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.literllm;

import java.util.Optional;

public record JsonSchemaFormat(String name, Optional<String> description, String schema, Optional<Boolean> strict) {
}
