// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public record ResponseObject(String id, String object, long createdAt, String model, String status,
		List<ResponseOutputItem> output, Optional<ResponseUsage> usage, Optional<String> error) {
}
