// DO NOT EDIT - auto-generated by skif
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public record StreamDelta(Optional<String> role, Optional<String> content, Optional<List<StreamToolCall>> toolCalls,
		Optional<StreamFunctionCall> functionCall, Optional<String> refusal) {
}
