// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record AssistantMessage(
    Optional<String> content,
    Optional<String> name,
    @JsonProperty("tool_calls") Optional<List<ToolCall>> toolCalls,
    Optional<String> refusal,
    /** Deprecated legacy function_call field; retained for API compatibility. */
    @JsonProperty("function_call") Optional<FunctionCall> functionCall
) {
    public static AssistantMessageBuilder builder() {
        return new AssistantMessageBuilder();
    }
}
