// DO NOT EDIT - auto-generated by alef
// alef:hash:d24d5528549156c139ea4e5c1b82d3f832588a004b601ddf63348331ffc1f0bd
package dev.kreuzberg.literllm;

public class BadRequestException extends LiterLlmErrorException {
    /** Creates a new BadRequestException with the given message. */
    public BadRequestException(final String message) {
        super(message);
    }

    /** Creates a new BadRequestException with the given message and cause. */
    public BadRequestException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
