// DO NOT EDIT - auto-generated by alef
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
package dev.kreuzberg.literllm;

public class ContextWindowExceededException extends LiterLlmErrorException {
    /** Creates a new ContextWindowExceededException with the given message. */
    public ContextWindowExceededException(final String message) {
        super(message);
    }

    /** Creates a new ContextWindowExceededException with the given message and cause. */
    public ContextWindowExceededException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
