// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a2388aa020f9f2deb6dae55a4c894f37006a66a085828090f2ccacadf2c02ae5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

/** Exception thrown when type conversion fails. */
public class ConversionErrorException extends LiterLlmRsException {
    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
