// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:832ade8c6b2429052926aa80d62aa774f6eaee6999d89108112b7d1d85bbac75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Request to create images from a text prompt.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateImageRequestBuilder.class)
public record CreateImageRequest(
    String prompt,
    @Nullable String model,
    @Nullable Integer n,
    @Nullable String size,
    @Nullable String quality,
    @Nullable String style,
    @Nullable @JsonProperty("response_format") String responseFormat,
    @Nullable String user
) {
    public static CreateImageRequestBuilder builder() {
        return new CreateImageRequestBuilder();
    }
}
