// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:213d1c0ff36fded4052ae51bd3a429029d283ca626797b803b18c54742bd454b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Request to generate speech audio from text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateSpeechRequestBuilder.class)
public record CreateSpeechRequest(
    String model,
    String input,
    String voice,
    @Nullable @JsonProperty("response_format") String responseFormat,
    @Nullable Double speed
) {
    public static CreateSpeechRequestBuilder builder() {
        return new CreateSpeechRequestBuilder();
    }
}
