// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:25ccead228e6f8dc3997595057655f6c00c00f009d9a33b865365e6f451dae2d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Configuration for registering a custom LLM provider at runtime.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record CustomProviderConfig(
    /** Unique name for this provider (e.g., "my-provider"). */
    String name,
    /** Base URL for the provider's API (e.g., "https://api.my-provider.com/v1"). */
    @JsonProperty("base_url") String baseUrl,
    /** Authentication header format. */
    @JsonProperty("auth_header") Object authHeader,
    /** Model name prefixes that route to this provider (e.g., ["my-"]). */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("model_prefixes") List<String> modelPrefixes
) {
}
