// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class DeveloperMessageBuilder {

    private String content = "";
    private Optional<String> name = Optional.empty();

    /** Sets the content field. */
    public DeveloperMessageBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the name field. */
    public DeveloperMessageBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Builds the DeveloperMessage instance. */
    public DeveloperMessage build() {
        return new DeveloperMessage(
            content,
            name
        );
    }
}
