// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2af69b5f3f5ce68bfd67365527be95814ba43db3afae95da2589bfd63c6bcaab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DeveloperMessage(String content, @Nullable String name) {
    public static DeveloperMessageBuilder builder() {
        return new DeveloperMessageBuilder();
    }
}
