// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class DeveloperMessageBuilder {

    private String content = "";
    private Optional<String> name = Optional.empty();

    /** Sets the content field. */
    public DeveloperMessageBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the name field. */
    public DeveloperMessageBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Builds the DeveloperMessage instance. */
    public DeveloperMessage build() {
        return new DeveloperMessage(
            content,
            name
        );
    }
}
