// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a60bb035380b79a49664caced11fe1acc4329c5db6ad33205c8a31855414b271
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;


public class DocumentContentBuilder {

    private String data = "";
    private String mediaType = "";

    /** Sets the data field. */
    public DocumentContentBuilder withData(final String value) {
        this.data = value;
        return this;
    }

    /** Sets the mediaType field. */
    public DocumentContentBuilder withMediaType(final String value) {
        this.mediaType = value;
        return this;
    }

    /** Builds the DocumentContent instance. */
    public DocumentContent build() {
        return new DocumentContent(
            data,
            mediaType
        );
    }
}
