// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:62906a1adfdb3ed5b962baaef891a207dba28c70585301c3d14dbbd570f0be3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbeddingRequest(
    String model,
    Object input,
    @Nullable @JsonProperty("encoding_format") EmbeddingFormat encodingFormat,
    @Nullable Integer dimensions,
    @Nullable String user
) {
}
