// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3e3f5c1e843da62758f0f02538bafe2893c9f4a3e08f9aa7aa60179ac4e5b6cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmbeddingRequest(
    String model,
    Object input,
    @JsonProperty("encoding_format") Optional<EmbeddingFormat> encodingFormat,
    Optional<Integer> dimensions,
    Optional<String> user
) {
}
