// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e89195170f2c7d52384074e90971a50a9e49390d375ddaba4f47325ac2ca5bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileListResponseBuilder.class)
public record FileListResponse(
    String object,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<FileObject> data,
    @Nullable @JsonProperty("has_more") Boolean hasMore
) {
    public static FileListResponseBuilder builder() {
        return new FileListResponseBuilder();
    }
}
