// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f07b9d0c5a3388fd688526634cfd40ad5fec501615920c58ad84caa9119b3b23
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Deprecated legacy function-role message body.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record FunctionMessage(String content, String name) {
    public static FunctionMessageBuilder builder() {
        return new FunctionMessageBuilder();
    }
}
