// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8767fa1ebd06e30ea1d20bdab2c9ddc2c0dcb9955c358a36341b5dbbed13b3d6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;

/**
 * Response containing generated images.
 */
public record ImagesResponse(long created, List<Image> data) {
    public static ImagesResponseBuilder builder() {
        return new ImagesResponseBuilder();
    }
}
