// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class ImageUrlBuilder {

    private String url = "";
    private Optional<ImageDetail> detail = Optional.empty();

    /** Sets the url field. */
    public ImageUrlBuilder withUrl(final String value) {
        this.url = value;
        return this;
    }

    /** Sets the detail field. */
    public ImageUrlBuilder withDetail(final Optional<ImageDetail> value) {
        this.detail = value;
        return this;
    }

    /** Builds the ImageUrl instance. */
    public ImageUrl build() {
        return new ImageUrl(
            url,
            detail
        );
    }
}
