// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5b8880d281bdf17dd3d40f1ae6e3efa03123e404a3824edf0f2f4a36b5d2edd4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class ImageUrlBuilder {

    private String url = "";
    private Optional<ImageDetail> detail = Optional.empty();

    /** Sets the url field. */
    public ImageUrlBuilder withUrl(final String value) {
        this.url = value;
        return this;
    }

    /** Sets the detail field. */
    public ImageUrlBuilder withDetail(final Optional<ImageDetail> value) {
        this.detail = value;
        return this;
    }

    /** Builds the ImageUrl instance. */
    public ImageUrl build() {
        return new ImageUrl(
            url,
            detail.orElse(null)
        );
    }
}
