// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class JsonSchemaFormatBuilder {

    private String name = "";
    private Optional<String> description = Optional.empty();
    private Object schema = null;
    private Optional<Boolean> strict = Optional.empty();

    /** Sets the name field. */
    public JsonSchemaFormatBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Sets the description field. */
    public JsonSchemaFormatBuilder withDescription(final Optional<String> value) {
        this.description = value;
        return this;
    }

    /** Sets the schema field. */
    public JsonSchemaFormatBuilder withSchema(final Object value) {
        this.schema = value;
        return this;
    }

    /** Sets the strict field. */
    public JsonSchemaFormatBuilder withStrict(final Optional<Boolean> value) {
        this.strict = value;
        return this;
    }

    /** Builds the JsonSchemaFormat instance. */
    public JsonSchemaFormat build() {
        return new JsonSchemaFormat(
            name,
            description,
            schema,
            strict
        );
    }
}
