// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c368129195c2d5f593a66af95a54dbb78cd9fd03dae9650f70449d081d149fcd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public record JsonSchemaFormat(
    String name,
    Optional<String> description,
    Object schema,
    Optional<Boolean> strict
) {
    public static JsonSchemaFormatBuilder builder() {
        return new JsonSchemaFormatBuilder();
    }
}
