// DO NOT EDIT - auto-generated by alef
// alef:hash:c2f6bf5db22c3649438bbee8af55cd301db6b9ef92159674d2267a3b289d4548
package dev.kreuzberg.literllm;

/**
 * All errors that can occur when using {@code liter-llm}.
 */
public class LiterLlmErrorException extends Exception {
    /** Creates a new LiterLlmErrorException with the given message. */
    public LiterLlmErrorException(final String message) {
        super(message);
    }

    /** Creates a new LiterLlmErrorException with the given message and cause. */
    public LiterLlmErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
