// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c18ee9fb95619fc89d7409d7d33654bcd11201772bec1f20d2f0e3d466a1627
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Boolean flags for each moderation category.
 */
public record ModerationCategories(
    boolean sexual,
    boolean hate,
    boolean harassment,
    @JsonProperty("self_harm") boolean selfHarm,
    @JsonProperty("sexual_minors") boolean sexualMinors,
    @JsonProperty("hate_threatening") boolean hateThreatening,
    @JsonProperty("violence_graphic") boolean violenceGraphic,
    @JsonProperty("self_harm_intent") boolean selfHarmIntent,
    @JsonProperty("self_harm_instructions") boolean selfHarmInstructions,
    @JsonProperty("harassment_threatening") boolean harassmentThreatening,
    boolean violence
) {
}
