// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:caf7b684be2bf092e29166972d5ecb30d131bff21860bd37fdeae5525b3cc81c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Boolean flags for each moderation category.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ModerationCategories(
    boolean sexual,
    boolean hate,
    boolean harassment,
    @JsonProperty("self_harm") boolean selfHarm,
    @JsonProperty("sexual_minors") boolean sexualMinors,
    @JsonProperty("hate_threatening") boolean hateThreatening,
    @JsonProperty("violence_graphic") boolean violenceGraphic,
    @JsonProperty("self_harm_intent") boolean selfHarmIntent,
    @JsonProperty("self_harm_instructions") boolean selfHarmInstructions,
    @JsonProperty("harassment_threatening") boolean harassmentThreatening,
    boolean violence
) {
}
