// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.List;

public class ModelsListResponseBuilder {

    private String object = "";
    private List<ModelObject> data = List.of();

    /** Sets the object field. */
    public ModelsListResponseBuilder withObject(final String value) {
        this.object = value;
        return this;
    }

    /** Sets the data field. */
    public ModelsListResponseBuilder withData(final List<ModelObject> value) {
        this.data = value;
        return this;
    }

    /** Builds the ModelsListResponse instance. */
    public ModelsListResponse build() {
        return new ModelsListResponse(
            object,
            data
        );
    }
}
