// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf3eb46439d55b6e42ed226b929611d6c6270afeffc32ccdfe721ed40a80debe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;

/**
 * Response from the moderation endpoint.
 */
public record ModerationResponse(String id, String model, List<ModerationResult> results) {
}
