// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7327fb9fe7d64cf41702a7511aa46d49558644f82cd59fc0de201435740cc0f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Confidence scores for each moderation category.
 */
public record ModerationCategoryScores(
    double sexual,
    double hate,
    double harassment,
    @JsonProperty("self_harm") double selfHarm,
    @JsonProperty("sexual_minors") double sexualMinors,
    @JsonProperty("hate_threatening") double hateThreatening,
    @JsonProperty("violence_graphic") double violenceGraphic,
    @JsonProperty("self_harm_intent") double selfHarmIntent,
    @JsonProperty("self_harm_instructions") double selfHarmInstructions,
    @JsonProperty("harassment_threatening") double harassmentThreatening,
    double violence
) {
}
