// DO NOT EDIT - auto-generated by alef
// alef:hash:702ff265cc50512e69155e583d3e9e70cd7b638f42fc34f189ed23239914de09
package dev.kreuzberg.literllm;

public class NotFoundException extends LiterLlmErrorException {
    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
