// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2c59ab44cc1a14cbd9f41d283283ab8e2a76f9cf05061532b39e643369bc6969
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

/**
 * An image extracted from an OCR page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrImage(String id, @Nullable @JsonProperty("image_base64") String imageBase64) {
}
