// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0feb335a6192eee50fef97be7d958b71be8d6f5a6c2b637f2f078e4eb3e67dbe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An image extracted from an OCR page.
 */
public record OcrImage(String id, @JsonProperty("image_base64") Optional<String> imageBase64) {
}
