// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff874e373ea2126865a26852517bdc274fc7d95afaffdc91d0aa78a9689532c4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * An image extracted from an OCR page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrImage(String id, @Nullable @JsonProperty("image_base64") String imageBase64) {
}
