// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a131c012fa44a26cd2fa3ad15747a3058c726ab94682ca27ddfe7ac3afd075f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

/**
 * A single page of OCR output.
 */
public record OcrPage(
    /** Page index (0-based). */
    int index,
    /** Extracted content as Markdown. */
    String markdown,
    /** Extracted images, if {@code include_image_base64} was set. */
    Optional<List<OcrImage>> images,
    /** Page dimensions in pixels, if available. */
    Optional<PageDimensions> dimensions
) {
}
