// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4225018b5d3f4cdf30d966edd314e8c8b33adfbb1019d8fdf86ca9b4bbe5659
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An OCR request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrRequest(
    /** The model/provider to use (e.g. {@code "mistral/mistral-ocr-latest"}). */
    String model,
    /** The document to process. */
    OcrDocument document,
    /** Specific pages to process (1-indexed). {@code None} means all pages. */
    Optional<List<Integer>> pages,
    /** Whether to include base64-encoded images of each page. */
    @JsonProperty("include_image_base64") Optional<Boolean> includeImageBase64
) {
}
