// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An OCR request.
 */
public record OcrRequest(
    /** The model/provider to use (e.g. {@code "mistral/mistral-ocr-latest"}). */
    String model,
    /** The document to process. */
    OcrDocument document,
    /** Specific pages to process (1-indexed). {@code None} means all pages. */
    Optional<List<Integer>> pages,
    /** Whether to include base64-encoded images of each page. */
    @JsonProperty("include_image_base64") Optional<Boolean> includeImageBase64
) {
}
