// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54f2fa3f2b1282456d968c8832c290f1c469c44d06dc03bdf32dd6df4966db88
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Breakdown of tokens used in the prompt portion of a request.
 *
 * {@code cached_tokens} is included in {@code Usage::prompt_tokens} — it is *not* an
 * additional charge on top of the prompt token count. When pricing supports
 * a {@code cache_read_input_token_cost}, the cached portion is billed at the
 * discounted rate and the remainder at the regular input rate.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PromptTokensDetailsBuilder.class)
public record PromptTokensDetails(
    /** Cached tokens present in the prompt. Defaults to 0 when absent. */
    @JsonProperty("cached_tokens") long cachedTokens,
    /** Audio input tokens present in the prompt. Defaults to 0 when absent. */
    @JsonProperty("audio_tokens") long audioTokens
) {
    public static PromptTokensDetailsBuilder builder() {
        return new PromptTokensDetailsBuilder();
    }
}
