// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:404d8b7c7e0995322fa3a3791ea4399af44aad3bfbf877cc070c4747b403433a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;


/**
 * The text content of a reranked document, returned when {@code return_documents} is true.
 */
public record RerankResultDocument(String text) {
}
