// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single reranked document with its relevance score.
 */
public record RerankResult(
    int index,
    @JsonProperty("relevance_score") double relevanceScore,
    Optional<RerankResultDocument> document
) {
}
