// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:db325bf1e68579144f3ab41e7dce9ffefe13e271a6e0a376e10bfba238c8f974
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single reranked document with its relevance score.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record RerankResult(
    int index,
    @JsonProperty("relevance_score") double relevanceScore,
    Optional<RerankResultDocument> document
) {
}
