// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request to rerank documents by relevance to a query.
 */
public record RerankRequest(
    String model,
    String query,
    List<RerankDocument> documents,
    @JsonProperty("top_n") Optional<Integer> topN,
    @JsonProperty("return_documents") Optional<Boolean> returnDocuments
) {
}
