// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:826d8e388af24d5e75128a511f07c05d750edc242285d2a113db9701def1cf8c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResponseUsageBuilder.class)
public record ResponseUsage(
    @JsonProperty("input_tokens") long inputTokens,
    @JsonProperty("output_tokens") long outputTokens,
    @JsonProperty("total_tokens") long totalTokens
) {
    public static ResponseUsageBuilder builder() {
        return new ResponseUsageBuilder();
    }
}
