// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a568d8b4cc115a5a87d8f15018562c164777e92681bd9759e99360eed074565
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResponseObjectBuilder.class)
public record ResponseObject(
    String id,
    String object,
    @JsonProperty("created_at") long createdAt,
    String model,
    String status,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<ResponseOutputItem> output,
    @Nullable ResponseUsage usage,
    @Nullable Object error
) {
    public static ResponseObjectBuilder builder() {
        return new ResponseObjectBuilder();
    }
}
