// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2036fdc8dfcfd2e3b0bbfe63b3a6bd704de06e29195f1c2aeef7090bac7faea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * An individual search result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SearchResult(String title, String url, String snippet, @Nullable String date) {
}
