// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:06abc40ac782d32e6f72b407530ce27a662130ca3b1564a11353fbcaed320567
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

/**
 * An individual search result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SearchResult(String title, String url, String snippet, @Nullable String date) {
}
