// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79f5710ddc668b0fa6652c6c43dcbe802bf1ccded0d5d61aea5fd09405570897
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A search response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SearchResponse(
    /** The search results. */
    @JsonInclude(JsonInclude.Include.NON_NULL) List<SearchResult> results,
    /** The model used. */
    String model
) {
}
