// DO NOT EDIT - auto-generated by alef
// alef:hash:2d4bf76462bea801b3b9ed38853be235a1c30948687ef9450925e376ee4fa9cd
package dev.kreuzberg.literllm;

public class SerializationException extends LiterLlmErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
