// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:49f1bd15ff4b07ff5f57c58e4967e12c9f0ef780f0a931ece1fd32394433d286
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class SpecificFunctionBuilder {

    private String name = "";

    /** Sets the name field. */
    public SpecificFunctionBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Builds the SpecificFunction instance. */
    public SpecificFunction build() {
        return new SpecificFunction(
            name
        );
    }
}
