// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record SpecificToolChoice(
    @JsonProperty("choice_type") ToolType choiceType,
    SpecificFunction function
) {
    public static SpecificToolChoiceBuilder builder() {
        return new SpecificToolChoiceBuilder();
    }
}
