// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:869fae848072b844ea56d72ef40bec563c789b12f6ad89dc69895aa2e70bf434
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public record StreamFunctionCall(Optional<String> name, Optional<String> arguments) {
    public static StreamFunctionCallBuilder builder() {
        return new StreamFunctionCallBuilder();
    }
}
