// DO NOT EDIT - auto-generated by alef
// alef:hash:0675b166f797c7e7e5e3edce7b22ff29370317b729c7b24b7702e99602fde4e0
package dev.kreuzberg.literllm;

/**
 * A catch-all for errors that occur during streaming response processing.
 *
 * This variant covers multiple sub-conditions including UTF-8 decoding
 * failures, CRC/checksum mismatches (AWS EventStream), JSON parse errors
 * in individual SSE chunks, and buffer overflow conditions.  The {@code message}
 * field contains a human-readable description of the specific failure.
 */
public class StreamingException extends LiterLlmErrorException {
    /** Creates a new StreamingException with the given message. */
    public StreamingException(final String message) {
        super(message);
    }

    /** Creates a new StreamingException with the given message and cause. */
    public StreamingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
