// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f7109946f8bf3cebbae683f6ee3c8cdbfe2233ee3e7ecb13bbcdb5345459fa2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public record StreamFunctionCall(Optional<String> name, Optional<String> arguments) {
    public static StreamFunctionCallBuilder builder() {
        return new StreamFunctionCallBuilder();
    }
}
