// DO NOT EDIT - auto-generated by alef
// alef:hash:07c0c89eb39244faf12e124d64610e2a7e508fcc79510bf8a0f22b6cb56d86e6
package dev.kreuzberg.literllm;

public class TimeoutException extends LiterLlmErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
