// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7da53ae1f4866a3b23f0b46d8dbfbd5d364893468bd5db93b89dd5a9df5a882a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ToolCall(
    String id,
    @JsonProperty("call_type") ToolType callType,
    FunctionCall function
) {
}
