// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77ff37c68027afd94e35f35ca30c1312d733c378073d3826d749a5f9575b1ff2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A segment of transcribed audio with timing information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TranscriptionSegment(int id, double start, double end, String text) {
    public static TranscriptionSegmentBuilder builder() {
        return new TranscriptionSegmentBuilder();
    }
}
