// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b650d348280825a60670029e9d8fbb6f39b862e6d9eaecbcf59743b504a098d4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

/**
 * Response from a transcription request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TranscriptionResponse(
    String text,
    @Nullable String language,
    @Nullable Double duration,
    @Nullable List<TranscriptionSegment> segments
) {
    public static TranscriptionResponseBuilder builder() {
        return new TranscriptionResponseBuilder();
    }
}
