// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;


/**
 * A segment of transcribed audio with timing information.
 */
public class TranscriptionSegmentBuilder {

    private int id = 0;
    private double start = 0.0;
    private double end = 0.0;
    private String text = "";

    /** Sets the id field. */
    public TranscriptionSegmentBuilder withId(final int value) {
        this.id = value;
        return this;
    }

    /** Sets the start field. */
    public TranscriptionSegmentBuilder withStart(final double value) {
        this.start = value;
        return this;
    }

    /** Sets the end field. */
    public TranscriptionSegmentBuilder withEnd(final double value) {
        this.end = value;
        return this;
    }

    /** Sets the text field. */
    public TranscriptionSegmentBuilder withText(final String value) {
        this.text = value;
        return this;
    }

    /** Builds the TranscriptionSegment instance. */
    public TranscriptionSegment build() {
        return new TranscriptionSegment(
            id,
            start,
            end,
            text
        );
    }
}
