// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9248f0d025732a538304be7b6c8896dc1774e896a67eeb8f11affd057da5f3ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record Usage(
    /** Prompt tokens used. Defaults to 0 when absent (some providers omit this). */
    @JsonProperty("prompt_tokens") long promptTokens,
    /** Completion tokens used. Defaults to 0 when absent (e.g. embedding responses). */
    @JsonProperty("completion_tokens") long completionTokens,
    /** Total tokens used. Defaults to 0 when absent (some providers omit this). */
    @JsonProperty("total_tokens") long totalTokens,
    /** Breakdown of tokens used in the prompt, including cached tokens served */
    @JsonProperty("prompt_tokens_details") Optional<PromptTokensDetails> promptTokensDetails
) {
    public static UsageBuilder builder() {
        return new UsageBuilder();
    }
}
