// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ca6f4b888069a406252a052c42e873e6953e2936d74dac9c88b2400aacc4de4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;


public class UsageBuilder {

    private long promptTokens = 0;
    private long completionTokens = 0;
    private long totalTokens = 0;

    /** Sets the promptTokens field. */
    public UsageBuilder withPromptTokens(final long value) {
        this.promptTokens = value;
        return this;
    }

    /** Sets the completionTokens field. */
    public UsageBuilder withCompletionTokens(final long value) {
        this.completionTokens = value;
        return this;
    }

    /** Sets the totalTokens field. */
    public UsageBuilder withTotalTokens(final long value) {
        this.totalTokens = value;
        return this;
    }

    /** Builds the Usage instance. */
    public Usage build() {
        return new Usage(
            promptTokens,
            completionTokens,
            totalTokens
        );
    }
}
