// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da35a7759be6bd6ceee25b2d2a47d3afc833fdde4987a0a9446010208e951479
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public class UserMessageBuilder {

    private UserContent content = null;
    private Optional<String> name = Optional.empty();

    /** Sets the content field. */
    public UserMessageBuilder withContent(final UserContent value) {
        this.content = value;
        return this;
    }

    /** Sets the name field. */
    public UserMessageBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Builds the UserMessage instance. */
    public UserMessage build() {
        return new UserMessage(
            content,
            name
        );
    }
}
