// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public record UserMessage(Object content, Optional<String> name) {
    public static UserMessageBuilder builder() {
        return new UserMessageBuilder();
    }
}
