// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLlmE2E;

public sealed class RerankTests
{

    /// <summary>Reranking with an empty query string</summary>
    [Fact]
    public async Task EdgeRerankEmptyQuery()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 200,
                Body: "{\"id\":\"rerank-empty001\",\"meta\":{\"api_version\":{\"version\":\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"index\":0,\"relevance_score\":0.5},{\"index\":1,\"relevance_score\":0.48}]}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>Reranking with only a single document</summary>
    [Fact]
    public async Task EdgeRerankSingleDoc()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 200,
                Body: "{\"id\":\"rerank-single001\",\"meta\":{\"api_version\":{\"version\":\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"index\":0,\"relevance_score\":0.98}]}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>401 Unauthorized for reranking with invalid API key</summary>
    [Fact]
    public async Task ErrorRerankAuth401()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 401,
                Body: "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>400 Bad Request for reranking with invalid model</summary>
    [Fact]
    public async Task ErrorRerankBadRequest()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 400,
                Body: "{\"error\":{\"code\":\"model_not_found\",\"message\":\"The model 'nonexistent-rerank' does not exist.\",\"param\":\"model\",\"type\":\"invalid_request_error\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>Basic reranking of documents against a query</summary>
    [Fact]
    public async Task SmokeRerankBasic()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 200,
                Body: "{\"id\":\"rerank-abc123\",\"meta\":{\"api_version\":{\"version\":\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"index\":0,\"relevance_score\":0.95},{\"index\":2,\"relevance_score\":0.82},{\"index\":1,\"relevance_score\":0.05}]}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>Reranking with return_documents flag to include document text</summary>
    [Fact]
    public async Task SmokeRerankReturnDocs()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 200,
                Body: "{\"id\":\"rerank-ghi789\",\"meta\":{\"api_version\":{\"version\":\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"document\":{\"text\":\"Rust is a systems programming language.\"},\"index\":0,\"relevance_score\":0.96},{\"document\":{\"text\":\"Iron rusts when exposed to water.\"},\"index\":1,\"relevance_score\":0.12}]}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }

    /// <summary>Reranking with top_n parameter to limit results</summary>
    [Fact]
    public async Task SmokeRerankWithTopN()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/rerank",
                Method: "POST",
                Status: 200,
                Body: "{\"id\":\"rerank-def456\",\"meta\":{\"api_version\":{\"version\":\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"index\":0,\"relevance_score\":0.97},{\"index\":2,\"relevance_score\":0.91}]}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        // TODO: unknown method "rerank"
    }
}
