// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import liter_llm

// Tests that identical chat requests return cached response
pub fn cache_hit_test() {
  let result = liter_llm.chat(Nil)
  result |> should.be_ok()
  result.cache_hit |> should.equal(True)
}

// Tests that cache expires after TTL
pub fn cache_miss_ttl_test() {
  let result = liter_llm.chat(Nil)
  result |> should.be_ok()
  result.cache_hit |> should.equal(True)
}

// Cache hit with OpenDAL memory backend returns cached response on repeat request
pub fn cache_opendal_memory_test() {
  let result = liter_llm.chat(Nil)
  result |> should.be_ok()
  result.cache_hit |> should.equal(True)
}

// Tests that streaming requests bypass cache entirely
pub fn cache_stream_bypass_test() {
  let result = liter_llm.chat_stream(Nil)
  result |> should.be_ok()
  result.cache_bypassed |> should.equal(True)
}

