// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import liter_llm

import gleam/list

// Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
pub fn binding_api_parity_test() {
  let result = liter_llm.chat(Nil)
  result |> should.be_ok()
  result.choices |> list.length |> should.equal(1)
  result.choices.get("0").message.content |> should.equal("OK")
  result.choices.get("0").finish_reason |> should.equal("stop")
  result.usage.total_tokens |> should.equal(6)
  result.model |> should.equal("gpt-4o")
}

// Verify ocr() method exists in all bindings
pub fn contract_ocr_test() {
  let result = liter_llm.ocr(Nil)
  result |> should.be_ok()
}

// Verify search() method exists in all bindings
pub fn contract_search_test() {
  let result = liter_llm.search(Nil)
  result |> should.be_ok()
}

