// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b933fef6af51509ce4804d5576f12d7508bf24244df4736ad2aac8aaa3041b2a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { createClient, type WasmChatCompletionRequest, initSync } from "liter_llm";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const wasmPath = path.join(
  path.dirname(__filename),
  "../node_modules/liter_llm/liter_llm_wasm_bg.wasm",
);
const wasmBuffer = fs.readFileSync(wasmPath);
initSync({ module: wasmBuffer });

function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("rerank", () => {
  it("edge_rerank_empty_query: Reranking with an empty query string", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/edge_rerank_empty_query`,
    );
    const result = await client.rerank({
      documents: ["Some document", "Another document"],
      model: "rerank-v3.5",
      query: "",
    } as WasmChatCompletionRequest);
    expect(result.results.length).toBe(2);
  });

  it("edge_rerank_single_doc: Reranking with only a single document", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/edge_rerank_single_doc`,
    );
    const result = await client.rerank({
      documents: ["Artificial intelligence is the simulation of human intelligence."],
      model: "rerank-v3.5",
      query: "What is AI?",
    } as WasmChatCompletionRequest);
    expect(result.results.length).toBe(1);
    expect(result.results["0"].relevanceScore).toBeGreaterThan(0.9);
  });

  it("error_rerank_auth_401: 401 Unauthorized for reranking with invalid API key", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/error_rerank_auth_401`,
    );
    await expect(async () => {
      await client.rerank({
        documents: ["doc1"],
        model: "rerank-v3.5",
        query: "test",
      } as WasmChatCompletionRequest);
    }).rejects.toThrow();
  });

  it("error_rerank_bad_request: 400 Bad Request for reranking with invalid model", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/error_rerank_bad_request`,
    );
    await expect(async () => {
      await client.rerank({
        documents: ["doc1"],
        model: "nonexistent-rerank",
        query: "test",
      } as WasmChatCompletionRequest);
    }).rejects.toThrow();
  });

  it("smoke_rerank_basic: Basic reranking of documents against a query", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_rerank_basic`,
    );
    const result = await client.rerank({
      documents: [
        "Machine learning is a subset of AI.",
        "The weather is sunny today.",
        "Deep learning uses neural networks.",
      ],
      model: "rerank-v3.5",
      query: "What is machine learning?",
    } as WasmChatCompletionRequest);
    expect(result.results.length).toBe(3);
    expect(result.results["0"].relevanceScore).toBeGreaterThan(0.9);
  });

  it("smoke_rerank_return_docs: Reranking with return_documents flag to include document text", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_rerank_return_docs`,
    );
    const result = await client.rerank({
      documents: ["Rust is a systems programming language.", "Iron rusts when exposed to water."],
      model: "rerank-v3.5",
      query: "What is Rust?",
      returnDocuments: true,
    } as WasmChatCompletionRequest);
    expect(result.results.length).toBe(2);
    expect((result.results["0"].document ?? "").length).toBeGreaterThan(0);
    expect(result.results["0"].relevanceScore).toBeGreaterThan(0.9);
  });

  it("smoke_rerank_with_top_n: Reranking with top_n parameter to limit results", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_rerank_with_top_n`,
    );
    const result = await client.rerank({
      documents: [
        "Python is a programming language.",
        "Cats are cute animals.",
        "Python was created by Guido van Rossum.",
        "The sun is a star.",
      ],
      model: "rerank-v3.5",
      query: "What is Python?",
      topN: 2,
    } as WasmChatCompletionRequest);
    expect(result.results.length).toBe(2);
    expect(result.results["0"].relevanceScore).toBeGreaterThan(0.9);
  });
});
