# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require 'spec_helper'

RSpec.describe 'batches' do
  it 'edge_batch_already_cancelled' do
    # Attempt to cancel an already-cancelled batch
    route = E2EHelpers::MockRoute.new(
      path: '/batches/batch-placeholder',
      method: 'POST',
      status: 400,
      body: "{\"error\":{\"code\":null,\"message\":\"Batch batch-cancelled001 is already in terminal state 'cancelled' and cannot be cancelled.\",\"param\":null,\"type\":\"invalid_request_error\"}}",
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "cancel_batch"
  ensure
    server&.stop
  end

  it 'edge_batch_empty_list' do
    # List batches when no batches exist
    route = E2EHelpers::MockRoute.new(
      path: '/batches',
      method: 'GET',
      status: 200,
      body: '{"data":[],"has_more":false,"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "list_batches"
  ensure
    server&.stop
  end

  it 'error_batch_auth_401' do
    # 401 Unauthorized when creating a batch with invalid API key
    route = E2EHelpers::MockRoute.new(
      path: '/batches',
      method: 'POST',
      status: 401,
      body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_batch"
  ensure
    server&.stop
  end

  it 'error_batch_invalid_file' do
    # 400 Bad Request when creating a batch with invalid input file
    route = E2EHelpers::MockRoute.new(
      path: '/batches',
      method: 'POST',
      status: 400,
      body: "{\"error\":{\"code\":null,\"message\":\"The file 'file-wrong-purpose' has purpose 'fine-tune', but batch requires 'batch'.\",\"param\":\"input_file_id\",\"type\":\"invalid_request_error\"}}",
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_batch"
  ensure
    server&.stop
  end

  it 'error_batch_not_found' do
    # 404 Not Found when retrieving a nonexistent batch
    route = E2EHelpers::MockRoute.new(
      path: '/batches/batch-placeholder',
      method: 'GET',
      status: 404,
      body: '{"error":{"code":null,"message":"No such Batch object: batch-nonexistent","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "retrieve_batch"
  ensure
    server&.stop
  end

  it 'smoke_batch_completed' do
    # Retrieve a completed batch job with output file
    route = E2EHelpers::MockRoute.new(
      path: '/batches/batch-placeholder',
      method: 'GET',
      status: 200,
      body: '{"completed_at":1711003600,"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-ghi789","in_progress_at":1711000100,"input_file_id":"file-input001","object":"batch","output_file_id":"file-output001","request_counts":{"completed":98,"failed":2,"total":100},"status":"completed"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "retrieve_batch"
  ensure
    server&.stop
  end

  it 'smoke_cancel_batch' do
    # Cancel a running batch job
    route = E2EHelpers::MockRoute.new(
      path: '/batches/batch-placeholder',
      method: 'POST',
      status: 200,
      body: '{"cancelling_at":1711000400,"created_at":1711000200,"endpoint":"/v1/chat/completions","id":"batch-def456","object":"batch","request_counts":{"completed":30,"failed":0,"total":100},"status":"cancelling"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "cancel_batch"
  ensure
    server&.stop
  end

  it 'smoke_create_batch' do
    # Create a new batch processing job
    route = E2EHelpers::MockRoute.new(
      path: '/batches',
      method: 'POST',
      status: 200,
      body: '{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","input_file_id":"file-abc123","object":"batch","request_counts":{"completed":0,"failed":0,"total":0},"status":"validating"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_batch"
  ensure
    server&.stop
  end

  it 'smoke_list_batches' do
    # List all batch jobs
    route = E2EHelpers::MockRoute.new(
      path: '/batches',
      method: 'GET',
      status: 200,
      body: '{"data":[{"created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","object":"batch","status":"completed"},{"created_at":1711000200,"endpoint":"/v1/embeddings","id":"batch-def456","object":"batch","status":"in_progress"}],"has_more":false,"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "list_batches"
  ensure
    server&.stop
  end

  it 'smoke_retrieve_batch' do
    # Retrieve the status of a batch job
    route = E2EHelpers::MockRoute.new(
      path: '/batches/batch-placeholder',
      method: 'GET',
      status: 200,
      body: '{"completion_window":"24h","created_at":1711000000,"endpoint":"/v1/chat/completions","id":"batch-abc123","in_progress_at":1711000100,"input_file_id":"file-abc123","object":"batch","request_counts":{"completed":45,"failed":2,"total":100},"status":"in_progress"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "retrieve_batch"
  ensure
    server&.stop
  end
end
