# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1a5015b45ef142a1877e75d62ef3f90bb3bd9bf86f59fe4a3f8a09858986fd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'cache' do
  it 'cache_hit: Tests that identical chat requests return cached response' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/cache_hit')
    result = client.chat(nil)
    expect(result.cache_hit).to be true
  end

  it 'cache_miss_ttl: Tests that cache expires after TTL' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/cache_miss_ttl')
    result = client.chat(nil)
    expect(result.cache_hit).to be true
  end

  it 'cache_opendal_memory: Cache hit with OpenDAL memory backend returns cached response on repeat request' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/cache_opendal_memory')
    result = client.chat(nil)
    expect(result.cache_hit).to be true
  end

  it 'cache_stream_bypass: Tests that streaming requests bypass cache entirely' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/cache_stream_bypass')
    result = client.chat_stream(nil)
    expect(result.cache_bypassed).to be true
  end
end
