# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65399dcccdff73e137b2f8145f52d51a27b897caa3e3f34e29ef924cf6c9cc45
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'contract' do
  it 'binding_api_parity: Verify all bindings expose the full API surface — constructor accepts all config options and every method exists' do
    result = LiterLlm.chat(nil)
    expect(result.choices.length).to eq(1)
    expect(result.choices.get("0").message.content).to eq('OK')
    expect(result.choices.get("0").finish_reason).to eq('stop')
    expect(result.usage.total_tokens).to eq(6)
    expect(result.model).to eq('gpt-4o')
  end

  it 'contract_ocr: Verify ocr() method exists in all bindings' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end

  it 'contract_search: Verify search() method exists in all bindings' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end
end
