# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8798a2498d8709a83c3ae092e2dc4aa2782f410b5582f5b55325f81b2e30a67
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'embed' do
  it 'batch_embed: Embedding request with multiple input strings returns one embedding object per input' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/batch_embed')
    result = client.embed(['Hello', 'World'])
    expect(result.data.length).to eq(2)
    expect(result.data.get("0").embedding.length).to eq(5)
  end

  it 'edge_embed_batch_input: Embedding request with multiple inputs returns multiple embedding objects' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_embed_batch_input')
    result = client.embed(['Hello world', 'Goodbye world'])
    expect(result.data.length).to eq(2)
    expect(result.data.get("0").index).to eq(0)
    expect(result.data.get("1").index).to eq(1)
  end

  it 'edge_embed_empty_input: Embedding request with empty string input returns empty data array' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/edge_embed_empty_input')
    result = client.embed('')
    expect(result.data.length).to eq(0)
  end

  it 'embed_encoding_format: Embedding request with explicit encoding_format of float returns float array embeddings' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/embed_encoding_format')
    result = client.embed('Test input')
    expect(result.data.length).to eq(1)
    expect(result.data.get("0").embedding.length).to eq(5)
  end

  it 'embed_error_401: 401 Unauthorized error on embedding request when API key is invalid' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/embed_error_401')
    expect { client.embed('Hello world') }.to raise_error
  end

  it 'embed_with_dimensions: Embedding request with explicit dimensions parameter returns embeddings of the requested size' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/embed_with_dimensions')
    result = client.embed('Hello world')
    expect(result.data.length).to eq(1)
    expect(result.data.get("0").embedding.length).to eq(8)
  end

  it 'local_embed_ollama: Embedding request via Ollama local provider with all-minilm model' do
    client = LiterLlm.create_client('test-key', ENV.fetch('MOCK_SERVER_URL') + '/fixtures/local_embed_ollama')
    result = client.embed('The quick brown fox jumps over the lazy dog')
    expect(result.data.length).to eq(1)
    expect(result.data.get("0").embedding.length).to eq(32)
  end
end
