# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "files" do
  it "edge_file_empty_list" do
    # List files when no files have been uploaded
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "GET",
      status: 200,
      body: '{"data":[],"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "list_files"

  ensure
    server&.stop
  end

  it "edge_file_large_upload" do
    # Upload a large file successfully
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "POST",
      status: 200,
      body: '{"bytes":536870912,"created_at":1711000000,"filename":"large_training_data.jsonl","id":"file-large001","object":"file","purpose":"fine-tune","status":"processed"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_file"

  ensure
    server&.stop
  end

  it "error_file_auth_401" do
    # 401 Unauthorized when listing files with invalid API key
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "GET",
      status: 401,
      body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "list_files"

  ensure
    server&.stop
  end

  it "error_file_bad_purpose" do
    # 400 Bad Request when uploading a file with invalid purpose
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "POST",
      status: 400,
      body: "{\"error\":{\"code\":null,\"message\":\"Invalid value for 'purpose': 'invalid-purpose'. Supported values are: 'fine-tune', 'assistants', 'batch'.\",\"param\":\"purpose\",\"type\":\"invalid_request_error\"}}",
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_file"

  ensure
    server&.stop
  end

  it "error_file_not_found" do
    # 404 Not Found when retrieving a nonexistent file
    route = E2EHelpers::MockRoute.new(
      path: "/files/file-placeholder",
      method: "GET",
      status: 404,
      body: '{"error":{"code":null,"message":"No such File object: file-nonexistent","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "retrieve_file"

  ensure
    server&.stop
  end

  it "smoke_create_file" do
    # Upload a file for use with the API
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "POST",
      status: 200,
      body: '{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "create_file"

  ensure
    server&.stop
  end

  it "smoke_delete_file" do
    # Delete an uploaded file
    route = E2EHelpers::MockRoute.new(
      path: "/files/file-placeholder",
      method: "POST",
      status: 200,
      body: '{"deleted":true,"id":"file-abc123","object":"file"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "delete_file"

  ensure
    server&.stop
  end

  it "smoke_file_content" do
    # Retrieve the content of an uploaded file
    route = E2EHelpers::MockRoute.new(
      path: "/files/file-placeholder/content",
      method: "GET",
      status: 200,
      body: '{"_binary":true,"_content_type":"application/octet-stream","_description":"Mock file content bytes"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "file_content"

  ensure
    server&.stop
  end

  it "smoke_list_files" do
    # List all uploaded files
    route = E2EHelpers::MockRoute.new(
      path: "/files",
      method: "GET",
      status: 200,
      body: '{"data":[{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"},{"bytes":2048,"created_at":1711000100,"filename":"batch_input.jsonl","id":"file-def456","object":"file","purpose":"batch","status":"processed"}],"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "list_files"

  ensure
    server&.stop
  end

  it "smoke_retrieve_file" do
    # Retrieve metadata for an uploaded file
    route = E2EHelpers::MockRoute.new(
      path: "/files/file-placeholder",
      method: "GET",
      status: 200,
      body: '{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "retrieve_file"

  ensure
    server&.stop
  end

end
