# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'moderate' do
  it 'edge_moderate_all_categories: Moderation response with multiple categories flagged' do
    result = LiterLlm.moderate('Extremely harmful content targeting multiple categories')
    expect(result.results.length).to eq(1)
    expect(result.results.get("0").flagged).to be(true)
  end

  it 'edge_moderate_empty_input: Moderation with empty string input' do
    result = LiterLlm.moderate('')
    expect(result.results.length).to eq(1)
    expect(result.results.get("0").flagged).to be(false)
  end

  it 'error_moderate_auth_401: 401 Unauthorized for moderation with invalid API key' do
    expect { LiterLlm.moderate('Hello') }.to raise_error
  end

  it 'error_moderate_bad_request: 400 Bad Request for moderation with invalid model' do
    expect { LiterLlm.moderate('Hello') }.to raise_error
  end

  it 'smoke_moderate_batch: Moderate multiple inputs in a single request' do
    result = LiterLlm.moderate(['Hello world', 'Nice weather today'])
    expect(result.results.length).to eq(2)
    expect(result.results.get("0").flagged).to be(false)
  end

  it 'smoke_moderate_flagged: Moderation detects flagged content' do
    result = LiterLlm.moderate('I want to hurt someone very badly')
    expect(result.results.length).to eq(1)
    expect(result.results.get("0").flagged).to be(true)
  end

  it 'smoke_moderate_single: Moderate a single non-flagged input' do
    result = LiterLlm.moderate('The weather is nice today.')
    expect(result.results.length).to eq(1)
    expect(result.results.get("0").flagged).to be(false)
  end
end
