# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'streaming' do
  it 'anthropic_stream: Streaming chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) yielding multiple SSE chunks' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 3
    expect(result.stream_content).to eq('One Two Three')
    expect(result.stream_complete).to be true
  end

  it 'azure_stream: Streaming chat completion via Azure OpenAI — verifies the azure/ prefix routes correctly and SSE chunks are delivered in the standard OpenAI chat.completion.chunk shape' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 3
    expect(result.stream_content).to eq('1 2 3')
    expect(result.stream_complete).to be true
  end

  it 'basic_stream: Streaming chat completion that produces content across multiple SSE chunks' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 3
    expect(result.stream_content).to eq('1 2 3')
  end

  it 'bedrock_stream: Streaming chat completion via the AWS Bedrock provider using the bedrock/ prefix — verifies SSE chunks are yielded and assembled correctly from the Converse streaming API' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 2
    expect(result.stream_content).to eq('One Two Three')
    expect(result.stream_complete).to be true
  end

  it 'edge_stream_function_call: Streaming chat completion with tool/function call chunks' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 2
  end

  it 'empty_stream: Streaming chat completion that produces no content chunks before the DONE signal' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 0
    expect(result.stream_content).to eq('')
  end

  it 'local_stream_ollama: Streaming chat completion via Ollama local provider with SSE chunks' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 3
    expect(result.stream_content).to eq('1 2 3')
    expect(result.stream_complete).to be true
  end

  it 'stream_content_policy_error: 400 Bad Request error on stream due to content policy violation' do
    expect { LiterLlm.chat_stream(nil) }.to raise_error
  end

  it 'stream_done_signal: Verify that the [DONE] sentinel signal properly terminates the stream' do
    result = LiterLlm.chat_stream(nil)
    expect(result.stream_complete).to be true
    expect(result.stream_content).to eq('Done')
    expect(result.no_chunks_after_done).to be true
  end

  it 'stream_error_401: 401 Unauthorized error on stream initiation before any chunks are received' do
    expect { LiterLlm.chat_stream(nil) }.to raise_error
  end

  it 'stream_multiple_choices: Streaming chat completion with multiple choice outputs (n > 1)' do
    result = LiterLlm.chat_stream(nil)
    expect(result).not_to be_nil
  end

  it 'stream_with_tool_calls: Streaming chat completion where the assistant responds with a tool call across multiple chunks' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 4
    expect(result.finish_reason).to eq('tool_calls')
    expect(result.tool_calls).not_to be_empty
    expect(result.tool_calls.get("0").function.name).to eq('get_weather')
  end

  it 'stream_with_usage: Streaming chat completion that includes a usage summary in the final chunk' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 3
    expect(result.stream_content).to eq('Hi there!')
    expect(result.usage.total_tokens).to eq(18)
  end

  it 'vertex_stream: Streaming chat completion via the Google Vertex AI provider using the vertex_ai/ prefix — verifies SSE chunks from the Gemini streaming endpoint are yielded and assembled correctly' do
    result = LiterLlm.chat_stream(nil)
    expect(result.chunks.length).to be >= 2
    expect(result.stream_content).to eq('One Two Three')
    expect(result.stream_complete).to be true
  end
end
