/* This file is auto-generated by alef. DO NOT EDIT. */
/* E2e tests for category: search */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "liter_llm.h"
#include "test_runner.h"

void test_search_basic(void) {
    /* Basic web search request with a simple query */
    LITERLLMSearchRequest* search_request_handle = literllm_search_request_from_json("{\"model\":\"brave/web-search\",\"query\":\"What is Rust programming language?\"}");
    assert(search_request_handle != NULL && "failed to build request");
    LITERLLMDefaultClient* client = literllm_create_client("test-key", NULL, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMSearchResponse* result = literllm_default_client_search(client, search_request_handle);
    assert(result != NULL && "expected call to succeed");
    literllm_search_response_free(result);
    literllm_search_request_free(search_request_handle);
    literllm_default_client_free(client);
}

void test_search_empty_results(void) {
    /* Web search with a query that returns no results */
    LITERLLMSearchRequest* search_request_handle = literllm_search_request_from_json("{\"model\":\"brave/web-search\",\"query\":\"xyznonexistent12345xyz\"}");
    assert(search_request_handle != NULL && "failed to build request");
    LITERLLMDefaultClient* client = literllm_create_client("test-key", NULL, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMSearchResponse* result = literllm_default_client_search(client, search_request_handle);
    assert(result != NULL && "expected call to succeed");
    literllm_search_response_free(result);
    literllm_search_request_free(search_request_handle);
    literllm_default_client_free(client);
}

void test_search_error_400(void) {
    /* 400 Bad Request error when search query is empty */
    LITERLLMSearchRequest* search_request_handle = literllm_search_request_from_json("{\"model\":\"brave/web-search\",\"query\":\"\"}");
    assert(search_request_handle != NULL && "failed to build request");
    LITERLLMDefaultClient* client = literllm_create_client("test-key", NULL, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMSearchResponse* result = literllm_default_client_search(client, search_request_handle);
    literllm_search_request_free(search_request_handle);
    literllm_default_client_free(client);
    assert(result == NULL && "expected call to fail");
}

void test_search_error_401(void) {
    /* 401 Unauthorized error on web search due to invalid API credentials */
    LITERLLMSearchRequest* search_request_handle = literllm_search_request_from_json("{\"model\":\"brave/web-search\",\"query\":\"test\"}");
    assert(search_request_handle != NULL && "failed to build request");
    LITERLLMDefaultClient* client = literllm_create_client("test-key", NULL, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMSearchResponse* result = literllm_default_client_search(client, search_request_handle);
    literllm_search_request_free(search_request_handle);
    literllm_default_client_free(client);
    assert(result == NULL && "expected call to fail");
}
