/* Code generated by liter-llm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Response completes with empty output items */
static void test_edge_response_empty_output(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-empty001\",\"model\":\"gpt-"
      "4o\",\"object\":\"response\",\"output\":[],\"status\":\"completed\","
      "\"usage\":{\"input_tokens\":0,\"output_tokens\":0,\"total_tokens\":0}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp =
        liter_llm_http_post(url, "{\"input\":\"\",\"model\":\"gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_edge_response_empty_output");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Response created with a very large input text */
static void test_edge_response_large_input(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-large001\",\"model\":\"gpt-"
      "4o\",\"object\":\"response\",\"output\":[{\"content\":[{\"text\":\"The "
      "text is a repetition of the classic Lorem Ipsum placeholder "
      "text.\",\"type\":\"output_text\"}],\"id\":\"msg-large001\",\"role\":"
      "\"assistant\",\"type\":\"message\"}],\"status\":\"completed\",\"usage\":"
      "{\"input_tokens\":850,\"output_tokens\":15,\"total_tokens\":865}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url,
        "{\"input\":\"Summarize the following long text: Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor "
        "sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
        "dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit "
        "amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem "
        "ipsum dolor sit amet. \",\"model\":\"gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_edge_response_large_input");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* 401 Unauthorized when creating a response with invalid API key */
static void test_error_response_auth_401(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API "
      "key provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp =
        liter_llm_http_post(url, "{\"input\":\"Hello\",\"model\":\"gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 401L, "test_error_response_auth_401");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 400 Bad Request when creating response with invalid model */
static void test_error_response_bad_request(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"model_not_found\",\"message\":\"The model "
      "'nonexistent-model' does not "
      "exist.\",\"param\":\"model\",\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"input\":\"Hello\",\"model\":\"nonexistent-model\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 400L, "test_error_response_bad_request");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 404 Not Found when retrieving a nonexistent response */
static void test_error_response_not_found(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":null,\"message\":\"No such Response object: "
      "resp-nonexistent\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses/resp-placeholder", base_url);

    LiterLlmResponse *resp = liter_llm_http_get(url);
    assert(resp != NULL);
    liter_llm_assert_status(resp, 404L, "test_error_response_not_found");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Cancel an in-progress response */
static void test_smoke_cancel_response(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-def456\",\"model\":\"gpt-4o\","
      "\"object\":\"response\",\"output\":[],\"status\":\"cancelled\","
      "\"usage\":{\"input_tokens\":10,\"output_tokens\":0,\"total_tokens\":10}"
      "}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses/resp-placeholder", base_url);

    LiterLlmResponse *resp =
        liter_llm_http_post(url, "{\"response_id\":\"resp-def456\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_smoke_cancel_response");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Create a basic response using the Responses API */
static void test_smoke_create_response(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-abc123\",\"model\":\"gpt-4o\","
      "\"object\":\"response\",\"output\":[{\"content\":[{\"text\":\"Quantum "
      "computing uses quantum bits that can exist in multiple states "
      "simultaneously to solve certain problems exponentially faster than "
      "classical "
      "computers.\",\"type\":\"output_text\"}],\"id\":\"msg-001\",\"role\":"
      "\"assistant\",\"type\":\"message\"}],\"status\":\"completed\",\"usage\":"
      "{\"input_tokens\":12,\"output_tokens\":28,\"total_tokens\":40}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp =
        liter_llm_http_post(url, "{\"input\":\"Explain quantum computing in "
                                 "one sentence.\",\"model\":\"gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_smoke_create_response");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Response that includes tool call output items */
static void test_smoke_response_with_tools(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-tool001\",\"model\":\"gpt-4o\","
      "\"object\":\"response\",\"output\":[{\"arguments\":\"{\\\"location\\\": "
      "\\\"San "
      "Francisco\\\"}\",\"call_id\":\"call-001\",\"id\":\"fc-001\",\"name\":"
      "\"get_weather\",\"type\":\"function_call\"},{\"content\":[{\"text\":"
      "\"The weather in San Francisco is currently 65F and "
      "sunny.\",\"type\":\"output_text\"}],\"id\":\"msg-002\",\"role\":"
      "\"assistant\",\"type\":\"message\"}],\"status\":\"completed\",\"usage\":"
      "{\"input_tokens\":50,\"output_tokens\":35,\"total_tokens\":85}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"input\":\"What is the weather in San "
             "Francisco?\",\"model\":\"gpt-4o\",\"tools\":[{\"description\":"
             "\"Get current weather for a "
             "location\",\"name\":\"get_weather\",\"parameters\":{"
             "\"properties\":{\"location\":{\"type\":\"string\"}},\"required\":"
             "[\"location\"],\"type\":\"object\"},\"type\":\"function\"}]}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_smoke_response_with_tools");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Retrieve a previously created response */
static void test_smoke_retrieve_response(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created_at\":1711000000,\"id\":\"resp-abc123\",\"model\":\"gpt-4o\","
      "\"object\":\"response\",\"output\":[{\"content\":[{\"text\":\"Quantum "
      "computing uses "
      "qubits.\",\"type\":\"output_text\"}],\"id\":\"msg-001\",\"role\":"
      "\"assistant\",\"type\":\"message\"}],\"status\":\"completed\",\"usage\":"
      "{\"input_tokens\":12,\"output_tokens\":8,\"total_tokens\":20}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/responses/resp-placeholder", base_url);

    LiterLlmResponse *resp = liter_llm_http_get(url);
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_smoke_retrieve_response");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

int main(void) {
  test_edge_response_empty_output();
  printf("PASS: Response completes with empty output items\n");
  test_edge_response_large_input();
  printf("PASS: Response created with a very large input text\n");
  test_error_response_auth_401();
  printf(
      "PASS: 401 Unauthorized when creating a response with invalid API key\n");
  test_error_response_bad_request();
  printf("PASS: 400 Bad Request when creating response with invalid model\n");
  test_error_response_not_found();
  printf("PASS: 404 Not Found when retrieving a nonexistent response\n");
  test_smoke_cancel_response();
  printf("PASS: Cancel an in-progress response\n");
  test_smoke_create_response();
  printf("PASS: Create a basic response using the Responses API\n");
  test_smoke_response_with_tools();
  printf("PASS: Response that includes tool call output items\n");
  test_smoke_retrieve_response();
  printf("PASS: Retrieve a previously created response\n");
  printf("All responses tests passed.\n");
  return 0;
}
