// DO NOT EDIT - auto-generated by alef
// alef:hash:48a3e93a21bf7dd19853243fda3a4672d68cd4542223ccc5df778213cfa0a0da
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (400, 405, 413, 422, …).
 */
public class BadRequestException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadRequestException with the given message. */
  public BadRequestException(final String message) {
    super(message);
  }

  /** Creates a new BadRequestException with the given message and cause. */
  public BadRequestException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
