// DO NOT EDIT - auto-generated by alef
// alef:hash:4ecd2aa056846f67dfe9244f4aad064fa7beb3ed27735babdf7dc051c2346c1e
package io.xberg.literllm;

/**
 * An outbound request was blocked by the active `OutboundPolicy`.
 *
 * Returned when `register_custom_provider` is called with a `base_url` that
 * violates the policy (e.g. a private-range IP under `DenyPrivate`), or when
 * the per-connection DNS resolver detects a forbidden address at connect time.
 */
public class OutboundForbiddenException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OutboundForbiddenException with the given message. */
  public OutboundForbiddenException(final String message) {
    super(message);
  }

  /** Creates a new OutboundForbiddenException with the given message and cause. */
  public OutboundForbiddenException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
