// DO NOT EDIT - auto-generated by alef
// alef:hash:ec5599ffa33f79ab77ab36dbfe3d2bf638cd8e5c0dc1ee9a9dcc314aa7632417
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (502, 503, or 504).
 */
public class ServiceUnavailableException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServiceUnavailableException with the given message. */
  public ServiceUnavailableException(final String message) {
    super(message);
  }

  /** Creates a new ServiceUnavailableException with the given message and cause. */
  public ServiceUnavailableException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
