// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8fe7728dd62cd92af576fe1ccf8cbfb835ad14e494447f51765e51755fe72ba
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.literllm.LiterLlm;
import io.xberg.literllm.ChatCompletionRequest;
import java.util.Optional;
import io.xberg.literllm.JsonUtil;

/** E2e tests for category: tool-calling. */
public class ToolCallingTest {


    @Test
    void testAnthropicToolCalling() throws Exception {
        // Chat request to Anthropic provider with a tool definition; assistant responds with a tool call
        var req = JsonUtil.fromJson("{\"max_tokens\":256,\"messages\":[{\"content\":\"What is the weather in London?\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and country, e.g. London, UK\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/anthropic_tool_calling";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(req);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertTrue(java.util.Optional.ofNullable(result.choices().get(0).message().toolCalls()).filter(value -> switch ((Object) value) {
            case CharSequence text -> !text.isEmpty();
            case java.util.Collection<?> items -> !items.isEmpty();
            case java.util.Map<?, ?> entries -> !entries.isEmpty();
            default -> true;
        }).isPresent(), "expected non-empty value");
        assertEquals("get_weather", result.choices().get(0).message().toolCalls().get(0).function().name());
        assertEquals("tool_calls", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse(""));


    }


    @Test
    void testSingleToolCall() throws Exception {
        // Chat request with a tool definition; assistant responds with a tool call
        var req = JsonUtil.fromJson("{\"messages\":[{\"content\":\"What is the weather in San Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and state, e.g. San Francisco, CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/single_tool_call";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(req);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");
        assertTrue(java.util.Optional.ofNullable(result.choices().get(0).message().toolCalls()).filter(value -> switch ((Object) value) {
            case CharSequence text -> !text.isEmpty();
            case java.util.Collection<?> items -> !items.isEmpty();
            case java.util.Map<?, ?> entries -> !entries.isEmpty();
            default -> true;
        }).isPresent(), "expected non-empty value");
        assertEquals("get_weather", result.choices().get(0).message().toolCalls().get(0).function().name());
        assertEquals("tool_calls", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse(""));


    }

}
