// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:liter_llm/liter_llm.dart';

// E2e tests for category: files
void main() {
  test('List files when no files have been uploaded', () async {
    final result = await listFiles();
    expect(result.data.length, equals(0));
  });

  test('Upload a large file successfully', () async {
    final result = await createFile(null);
    expect(result.id, isNotEmpty);
  });

  test('401 Unauthorized when listing files with invalid API key', () async {
    await expectLater(listFiles(), throwsA(isA<Exception>()));
  });

  test('400 Bad Request when uploading a file with invalid purpose', () async {
    await expectLater(createFile(null), throwsA(isA<Exception>()));
  });

  test('404 Not Found when retrieving a nonexistent file', () async {
    await expectLater(retrieveFile('file-nonexistent'), throwsA(isA<Exception>()));
  });

  test('Upload a file for use with the API', () async {
    final result = await createFile(null);
    expect(result.id, isNotEmpty);
  });

  test('Delete an uploaded file', () async {
    final result = await deleteFile('file-abc123');
    expect(result.id, isNotEmpty);
    expect(result.deleted, equals(true));
  });

  test('Retrieve the content of an uploaded file', () async {
    final result = await fileContent('file-abc123');
    expect(result.content, isNotEmpty);
  });

  test('List all uploaded files', () async {
    final result = await listFiles();
    expect(result.data.length, equals(2));
  });

  test('Retrieve metadata for an uploaded file', () async {
    final result = await retrieveFile('file-abc123');
    expect(result.id, isNotEmpty);
  });

}
