#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed
set -euo pipefail

test_batch_embed() {
    # Embedding request with multiple input strings returns one embedding object per input
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 2 ] || exit 1
    local count_data_0__embedding
    count_data_0__embedding=$(echo "$output" | jq '.data[0].embedding | length')
    [ "$count_data_0__embedding" -eq 5 ] || exit 1
}

test_edge_embed_batch_input() {
    # Embedding request with multiple inputs returns multiple embedding objects
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 2 ] || exit 1
    local val_data_0__index
    val_data_0__index=$(echo "$output" | jq -r '.data[0].index')
    assert_equals "$val_data_0__index" '0' 'data[0].index'
    local val_data_1__index
    val_data_1__index=$(echo "$output" | jq -r '.data[1].index')
    assert_equals "$val_data_1__index" '1' 'data[1].index'
}

test_edge_embed_empty_input() {
    # Embedding request with empty string input returns empty data array
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 0 ] || exit 1
}

test_embed_encoding_format() {
    # Embedding request with explicit encoding_format of float returns float array embeddings
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 1 ] || exit 1
    local count_data_0__embedding
    count_data_0__embedding=$(echo "$output" | jq '.data[0].embedding | length')
    [ "$count_data_0__embedding" -eq 5 ] || exit 1
}

test_embed_error_401() {
    # 401 Unauthorized error on embedding request when API key is invalid
    if liter_llm chat >/dev/null 2>&1; then
        echo 'FAIL [error]: expected command to fail but it succeeded' >&2
        return 1
    fi
}

test_embed_with_dimensions() {
    # Embedding request with explicit dimensions parameter returns embeddings of the requested size
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 1 ] || exit 1
    local count_data_0__embedding
    count_data_0__embedding=$(echo "$output" | jq '.data[0].embedding | length')
    [ "$count_data_0__embedding" -eq 8 ] || exit 1
}

test_local_embed_ollama() {
    # Embedding request via Ollama local provider with all-minilm model
    local output
    output=$(liter_llm chat)

    local count_data
    count_data=$(echo "$output" | jq '.data | length')
    [ "$count_data" -eq 1 ] || exit 1
    local count_data_0__embedding
    count_data_0__embedding=$(echo "$output" | jq '.data[0].embedding | length')
    [ "$count_data_0__embedding" -eq 32 ] || exit 1
}

run_tests_embed() {
    run_test test_batch_embed
    run_test test_edge_embed_batch_input
    run_test test_edge_embed_empty_input
    run_test test_embed_encoding_format
    run_test test_embed_error_401
    run_test test_embed_with_dimensions
    run_test test_local_embed_ollama
}
