// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31ef34018155c64886a6f5f47f696331cb79ed3a400b7fb549953ba87934a5a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: batches
package e2e_test

import (
	"strings"
	"testing"

	pkg "liter_llm"
)

func Test_EdgeBatchAlreadyCancelled(t *testing.T) {
	// Attempt to cancel an already-cancelled batch
	_, err := pkg.CancelBatch(`batch-cancelled001`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_EdgeBatchEmptyList(t *testing.T) {
	// List batches when no batches exist
	result, err := pkg.ListBatches(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Data), 0, "expected exactly 0 elements")
}

func Test_ErrorBatchAuth401(t *testing.T) {
	// 401 Unauthorized when creating a batch with invalid API key
	_, err := pkg.CreateBatch(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorBatchInvalidFile(t *testing.T) {
	// 400 Bad Request when creating a batch with invalid input file
	_, err := pkg.CreateBatch(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorBatchNotFound(t *testing.T) {
	// 404 Not Found when retrieving a nonexistent batch
	_, err := pkg.RetrieveBatch(`batch-nonexistent`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_SmokeBatchCompleted(t *testing.T) {
	// Retrieve a completed batch job with output file
	result, err := pkg.RetrieveBatch(`batch-ghi789`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.ID) == 0 {
		t.Errorf("expected non-empty value")
	}
	if strings.TrimSpace(result.Status) != `completed` {
		t.Errorf("equals mismatch: got %v", result.Status)
	}
}

func Test_SmokeCancelBatch(t *testing.T) {
	// Cancel a running batch job
	result, err := pkg.CancelBatch(`batch-def456`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.ID) == 0 {
		t.Errorf("expected non-empty value")
	}
	if strings.TrimSpace(result.Status) != `cancelling` {
		t.Errorf("equals mismatch: got %v", result.Status)
	}
}

func Test_SmokeCreateBatch(t *testing.T) {
	// Create a new batch processing job
	result, err := pkg.CreateBatch(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.ID) == 0 {
		t.Errorf("expected non-empty value")
	}
	if strings.TrimSpace(result.Status) != `validating` {
		t.Errorf("equals mismatch: got %v", result.Status)
	}
}

func Test_SmokeListBatches(t *testing.T) {
	// List all batch jobs
	result, err := pkg.ListBatches(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Data), 2, "expected exactly 2 elements")
}

func Test_SmokeRetrieveBatch(t *testing.T) {
	// Retrieve the status of a batch job
	result, err := pkg.RetrieveBatch(`batch-abc123`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.ID) == 0 {
		t.Errorf("expected non-empty value")
	}
	if strings.TrimSpace(result.Status) != `in_progress` {
		t.Errorf("equals mismatch: got %v", result.Status)
	}
}
