// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: cache
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "liter_llm"
)

func Test_CacheHit(t *testing.T) {
	// Tests that identical chat requests return cached response
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, result.CacheHit, "expected true")
}

func Test_CacheMissTtl(t *testing.T) {
	// Tests that cache expires after TTL
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, result.CacheHit, "expected true")
}

func Test_CacheOpendalMemory(t *testing.T) {
	// Cache hit with OpenDAL memory backend returns cached response on repeat request
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, result.CacheHit, "expected true")
}

func Test_CacheStreamBypass(t *testing.T) {
	// Tests that streaming requests bypass cache entirely
	result, err := pkg.chat_stream(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.True(t, result.CacheBypassed, "expected true")
}
