// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bd2519d40f376be867de515d5c1273618b62735a89533beb24bd00bb73d6881
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: configuration
package e2e_test

import (
	"strings"
	"testing"

	pkg "liter_llm"
)

func Test_CustomBaseUrl(t *testing.T) {
	// Client configured with a custom base URL routes all requests to that endpoint
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].Message.Content) != `Hi there!` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].Message.Content)
	}
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
	if strings.TrimSpace(result.Model) != `local-model` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_ExtraHeaders(t *testing.T) {
	// Client configured with extra custom headers successfully completes a chat request
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
}

func Test_LocalProviderLlamacpp(t *testing.T) {
	// llamacpp local provider routes requests via llamacpp/ model prefix with no auth
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].Message.Content) != `Hi there! I'm running locally.` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].Message.Content)
	}
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
	if strings.TrimSpace(result.Model) != `my-model` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_LocalProviderOllama(t *testing.T) {
	// Ollama local provider routes requests via ollama/ model prefix with no auth
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].Message.Content) != `Hello! How can I help you today?` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].Message.Content)
	}
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
	if strings.TrimSpace(result.Model) != `qwen2:0.5b` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_LocalProviderVllm(t *testing.T) {
	// vLLM local provider routes requests via vllm/ model prefix with no auth
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].Message.Content) != `Hello! How may I assist you?` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].Message.Content)
	}
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
	if strings.TrimSpace(result.Model) != `meta-llama/Llama-3.2-1B` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}
