// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:05a882cfdeb3af5246127047f67d40092b7c804a79dd02bd55c7ccb589e8b6bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: contract
package e2e_test

import (
	"strings"
	"testing"

	pkg "liter_llm"
)

func Test_BindingApiParity(t *testing.T) {
	// Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
	result, err := pkg.Chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(result.Choices["0"].Message.Content) != `OK` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].Message.Content)
	}
	if strings.TrimSpace(result.Choices["0"].FinishReason) != `stop` {
		t.Errorf("equals mismatch: got %v", result.Choices["0"].FinishReason)
	}
	if result.Usage.TotalTokens != 6 {
		t.Errorf("equals mismatch: got %v", result.Usage.TotalTokens)
	}
	if strings.TrimSpace(result.Model) != `gpt-4o` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_ContractOcr(t *testing.T) {
	// Verify ocr() method exists in all bindings
	_, err := pkg.Ocr(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ContractSearch(t *testing.T) {
	// Verify search() method exists in all bindings
	_, err := pkg.Search(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
