// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6dcf635ec7085cbe940513a8c744ff462c39dbdebb1fbe20590280538d40c4e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: custom_provider
package e2e_test

import "testing"

func Test_ProviderAuth(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}

func Test_RegisterProvider(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}
