// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9083c88665538425f346d7f3ce6f9891378e3f84a2b732d410d6691701ecf8f3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: list-models
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "liter_llm"
)

func Test_EmptyModelList(t *testing.T) {
	// List models response returns an empty data array when no models are available
	result, err := pkg.ListModels(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Data), 0, "expected at least 0 elements")
	assert.Equal(t, len(result.Data), 0, "expected exactly 0 elements")
}

func Test_ListModelsError401(t *testing.T) {
	// 401 Unauthorized error on list models request when API key is invalid
	_, err := pkg.ListModels(`{}`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ListModelsError500(t *testing.T) {
	// 500 Internal Server Error when listing models due to server failure
	_, err := pkg.ListModels(`{}`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ListModelsFiltered(t *testing.T) {
	// List models response with multiple model objects
	result, err := pkg.ListModels(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Data), 5, "expected at least 5 elements")
	if strings.TrimSpace(result.Data["0"].Object) != `model` {
		t.Errorf("equals mismatch: got %v", result.Data["0"].Object)
	}
}
