// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6ec3f62b7896b1e6d78573bfa441f7055cad6bd37e0948a42395ba52899eb63
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: list-models
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "liter_llm"
)

func Test_EmptyModelList(t *testing.T) {
	// List models response returns an empty data array when no models are available
	err := pkg.ListModels()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListModelsError401(t *testing.T) {
	// 401 Unauthorized error on list models request when API key is invalid
	err := pkg.ListModels()
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ListModelsError500(t *testing.T) {
	// 500 Internal Server Error when listing models due to server failure
	err := pkg.ListModels()
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ListModelsFiltered(t *testing.T) {
	// List models response with multiple model objects
	err := pkg.ListModels()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
