// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6ec3f62b7896b1e6d78573bfa441f7055cad6bd37e0948a42395ba52899eb63
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: list-models
package e2e_test

import "testing"

func Test_EmptyModelList(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}

func Test_ListModelsError401(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}

func Test_ListModelsError500(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}

func Test_ListModelsFiltered(t *testing.T) {
	t.Skip("Go binding does not expose a configured e2e callable for this fixture")
}
