// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e18f3d6302923ccb77aa86dee0a8e487bb7b3b7e49543c799ce559856461b68f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: ocr
package e2e_test

import (
	"testing"

	pkg "liter_llm"
)

func Test_OcrError400(t *testing.T) {
	// 400 Bad Request error when OCR input has an invalid image format
	_, err := pkg.ocr(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_OcrError401(t *testing.T) {
	// 401 Unauthorized error on OCR request due to invalid API credentials
	_, err := pkg.ocr(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_OcrMultiPage(t *testing.T) {
	// OCR request returning multiple pages of document content
	result, err := pkg.ocr(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.Equal(t, len(result.Pages), 2, "expected exactly 2 elements")
	if result.Pages["0"].Index != 0 {
		t.Errorf("equals mismatch: got %v", result.Pages["0"].Index)
	}
	if result.Pages["1"].Index != 1 {
		t.Errorf("equals mismatch: got %v", result.Pages["1"].Index)
	}
}

func Test_OcrUrlDocument(t *testing.T) {
	// OCR request with a document URL input
	_, err := pkg.ocr(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
